### ISSUE TITLE
hyphenation dictionaries in spellcheck stuff?

### ISSUE THREAD

**Issue by mapreri** [Sigil-Ebook/Sigil#133]
in src/Resource_Files/dictionaries/ there are hyphenation dictionaries.
Also, in src/Misc/SpellCheck.cpp there is

```cxx
    // Dictionary files to use.
    QString aff = QString("%1%2.aff").arg(m_dictionaries.value(name)).arg(name);
    QString dic = QString("%1%2.dic").arg(m_dictionaries.value(name)).arg(name);
    QString hyph_dic = QString("%1hyph_%2.dic").arg(m_dictionaries.value(name)).arg(name);
    // Create a new hunspell object.
    m_hunspell = new Hunspell(aff.toLocal8Bit().constData(), dic.toLocal8Bit().constData());

    // Load the hyphenation dictionary if it exists.
    if (QFile::exists(hyph_dic)) {
        m_hunspell->add_dic(hyph_dic.toLocal8Bit().constData());
    }
```

This makes me somewhat confused, hyphenation patterns are not really usable by hunspell (they are used by libhyphen).
Clearly hunspell is able to deal with broken dictionaries if it does not boil out, but imho both those dictionaries and the hyphenation-related code should just go away.

**Comment by kevinhendricks** [comment]
Hi,
That was certainly true when I created MySpell for OpenOffice.org  so I can't see any reason for it to have changed under Hunspell.   I just want to verify that hunspell has not added any hyphenation support and if not, I will remove these.

Nice Catch!

Kevin

**Comment by mapreri** [comment]
On Tue, Oct 13, 2015 at 09:54:43AM -0700, Kevin Hendricks wrote:
> That was certainly true when I created MySpell for OpenOffice.org

You mean, MySpell did not fail on invalid dicts?

> I just want to verify that hunspell has not added any hyphenation
> support

That would be a nice discovery for me :)

**Comment by kevinhendricks** [comment]
Hi,
No I meant that Myspell never added hyphenation support.  I did not pay much attention after I retired from OOo lingucomponent and did not know if hunspell had added that or not.

It didn't so I will remove the code that loads the hyphenation dictionary but keep them for plugin use via libhyphen.  I think the person who committed this thought he was committing the raw hyphenated word list used to create the hyphen dic itself.  I can't figure out any other good reason.

Thanks,

Kevin

**Comment by mapreri** [comment]
if that can I ask you to move the hyphenation pattern to another directory?
That way I can (vendor side => debian) symlink that directory to the one containing system-wide dictionaries, which is different than the one containing hunspell's (/usr/share/hunspell vs /usr/share/hyphen).

**Comment by kevinhendricks** [comment]
Hi,

Unfortunately, that would mean changing the plugin interface we have just established to pass along yet another directory location to the plugin code.

I wouldn’t worry about it.  I may replace them with the raw hyphenated lists, I have just not decided yet.

Take care,

Kevin

**Comment by mapreri** [comment]
ok, thanks for everything!

**Comment by kevinhendricks** [comment]
Closing this, I just pushed the change to remove the loading of the hyphenation dics into Hunspell.  Just commented out most of it and I may want to revisit this with the raw hyphenation dictionaries if I can find any with the right licenses to fit with gpl3.

Thanks!

Kevin

**Comment by eli-schwartz** [comment]
On my ArchLinux machine, there are compatibility symlinks in `/usr/share/myspell/dicts/` for all the files in both `/usr/share/hunspell` and `/usr/share/hyphen`.

On the basis of that, I propose this commit eli-schwartz/Sigil@cbd5efaf32258e42c2b09a539e82647695359886 which tells Sigil to look in that directory for hunspell dictionaries rather than installing its own, if `USE_SYSTEM_LIBS` is in play.
I can open a pull request, but first I'd like to know whether that works on other distros, and/or whether it is important to be able to specify the directory to cmake.


This is an alternative to #134.


@mapreri, what do you say?

**Comment by mapreri** [comment]
@eli-schwartz Well, in Debian I'm trying to ditch myspell, since everything is already migrated to hunspell and the only myspell stuff remaining are only the package names and some symlinks.
Btw, if building with USE_SYSTEM_LIBS (or anything else) triggers the use of /usr/share/hunspell/ instead of sigil's dicts I'd just be happy.  So your commit would be fine to me.

In debian we're using /usr/share/hunspell/ for hunspell dictionaries, and I'm trying to stop installing stuff in myspell-related directories, since nothing is left that reads it (and if it does, then it's already bugged, as myspell itself is long gone from debian).  Furthermore I don't understand why you symlink in that directory hunspell and hyphen dictionaries, doesn't look sane to me.

**Comment by toddcarnes** [comment]
Are the two dictionaries interchangeable/compatible?

**Comment by eli-schwartz** [comment]
The reason ArchLinux symlinks those dictionaries is I guess because they are supposed to be interchangeable, and the Arch devs decided to simplify things by not having an extra package with the same stuff/symlinks.

So it's not as nice as getting every program out there to look in the newer, individual hyphen/hunspell directories ;) it still works.


I guess the alternative is to simply use the main hunspell location and any plugins which rely on hyphenation dictionaries are out in the cold.
Or else teach the plugin launcher a separate way to find hyphen dictionaries.

**Comment by eli-schwartz** [comment]
See #139
