### ISSUE TITLE
Sigil adds empty lines on save

### ISSUE THREAD

**Issue by ordtrogen** [Sigil-Ebook/Sigil#138]
Windows 7 Professional, SP 1

Each time I press "save", Sigil adds empty lines after any <br/> tags. See pictures

![problem1](https://github-cloud.s3.amazonaws.com/assets/15184875/10566112/36d31dfc-75de-11e5-8335-688c7dcbd2e6.png)
![problem2](https://github-cloud.s3.amazonaws.com/assets/15184875/10566111/36cff2d0-75de-11e5-8026-74d38ed5f202.png)
![problem3](https://github-cloud.s3.amazonaws.com/assets/15184875/10566113/36d362ee-75de-11e5-8c5c-69472f8548f6.png)
![version](https://github-cloud.s3.amazonaws.com/assets/15184875/10566114/36d3b0aa-75de-11e5-9fba-c0a5ac5cd762.png)

**Comment by kevinhendricks** [comment]
Please check your Sigil Preferences and let me know if you have enabled Clean on Save or not and what cleaning you have selected: PrettyPrint Gumbo, or just normal gumbo cleaning so I know where to start looking for the bug.

Thanks,

KevinH

**Comment by ordtrogen** [comment]
I just installed and began using Sigil, so I suppose I use the defaults.


[image: Infogad bild 1]

2015-10-19 1:03 GMT+02:00 Kevin Hendricks <notifications@github.com>:

> Please check your Sigil Preferences and let me know if you have enabled
> Clean on Save or not and what cleaning you have selected: PrettyPrint
> Gumbo, or just normal gumbo cleaning so I know where to start looking for
> the bug.
>
> Thanks,
>
> KevinH
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sigil-Ebook/Sigil/issues/138#issuecomment-149060092>.
>



-- 
Johan von Boisman
F:a Ordtrogen Översättning
Göteborg, SWEDEN
Telefon:   +46 709 46 65 26
Skype:    johan_v_b

**Comment by kevinhendricks** [comment]
Just committed fix for this into master.  Fix will appear in the next release.  

BTW: I strongly recommend you change your Sigil preferences to only use PrettyPrinting when text is in a horrible condition and not repeatedly for every save.

There are simply too many combinations for pretty printing to always be robust especially since html5 now allows text NOT inside p tags to exist in blockquotes when previously it was not allowed.

Thanks for bug report.  Closing this issue.
