### ISSUE TITLE
Table of Content looks cutted

### ISSUE THREAD

**Issue by daspisch** [Sigil-Ebook/Sigil#140]
When i generating my epub using Sigil 0.8.901 for OSX Table of Content end unexpectly, firs i think what it is because large table of content(>100 points) but when i reduce size of ToC nothing changed - part of ToC just cutted. I've tryed to open generated epub by Calibrie and iBooks

**Comment by kevinhendricks** [comment]
- What version of OS X.  We have had problem reports with El Capitan.
- How do you mean missing?  
- Did they appear in the gui window that allows you to select and manipulate which headings you want in the finished ToC.  Was their associated checkbox checked? 
- Have you run the FlightCrew plugin to make sure all of your xhtml files are properly linked into the content.opf and that there are no parsing issues or problems with your epub?
- Exactly what part of the ToC went away?  Was it confined to a single file or many files?
- Do you have a test case you could post somewhere and then post the link here so that I can grab it and recreate what you are seeing?   Without an epub that shows the issue, we may have no way of tracking it down, as all epubs I have tested with the ToC generation button all seem to work just fine.

**Comment by kevinhendricks** [comment]
I grabbed your test case (and I removed the link and decryption key from your Sigil Issue 140 post).
Thanks for the test case.  I will look at it tonight after work and let you know.

**Comment by kevinhendricks** [comment]
Yes, definite bug.  Exists in all previous versions of Sigil I have tested, so the bug is long before my time here.  I think the problem happens because of constantly changing the end condition of a for loop inside the loop by removing elements from the container when trying to build a hierarchical list of headings.  I will rewrite the code to prevent that nonsense.  Hopefully the fix will appear in the next release.

Thank you for your bug report and especially the test case that helped me track it down.

**Comment by toddcarnes** [comment]
Of course, those of use who receive these posts by email received both 
the link and the key. (Not that I, personally, have any use for them, 
but it IS a security risk for the OP.) :)

Todd

**Comment by kevinhendricks** [comment]
Hi,

Good point!  I did not expect a test case book that would need to be decrypted when I asked for a test case.  I guess Sigil should look at finding a better bug/issue software that allows private attachments.

Thanks,

Kevin

**Comment by kevinhendricks** [comment]
Just committed the fix for this to master.  The fix will appear in the upcoming Sigil 0.9.0 release which hopefully will happen in a few weeks or less.
