### ISSUE TITLE
Opening/Closing software can be very slow after copy&paste big amount of text

### ISSUE THREAD

**Issue by firstrose** [Sigil-Ebook/Sigil#151]
I found sigil.ini would be very large and "clipboardringhistory" takes most space. After removing the line, Sigil will become normal again.

Please limit count of preserved clipboard history.

Add "editing clipboard history" feature will also be a good solution.

Thanks

**Comment by kevinhendricks** [comment]
Limiting clip count won't work as even a single clip can be too large.  Cutting at a byte count size can end up with incomplete clip.  

I think the long term simplest solution is for the Sigil -> Paste from ClipBoard History dialog to add a clear all entries button or a way to selectively delete the clipboard entires.  We will look into adding something like that in the future.  Right now our focus is on getting simple epub3 editing working.

So I will leave this issue open as a reminder.

Thanks,

**Comment by kevinhendricks** [comment]
BTW, yor can already clear the clip history be highlighting any items you desire and hitting either delete or delete forward key depending on you keyboard key mapping.

**Comment by kevinhendricks** [comment]
Changed "Paste From Clipboard History" to be "Edit / Paste From Clipboard History".    This dialog now allows use of either the delete key or the backspace key to delete selected clipboard history entries, and adds a "Save" button to keep those changes.  Upon exiting Sigil, the newly shortened clipboardHistory will be saved in the "ini".

Closing this as fixed in master
