### ISSUE TITLE
Use standard paths for installed libraries/binaries at Linux

### ISSUE THREAD

**Issue by anatol** [Sigil-Ebook/Sigil#154]
Linux as well as other Unixes have conventions where application files should be located. Binaries should be put to $PREFIX/bin (e.g. /usr/bin) shared libraries should be in $PREFIX/lib/

Currently Sigil uses non-standard location for those /usr/lib/sigil/{sigil,libsigilgumbo.so}. This requires wrappers to set LD_LIBRARY_PATH as well as it might confuse packaging tools.

It is better to use standard location for the files:

 remove current wrapper /usr/bin/sigil
 /usr/lib/sigil/sigil => /usr/bin/sigil
 /usr/lib/sigil/libsigilgumbo.so => /usr/lib/libsigilgumbo.so

Or at least provide a build time option that allows to do this. I would like to use that at Linux Arch.

I just moved the files manually and Sigil tool works fine.

**Comment by mapreri** [comment]
On Fri, Nov 13, 2015 at 04:28:32PM -0800, Anatol Pomozov wrote:
> Linux as well as other Unixes have conventions where application files should be located. Binaries should be put to $PREFIX/bin (e.g. /usr/bin) shared libraries should be in $PREFIX/lib/
> 
> Currently Sigil uses non-standard location for those /usr/lib/sigil/{sigil,libsigilgumbo.so}. This requires wrappers to set LD_LIBRARY_PATH as well as it might confuse packaging tools.

I totally agree, but given that the gain is really null, I've given up
on this, and in Debian we just use the file as installed by the sigil
build system.

>  remove current wrapper /usr/bin/sigil
>  /usr/lib/sigil/sigil => /usr/bin/sigil

though this is also handy to be able to set other stuff, like
SIGIL_DICTIONARIES to a system-wide path.

>  /usr/lib/sigil/libsigilgumbo.so => /usr/lib/libsigilgumbo.so

pretty sure libsigilgumpo is not supposed to be a public, shared
library...
though it's actually treated as such by sigil.

just my 2¢

-- 
regards,
                        Mattia Rizzolo

GPG Key: 66AE 2B4A FCCF 3F52 DA18  4D18 4B04 3FCD B944 4540      .''`.
more about me:  http://mapreri.org                              : :'  :
Launchpad user: https://launchpad.net/~mapreri                  `. `'`
Debian QA page: https://qa.debian.org/developer.php?login=mattia  `-

**Comment by kevinhendricks** [comment]
libsigilgumbo.so  needs to be a shared library so Sigil’s python plugins can access those routines via ctypes.  It should never be linked to anything outside of Sigil.    We renamed it to sigilgumbo to prevent any name collision with official gumbo libraries if they exist on someone’s system (our version has unique changes not needed upstream.

**Comment by kevinhendricks** [comment]
BTW:

Lots of more substantial apps (OpenOffice/LibreOffice), java, etc, etc use scripts that wrapper other executables, to set private LD_LIBRARY_PATH allow auto versioning  and the like.

You keep thinking in terms of small apps that fit nicely into the old unix structure.  Think more along the lines of app wrappers and ways to keep private copies of shared libraries and things for more complex apps.

A better model might be Mac OS X which uses a hybrid model. It keeps the nice standard unix install locations for utilities and simple libs, but then introduces a signed app container that contains its own resources that can be validated upon launch.  A similar approach is being used for more complex system level tools in the form of Frameworks (again which can be code-sgined and have limited capabilities).

These types of app containers are coming to Linux.  

Kevin

**Comment by mapreri** [comment]
On Fri, Nov 13, 2015 at 04:56:32PM -0800, Kevin Hendricks wrote:
> Lots of more substantial apps (OpenOffice/LibreOffice), java, etc, etc use scripts that wrapper other executables, to set private LD_LIBRARY_PATH allow auto versioning  and the like.

yeah, indeed I'm pretty ok with the current way sigil is installed.
a launching script makes sense, given that there is no simple way to
1) set SIGIL_DICTIONARIES otherwise
2) keep libsigilgumbo out of the standard shared lib directory and yet
use it as a shared lib... (sorry, didn't think about plugins before)

> You keep thinking in terms of small apps that fit nicely into the old unix structure.  Think more along the lines of app wrappers and ways to keep private copies of shared libraries and things for more complex apps.
> 

1) private copies of shared libs are are better avoided if they can be
2) sigil is not a so (architectural) complex app

> A better model might be Mac OS X which uses a hybrid model. It keeps the nice standard unix install locations for utilities and simple libs, but then introduces a signed app container that contains its own resources that can be validated upon launch.  A similar approach is being used for more complex system level tools in the form of Frameworks (again which can be code-sgined and have limited capabilities).
> 
> These types of app containers are coming to Linux.  

I really look forward to see this!
It'd be awesome, even if with my "debian developer culture" I keep
thinking private copies of shared libs are mostly bad and not so often
needed as it might seem.
https://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles
https://www.debian.org/doc/debian-policy/footnotes.html#f30

Still, containerizing apps is really awesome :)

-- 
regards,
                        Mattia Rizzolo

GPG Key: 66AE 2B4A FCCF 3F52 DA18  4D18 4B04 3FCD B944 4540      .''`.
more about me:  http://mapreri.org                              : :'  :
Launchpad user: https://launchpad.net/~mapreri                  `. `'`
Debian QA page: https://qa.debian.org/developer.php?login=mattia  `-

**Comment by dougmassay** [comment]
Please keep in mind that sigil binary was moved from PREFIX/share/Sigil to PREFIX/lib/sigil/ to comply with this request:

https://github.com/Sigil-Ebook/Sigil/pull/57

Also, if you launch Sigil without a launch script, it very well-may run (as the rpath is set to the Qt5 location), but plugins probably won't work at all.

So I'm afraid I'm going to have to respectfully say no to the original request. The launch script will go in PREFIX/bin and the binary will stay in PREFIX/lib/sigil. Too much relies on these locations to change it now. And too much runtime flexibility relies on environment variables being set in the launch script to consider eliminating the launch script.

**Comment by mapreri** [comment]
On Fri, Nov 13, 2015 at 05:27:54PM -0800, Doug Massay wrote:
> Please keep in mind that sigil binary was moved from PREFIX/share/Sigil to PREFIX/lib/sigil/ to comply with this request:
> 
> https://github.com/Sigil-Ebook/Sigil/pull/57

this was about moving arch-dependant stuff out of /usr/share to
/usr/lib, which was actually a issue and was actually wrong (FHS-wise)
The script was introduced in
https://github.com/Sigil-Ebook/Sigil/pull/42

-- 
regards,
                        Mattia Rizzolo

GPG Key: 66AE 2B4A FCCF 3F52 DA18  4D18 4B04 3FCD B944 4540      .''`.
more about me:  http://mapreri.org                              : :'  :
Launchpad user: https://launchpad.net/~mapreri                  `. `'`
Debian QA page: https://qa.debian.org/developer.php?login=mattia  `-

**Comment by kevinhendricks** [comment]
since okay with script use as is, closing this

**Comment by anatol** [comment]
> but given that the gain is really null

Following standards and common conventions is not null. Breaking standards is definitely _a bad thing_. Especially if there is no reason to break it.

It is not just a theoretical question. At Linux Arch sigil package had been broken for a while because build scripts did not catch *.so file dependency as sigil uses non-standard location for it.

> Lots of more substantial apps (OpenOffice/LibreOffice), java, etc, etc use scripts that wrapper other executables, to set private LD_LIBRARY_PATH allow auto versioning  and the like.
>
> You keep thinking in terms of small apps that fit nicely into the old unix structure.  Think more along the lines of app wrappers and ways to keep private copies of shared libraries and things for more complex apps.

Your point of view is that Sigil is the central application at a user system and it is OK if it breaks common conventions. My point of view is system-level. I support 100+ Arch packages and one of my goals to keep applications consistent with each other. Projects that use non-standard installation paths are just looking for problems. Similar situation with applications that have UI non-consistent with the rest of the system (not in case of Sigil but some other apps do). Its developers might think that having non-standard UI tricks makes it look cool but in reality it usually looks ugly.

System administrators and DevOps who deal with many applications have similar attitude. Applications should be consistent with each other, it reduces mental load and maintenance burden.

> Also, if you launch Sigil without a launch script, it very well-may run (as the rpath is set to the Qt5 location), but plugins probably won't work at all.

You basically want to modify part of application and there are several ways to do this:
 - use compile-time option. From your comments above I think it is what you want.
 - use a config file in /etc, or configuration via UI
 - use command line options. Though it is more typical for command-line tools.

Using environment variables to modify application run-time behavior is so eighties. Having a wrapper shell script to set these variables before executing the binary is definitely a bad practice.

The plugin path is easy to configure at compile time, no need to use trick with environment variables.

> We renamed it to sigilgumbo to prevent any name collision with official gumbo libraries if they exist on someone’s system

It is OK to have this library in /usr/lib if it does not conflict with upstream library name. Another option is to add /usr/lib/sigil to ld.so.conf but for me it sounds overkill.

Do not try to overcomplicate the things. Keep it simple. Package maintainers and future contributors will say "thanks" to you.

**Comment by kevinhendricks** [comment]
We will agree to disagree.  We do not want to modify the plugin launcher scripts as we release changes/updates to them separately.  

Forcing apps to spread themselves all over the place is so 70s and fit with unix at that time, but as I said app containers are coming to linux, along with launch time code signature verification and the like.

If you think using scripts to launch and controls things are bad design, then Linux is full of it.  This is how the KDE Desktop works, most major applications, Qt itself, LibreOffice, and the like because they do not fit the now quite old unix package design.

The launch script works..  Apps should be able to have private shared libs, common system libs are no longer included so no duplication is done, building Sigil on Linux is now quite simple, we have reduced the number of required user packages, ... etc  and yet you still complain about a startup script and environment vars that are used all throughout Linux.

Sorry, not going to happen.

**Comment by eli-schwartz** [comment]
@anatol, when you say the Arch package was "broken", what do you mean?
It ran just fine for me...

If you are referring to the changes from my bug report, yes, the bundled hunspell,minizip, etc. were used instead of the system ones, that isn't "broken", that is "non-optimal packaging" which is something we care about more than they do. :wink:
It is far, far more important for those purposes, that there is now documentation [BuildingOnLinux.md] (https://github.com/Sigil-Ebook/Sigil/blob/master/docs/BuildingOnLinux.md) which describes those options and alerts packagers that they should do so.
Granted, it did not actually mention those options until prompted by my abortive PR #139...
I'm sure that was an oversight. :smiley: But now it does, and all is well again.

And given that they want to be able to bundle those dependencies (which makes sense for Windows/OSX, and perhaps when they get a standalone binary release for linux worked out), I don't see why it makes sense to install them in /usr/lib/ -- for one, if someone built it themselves, rather than using a distro package, wouldn't that overwrite the system copy...
If sigil wants to (optionally, by default) ship its own copies of system libs, I would much rather they keep it separate!
From a distro perspective it makes no sense to ship bundled dependencies, basically ever, but upstream has the right to think about other use-cases, and their current solution works fine.
And moving libsigilgumbo on its own is aesthetically pleasing but otherwise a no-op.


re: the launch script wrapper, doug pointed out in my PR
> Nor am I crazy about making [wrapper.py] (https://github.com/Sigil-Ebook/Sigil/blob/master/src/Resource_Files/plugin_launchers/python/wrapper.py) a file that needs to be configured first. It's important for the plugin framework to remain a standalone (and fully functional) unit which can be easily released separately if need be.

which is fair and probably necessitates the wrapper on its own.
The plugin launcher needs to know where SIGIL_SHARE_PREFIX was at build time, do you have a better way to guarantee it can find out?

...

...

AFAICT, this is essentially nothing but a documentation issue. Which is fixed.
