### ISSUE TITLE
FlightCrew default python interpreter (Windows 7)

### ISSUE THREAD

**Issue by mrprobert** [Sigil-Ebook/Sigil#155]
Initial FlightCrew plugin install sets the default interpreter to a local executable (python 2.7 in my case) and FlightCrew barfs when run. The fix is to check the use bundled python box. Shouldn't the bundled interpreter be the default option?

**Comment by kevinhendricks** [comment]
Initial install of flightcrew does nothing.  In that same preferences window you can choose whatever python engine you like as long as its bitness (32 vs 64) matches that of Sigil.

A new install of Sigil should default to use embedded via the Sgil.ini file, but if in earlier versions you selected an external interpreter it will be remembered and used.

**Comment by dougmassay** [comment]
The bundled interpreter is the default on a brand-new Sigil installation. But if external interpreters were setup on previous Sigil versions, then the box will not be checked. That way we don't break someone's existing custom plugins by hijacking their working python environment.

Sigil is probably barfing on the  Flightcrew plugin because of an architecture mismatch between Sigil and your python2.7. If Sigil is 64-bit, any external python interpreters used for Sigil plugins also needs to be 64-bit.

**Comment by kevinhendricks** [comment]
closing this since not an actual bug
