### ISSUE TITLE
Ubuntu repositories updated from 8.7?

### ISSUE THREAD

**Issue by JesselSteele** [Sigil-Ebook/Sigil#163]
Are Ubuntu repos still part of the roadmap so true open-source writers can test it for production? Y/N I just want to know.

**Comment by kevinhendricks** [comment]
Huh?
Isn't this something you should ask the Ubuntu packagers?  This really is not a Sigil issue.  We have already worked to include patches form other Linux distributions and they do include Sigil-0.9.0.

**Comment by toddcarnes** [comment]
"True open-source" writers... A little arrogant aren't you?

**Comment by kevinhendricks** [comment]
This issue is closed.  This is not the place for this debate.

**Comment by mapreri** [comment]
stable releases don't usually update packages, and quite certainly not the kind of programs like sigil.
Currently ubuntu doesn't even have sigil 0.9.0 in the development version due to a problem with a dep of a dep of dep (that I'll clearly sort out before the release).
I'm thinking about setting a PPA, it might be worth it (currently I've ppa:mapreri/sigil, but I don't really keep it up-to-date atm, so....).

Anyway, sigil 0.9.0 won't build/run on plain trusty (14.04) due to a too old cmake (and iirc also something else).

**Comment by eli-schwartz** [comment]
> Are Ubuntu repos still part of the roadmap so true open-source writers can test it for production? Y/N I just want to know.

Distros are in charge of maintaining their own repos.
I believe in the near future Sigil will be available as a standalone linux binary, for the benefit of people on ~~laggy~~ stable distros.
