### ISSUE TITLE
"OEBPS" directory name

### ISSUE THREAD

**Issue by bvds** [Sigil-Ebook/Sigil#171]
I know the standard does not specify the name of the OEBPS directory, but I have an application that demands that the name be "OPS".  It would be nice to either preserve the name of this directory or have the name be settable in preferences.  (Also with other directory names.)

**Comment by kevinhendricks** [comment]
Sorry,  Sigil has operated this way since the very beginning.  The name chosen by Sigil is valid.  Please file the bug report with the application that only accepts OPS.  You could use the Calibre editor since it does not move things.  Or create a Sigil output plugin that can be made to generate an epub in any format you so desire.
Closing.
