### ISSUE TITLE
change name of xhtml-file but link remain same

### ISSUE THREAD

**Issue by Igelball** [Sigil-Ebook/Sigil#174]
if Change name of xhtml-file link in files do not change with it. At documents with many links is not possible change all links separate.

**Comment by dougmassay** [comment]
You'll need to provide some specific examples where this doesn't work as expected. Because whenever I rename an xhtml file in the Book Browser (using the integrated 'Rename' feature), all of the links (throughout the book) that use that file name in their href attribute are automatically updated as well.

**Comment by kevinhendricks** [comment]
Works for me.  So closing this issue.  Please reopen with a repeatable test case or at least some instructions on how to recreate the issue.
