### ISSUE TITLE
allow custom/no modification date

### ISSUE THREAD

**Issue by ziep** [Sigil-Ebook/Sigil#180]
Currently, if you set a custom modification date (in the metadata editor window or in the source code of content.opf, it doesn't matter) or delete the item, Sigil doesn't respect that but overwrites it on file save. There is no option to override or turn this off.
This is a privacy issue and Sigil's current behaviour is patronizing.
If Sigil will not default to respecting a custom value or deletion of the modification date item I need at least an option to deactivate this automatic, similar to the checkboxes for "Mend XHTML Source Code" in the preferences.

**Comment by kevinhendricks** [comment]
This will get even worse with epub3.  The spec *requires* a very specific modification date in a very specific format including the complete time down to the second in "Z" gmt time zone.  The idea is that the book unique identifier plus the exact modification date/time provides a rendition a completely unique identifier.  So Sigil will not be adding that checkbox.  It is the spec.    The reason is it prevents the proliferation of multiple subtly different copies of virtually the same epub being out there with no way to tell which is the most recent.  That is its purpose.  If you change something in the epub using Sigil, the modification date is recorded, **just** like what your OS does with the last modified date on *any* file on your computer that you play with.  It truly is no different.  

Your alternatives are:

1. modify a Sigil output plugin to do what you want and use it.
2. simply unzip the epub and change the modification date manually, this could easily be scripted on any platform
3. use a different epub editing program

**Comment by kevinhendricks** [comment]
FYI: here is the spec

"This specification makes a distinction between the Unique Identifier for an EPUB Publication and the identifier that uniquely identifies a specific version of it (i.e., to be able to differentiate different versions of the same EPUB Publication). Whenever a Rendition is modified, it *must* include a new last modified date."

See http://www.idpf.org/epub/301/spec/epub-publications.html#sec-opf-dcidentifier
