### ISSUE TITLE
CSS cleanup doesn't work if CSS file has "special" chars

### ISSUE THREAD

**Issue by mbest** [Sigil-Ebook/Sigil#209]
In my case, the file had spaces in it. Sigil would show that all CSS classes were unused. Once I changed the CSS file name to something simple, it worked fine.

See also http://www.mobileread.com/forums/showthread.php?t=262892

**Comment by kevinhendricks** [comment]
Please specify what the exact link tag used in the xhtml to pull in that css file.   Also the exact manifest entry for that css file, so that I can see if the url was properly escaped with the required %20 replacing the space.

KevinH

**Comment by mbest** [comment]
From content.opf

    <item href="Styles/Manah%20Siksa%20CS6_EPUB.css" id="Manah-Siksa-CS6_EPUB.css" media-type="text/css"/>

From one of the xhtml files:

    <link href="../Styles/Manah%20Siksa%20CS6_EPUB.css" rel="stylesheet" type="text/css"/>

**Comment by kevinhendricks** [comment]
Since the  link tag has the proper uri encoding but still doesn't work, then it is a Sigil bug and I will look into it.

That said ... using spaces inside a file name used inside an epub is not recommended and violates some rules of certain epub vendors (such as kobo for example).  So if you do decide to keep the space in the filename and it is properly encoded, be aware that specific epub publishers may still reject it as it violates their specific policies.

**Comment by kevinhendricks** [comment]
Again, after reading the MR post, this only happens when you import the html file (and the css file is pulled in automatically, correct.  If instead you use add existing to add the css file and manually link it to the html file, it works correctly.  But both versions result in properly encoded urls with %20 used in both the content.opf manifest and the xhtml link tag.  Is that correct?

**Comment by mbest** [comment]
I did not try to add the CSS file. It was already there.

I did try to unlink and link it to an xhtml file, but that didn't fix the problem. I did notice that when linking, the spaces weren't escaped in the xhtml.

**Comment by kevinhendricks** [comment]
Then that is a different bug from what you cited in MR.  When you linked it manually, the Sigil added link tag in head did NOT properly escape the space in the uri. Is that correct?  If so that appears to be a different bug.   

The bug you are trying to report is about importing an html file with an already linked in css file that has a space in the filename results in a properly escaped link tag uri inside Sigil and in the content.opf manifest, but for some reason deleting unused css deletes too much from that linked in css file. If you use the exact same procedure but with a css file without spaces in its name, everything works correctly.
Is that correct?

Since lots of changes have happened relating to CSS in Sigil.  Which exact version of Sigil are you using and on which platform?

**Comment by mbest** [comment]
> If you use the exact same procedure but with a css file without spaces in its name, everything works correctly. Is that correct?

Yes

> Which exact version of Sigil are you using and on which platform?

Version 0.9.5 on Windows 7 64.

**Comment by kevinhendricks** [comment]
Thanks for the bug report.  The url decode to convert from url back to relative path Also, fyi using spaces inside a file name used inside an epub is generally not recommended and violates some rules of some epub vendors (such as kobo for example). within the epub is  missing in the Book Report  which generates a list of classes used in the html and which css file it is taken from.  

Similarly a url encode is missing to convert an epub relative path of a stylesheet to the link tab being created.  Both should be fixed in the next release.

**Comment by mbest** [comment]
Probably related: I also noticed that when I would update the CSS file, the preview or Book View wouldn't see the updated styles. Now with the simple CSS name, it works.

**Comment by mbest** [comment]
Thanks for looking at this quickly.

**Comment by kevinhendricks** [comment]
Just pushed a fix for this to master so closing this as "fixed".  The bug fix will appear in our next release.  If after upgrading to the next release you still have issues with your particular testcase, please re-open this issue.

Thank you for your bug report!
