### ISSUE TITLE
"Delete unused stylesheet classes" deletes rules even if there are other undeleted selectors associated with them

### ISSUE THREAD

**Issue by wrCisco** [Sigil-Ebook/Sigil#211]
If I have a css like this:
```
div,
.one {
some-property: some-value;
}
```
and the class "one" isn't used in any xhtml file, the tool "Delete unused stylesheet classes" deletes the ".one" selector and the rule associated with it, leaving the "div," of the previous line associated with the subsequent rule, if any. I think the problem is connected with the newline that separates the two selectors. I can avoid to put newlines between selectors, but the behavior of this function seems to be quite dangerous at the moment.
I'm using Sigil 0.9.5 on Mac OSX 10.11.
Thanks!

**Comment by kevinhendricks** [comment]
I am not much of a css user.  is it legal for grouped selectors to be on more than 1 line.  The spec just mentions comma separated and all examples I could find used one line.

I will look into getting this fixed.

**Comment by wrCisco** [comment]
AFAIK, W3C validator and rendering engines have no problem with that. I think that one can put as many newlines and spaces as he wants in css, between all sort of elements (doesn't make necessarily a good css...).

**Comment by kevinhendricks** [comment]
Yes, Sigil's CSSInfo.cpp class explicitly assumes that no newline can exist between elements of a selector group and that every selector/group starts on its own line.

I can find no parser spec that clearly states if this is right or wrong.  Examples of selector groups spread over multiple lines are rare based of my google searches.

I did check the github tinycss tokenizer code and it does allow what you are doing.

I will try to fix this but it will probably take adding a good css parser written in C or C++ with a compatible license to Sigil to more properly handle all of the variations.

Until fixed, the correct workaround is to not use newlines inside selector groups.

**Comment by wrCisco** [comment]
Understood.
Thanks for your work!

**Comment by kevinhendricks** [comment]
After studying the code some more, I think I have fixed this issue with my latest commit to master.
My test stylesheet was:

p,
.IDoNotExist,
h1,
h2 {
}

And then ran Delete Unused Stylesheet Classes, and only the .IDoNotExist line was removed, in other words the code now recognizes group selectors even when separated by new lines.
So, when you get a free moment, please give my fix a try and let me know if I can close this issue.

A better long run solution is to add a true CSS parser but so far I have examined  the W3C's SAC but it hasn't been touched for over 16 years,  libcss but it does too much and requires libWapcaplet and libParserUtils, and something called katana.  Of the 3, katana (https://github.com/hackers-painters/katana-parser) looks usable since it is MIT licensed and is similar to gumbo in spirit, written in C99 with no outside requirements - but it will take some time to develop a working interface as there is virtually no docs or examples.

So hopefully the last commit to master will do the trick.

Thanks for your bug report.

**Comment by wrCisco** [comment]
Hi Kevin, your fix works well!
I'm afraid though there are other problems with that tool: if I have
.exist, .not-exist {
}
.exist {
}
The tool will propose to delete the second .exist, which is definitely not a good thing.
Plus, the .not-exist won't be on the list of proposed deletions (seems that if there is at least one class that exists all group of selectors is left untouched... Ok, this is not dangerous, only useless).

**Comment by kevinhendricks** [comment]
If a class rule is repeated, which rule is valid?  Is it the first or the second or both? If the first then, isn't the tool correct in removing the second .exist rule since it can never be reached.  If the second or both, then yes it is another bug.   I will have to check the spec on that.

Something must be funny though  if the .notexist is not on the delete list in your example.  My exact test above is the very same case, and only the .IDoNotExist selector was on the delete list and it was removed from that selector.

I will try to play around with your test case to see if I can recreate what you are seeing?

**Comment by kevinhendricks** [comment]
spec says two selectors with equal specificity, the latter one is used.  So definitely a bug.

Have to look at how that case is handled in the parsing of the css and how the mapping of css classes used in xhtml are made into specific stylesheets/rules by the DeleteUnused code to figure out what is going wrong here.

**Comment by wrCisco** [comment]
Both are valid: only when the properties in different rules are the same the last overwrite the previouses.
If I have:
.example { color: red; font-size: 1.5em; }
.example { color: blue; text-decoration: underline; }

the computed style will be:
color: blue;
font-size: 1.5em;
text-decoration: underline;

I think that the most important difference between our test cases is that in yours all other selectors are tags, not classes. I barely know C language, so it's not easy for me to say more.

**Comment by kevinhendricks** [comment]
Yes, after studying the code more, the algo checks if an html class attribute exists in the css stylesheet and records the first place it matches as it only cares if used or not.  It needs to instead record ALL  selectors it matches.  This will take some redesign.  It should be fixable.

**Comment by kevinhendricks** [comment]
Okay, I have modified the code to detect that multiple selectors can be used by a single class reference in an html file.  Once I commit these changes, Sigil will no longer ask to remove the second .exist selector in your example.  The second issue of not removing the .not-exist from the group selector still has to be dealt with but as you said, that case is not a safety/correctness issue.

If the second issue turns out to be doable, I will try to add it.  If not, it may have to wait until a real css parser is incorporated sometime down the road.

**Comment by kevinhendricks** [comment]
And added in a fix for second issue as well and committed both fixes to master..  
So when you get a free moment please pull from master and let me know if this finally handles all of your problem cases.  If so, I will then close the issue as fixed in master.

**Comment by wrCisco** [comment]
Works great!
(There would be other issues with CSS3 selectors, like :not(.example-class) that is proposed for deletion both when the class is used and when is unused (and in both cases it would be probably wrong), but maybe they are sufficiently edge cases to wait until the css parser will be eventually added).

**Comment by kevinhendricks** [comment]
Great.  I am okay with edge cases being proposed.  It is the user's job to audit the list presented in the Dialog and select which ones he/she actually wants to have deleted.  That is the only way to handle some of the cases.

Thanks for testing.
