### ISSUE TITLE
Suggestion: Recover previously opened tabs, and draft recovery

### ISSUE THREAD

**Issue by Jane84** [Sigil-Ebook/Sigil#215]
Would it be possible to make a function so when you open, or re-open a previously opened ebook that it would recover and open the tabs that were open when the ebook last shut down?

It could be quite helpful when you are editing several ebooks and sometimes need to switch between books, or when you recover from a crash. 

I would really appreciate it if it were possible to find a way to recover an unsaved ebook - very much like you have in MS Word and other simiar applications.

**Comment by kevinhendricks** [comment]
You can run multiple copies of Sigil side by side and cut and paste between both open books.  Simply run muliple copies of Sigil simultaneously on Linux or Windows.  On Mac OS X, you can just File->Open  a second Window.

As for crash recovery, it is simply much better to not cash.  

Any open tab that has changes has not been saved to disk as it only exists in memory and therefore will be lost if Sigil crashes no matter what. You are much better off doing periodic save-as under a new name each time (_rev1.epub, _rev2.epub) when you feel you have reached a suitable point.   

But most importantly, if you are experiencing *any* crashes, at all with the latest version of Sigil, it would be infinitely better to report those crashes so they can be tracked down and fixed for everyone.  As of Sigil-0.9.5 there are no known crashes at all reported now.  It is very stable now,  many many crashing bugs have now been fixed since Sigil-0.7 and Sigil-0.8.

**Comment by kevinhendricks** [comment]
I have added a feature to allow the user to set his/her own temporary folder locations.  If a crash happens, the user should be able to open this folder and search for any updated files since this is where Sigil unpacks the epub while editing it.  Hopefully this will allow the user to get what can actually be saved back.

I still would prefer actual bug reports for any crashes so that I can track them down and get them fixed for everyone.  This new feature was added to master.

Closing this issue.

**Comment by Jane84** [comment]
It's not so much if or when sigil crash.I have yet to experience Sigil crash or shut down on it's own, but have been more when the computer crashes out of spite, or force an update and then restarts when you are not near it, and have forgotten to quicksave the most recent editings, so I then had to track down what tabs I had open and then relocate the sectons that I worked on. 

As for multiple copies, then yes I do know that. I currently have 5 books open at once, while comparing sections or editing them. I love Sigil, and it is one of my most used applications (next after MS Word)

"As for crash recovery, it is simply much better to not cash." I agree with you on that, but what happends and what I want to happen, is sometimes two different things. 

Thank you for the added feature.
