### ISSUE TITLE
a statement on developing for Linux

### ISSUE THREAD

**Issue by drydenp** [Sigil-Ebook/Sigil#230]
I remember a statement by a Sigil developer here (I think) that there were no Linux provided packages because he said he had found Linux people hard to work with. Am I correct that this was here?

I cannot find this thing now. I find it interesting, because it would be another developer (I guess) who would consider Linux people not-so-nice-to-work-with, but I cannot find a reference to it here now.

Am I mistaken?

Regards.

**Comment by drydenp** [comment]
Never mind, I found it.

**Comment by kevinhendricks** [comment]
For the record, Sigil has a new development team  as the old maintainer has retired.  The current devopment team has worked closely to get linux distribution changes that are needed into the tree.  Arch Linux for example keeps an up-to-date Sigil package and Sigil will build out of the box on Linux Mint and many other linux versions.  See Building on Linux in the docs.  The only reason we do not include packages is because we are a small volunteer development team of just two people, plus the official distributin maintainers have done a wonderful job creating official packages.
