### ISSUE TITLE
Request: Rename the end tag too when rename the open tag.

### ISSUE THREAD

**Issue by hantsaniala** [Sigil-Ebook/Sigil#293]
This is not by the find/replace using regex but manually rename one open tag and the end tag will be renamed too.

**Comment by kevinhendricks** [comment]
I am confused.  If a tag set (an open and close tag pair) already exists, then  using a stored search and replace would always be best/fastest.  Under what circumstances would you want to repetitively replace an open/close pair with a different open/close tag as opposed search/replace or wrapping it in a new tag.

**Comment by bershan2** [comment]
Probably @hantsaniala means something like this:
imagine you have
`<p><i>Hello World!</i></p>`
and want to change italics to bold. Then you really need to substitute `i` with `b`, which would work seamlessly because all `i`'s are in the tags. But that would not work if sentence contained an `i`!

@hantsaniala suggests to somehow pair the open/close tags and if one is modified, automatically substitute the other. I would assume if a tag is removed completely, its pair is removed too.

Seems like a peculiar case, but I do not edit books that much to have a necessary experience; on the other hand, that would help prevent mismatching tags.

**Comment by kevinhendricks** [comment]
If you had to do that repeatedly, a stored search and replace using regular expressions can easily be done to make that change without having to worry about any "i" anyplace else un the text.  Regular expressions and stored searches make Sigil quite powerful in this regard.  There is also a Tag Mechanic plugin that can be used to ro this repeatedly without knowledge of regular expressions.

If it is just a one-off, then finding the appropriate end tag is easy and hanging or mismatched tags are automatically detected by Preview mode error messages.  

There seems little point to bloat the user interface with this given there are already multiple ways to handle it in a repetitive case.

**Comment by hantsaniala** [comment]
Yes, this is the best approach but sometimes, there is a need to work manualy on the tag and it is very useful if there is a fonctionality like that if the OP doesn't know how to use regex. For me, I'm familiarized with the Oxygen XML behaviour and with Oxygen I can do that and like select all bloc like **div** or **p** by only double-clic the open or ending tag too. So it's just a request 😄  But thanks everyone, it's a great tool 😄 👍
