### ISSUE TITLE
Paste in Book View replaces space with nbsp before inline elements

### ISSUE THREAD

**Issue by larrykollar** [Sigil-Ebook/Sigil#299]
MacOSX 10.11.6, Sigil 0.9.8 (I've seen this in earlier versions as well).

Steps to reproduce:

1.  Add an HTML text file to an empty book.
2.  Switch to Book View. Apply bold, italic, and span elements to strings of text. Switch to Code View to verify that there are plain spaces in front of the highlighted text, then back to Book View.
3.  Copy a run of text containing at least one inline (bold/italic/span) element.
4.  Paste the text elsewhere in the file (say, at the end of a paragraph). When Sigil asks if you want to paste as plain text, click **No**.
5.  Switch to Code View. Note that all spaces before inline elements have been changed to &amp;nbsp;.

**Comment by kevinhendricks** [comment]
Again, exact what ty=ags are created when editing in BookView are not under the control of Sigil and are mainly internal decision made inide Qt's Webkit.  

We strongly suggest that is you actually care about how the code looks (have a preference for what you want to see happen) then you should be using CodeView not BookView.

If you want to see the impact of your CodeView edits, you should enable Preview so you can edit in CodeView and see the changes in Preview and never have to use BookView.

As it stands, because of the number of issues with BookView and how Qt's Webkit handles "editing mode" in the tree without giving much leeway, we will be removing BookView completely in a future version of Sigil (not determined yet which version), and strongly suggest using CodeView with Preview enabled if you care about more than code correctness. (ie. have a preference for exactly which tags you want to use).
