### ISSUE TITLE
PyGumbo parse bug

### ISSUE THREAD

**Issue by LuoZijun** [Sigil-Ebook/Sigil#308]
Test Code:

https://gist.github.com/LuoZijun/69a55c292d5d4f884c612a5345e54de4

Error Message:

```
Assertion failed: (node_html_tag_is(head, GUMBO_TAG_HEAD)), function handle_in_head, file /Users/user/Project/Sigil-master/internal/gumbo/parser.c, line 2197.
fish: 'python3 test.py' terminated by signal SIGABRT (Abort)
```

if i use [html5ever](https://github.com/servo/html5ever) or [gumbo-parser](https://github.com/google/gumbo-parser), then everything is ok.

**Comment by kevinhendricks** [comment]
This bug is created because our modified sigli-gumbo properly handles xml closing tags even on script tags (since we are parsing xhtml for ebooks) making this line not-well-formed:

```
<script type="text/javascript" src="https://passport.baidu.com/passApi/js/uni_login_wrapper.js?cdnversion=201707212011"/></script>
```

As it has a self-closing style tag followed by a spurious (extra)  closing script tag.

I will look to see how we can more properly handle spurious closing tags after self-closing tags when nothing is nested.

**Comment by kevinhendricks** [comment]
Fixed with this commit:

https://github.com/Sigil-Ebook/sigil-gumbo/commit/b96cbf23a53a7fdefced3909b8deceab24a1dc82
After lots more testing this change will eventually migrate to the Sigil ebook tree.

Closing as fixed.

**Comment by LuoZijun** [comment]
@kevinhendricks thanks.

👍
