### ISSUE TITLE
Code View - Slow/Poor performance - 1+ sec. delay with focus change

### ISSUE THREAD

**Issue by DFlame69** [Sigil-Ebook/Sigil#317]
I have an Intel i7 5930k 6 core with updated Windows 10 Pro x64. OS is on SSD. Using x64 Sigil, now version 0.9.8

I'm noticing long 1+ sec. delayed response in code view when:
the content is larger than 10k Lines
during focus changes into and out of other windows sections and other programs

There doesn't seem to be an issue with book view though.

I've notice this issue since around v0.9.4 I think.

I mostly use code view since most things will produce some really ugly html code.

**Comment by kevinhendricks** [comment]
This is due to syntax colouring only used in CodeView.  Codeview is a line based editor.  Have you enabled Mend on Open in Sigil Preferences?

**Comment by DFlame69** [comment]
Yes, 'Mend on Open' is enabled, though I doubt that has anything to do with the issue.

Whatever kind of processing done on the text that takes that long, every time there's a focus change really needs to be optimized. This is text, not 3D raycast rendering.

Even if such lengthy processing is needed, shouldn't it only be done on only the visible text or only when the text is actually changed?

**Comment by dougmassay** [comment]
A 10k+ line flow is not really typical usage. And the sluggishness of Sigil's interface has always been directly proportional to the length of the flows being edited.

**Comment by kevinhendricks** [comment]
And yes syntax highlighting for each line to colour tags different from text, different from line number areas etc is what slows this down.  This is done via a Qt syntax colouring routine that uses regular expressions on each line.   Mend on open tries to insert newlines to prevent long run on code blocks without line breaks into something actually usable and editable.

And yes 10,000 line file/chapters are not typical as they would make older epub readers barf, cause long loading times on ebook pages, etc.  

Have you considered simply using a find and replace to automatically insert Sigil split markers and properly splitting those 10,000 line long files into appropriate chapters?

Perhaps this is a Windows only issue?  I have even tested with user supplied  Bibles that only used one huge file and was able to edit it reasonably after mending it on open.

Do you have a test html you could point us at that we could use for testing and profiling with to see what is going on?

**Comment by DFlame69** [comment]
Well here's an extreme example of an epub I made:

[Manga wo Yomeru Ore ga Sekai Saikyou -Yometachi to Sugosu Ki mama na Seikatsu-](https://drive.google.com/open?id=0B7TpTnm9oWeocVhHRk5XZ3RVRUE)

Since I mostly make them for personal use, they work fine on the readers that I use. Splitting the html is undesirable because the tts I use can't continue across a split.

**Comment by kevinhendricks** [comment]
What epub reader tts does not handle multiple chapter ebooks?  Those are the single most common way ebooks are made?  Keeping multiple chapters in a huge single file really is not a good design approach.

I will grab your testcase when I am out of work and see how Sigil responds on my iMac and try to profile the code with it.

**Comment by fcntl** [comment]
> What epub reader tts does not handle multiple chapter ebooks? 

I would also love to know this, @DFlame69 .

**Comment by DFlame69** [comment]
If you must know, I wanted a **free** reader that worked with a sapi TTS in windows. What I ended up with is EPUBReader Firefox plugin with Multi-language TTS plugin.

The TTS plugin is pretty crap, but it met the requirement of free and uses sapi for TTS.

**Comment by kevinhendricks** [comment]
Again,  as you load each chapter, tts should work just as it does in any file.  So why can't you split it into multi-file/chapter epub, EpubReader for Firefox should handle those just fine otherwise it is not an epub reader.

**Comment by kevinhendricks** [comment]
Okay, I grabbed it.  Yes. it is a very extreme example.  Over 24000 lines and the epub itself is 48.4 meg.  Furthermore there are multiple "books" all in the same file not just multiple "chapters".

In my i7 iMac, I do see a delay when I click outside of the Tabbed window to force focus to move someplace else but it is on the order of a quarter of a second in real time not 1+ seconds.  This is even with Preview open.  So editing this book is easily done in CodeView on my iMac.

Furthermore a simple Search and Replace as follows:

Search: <h1 id="book_
Replace: <hr class="sigil_split_marker" /><h1 id="book_
Mode: Normal

Followed by a Sigil:
Edit->Split at Markers 

happily splits the single huge html file into multiple files (ie. "books" each holding multiple "chapters").  A similar technique within each of those could also split out individual chapters.

Once split, changing focus is basically instantaneous.

I will try to use this sample epub to profile the code to see if there is any low-hanging speed-ups but the real problem is that you have designed the book poorly and should be employing multiple html file (one for each "chapter" - or at least one for each "book") so that epub readers have some chance of working with your epub.  Trying to optimize Sigil for your one special-use case is simply not feasible.

**Comment by kevinhendricks** [comment]
Profiling reveals no easy way to speed things up as most of the code at issue is inside Qt.  So closing this.
