### ISSUE TITLE
Feature request: support for version control? Non-interactive mode? Import from/export to uncompressed directories?

### ISSUE THREAD

**Issue by dpurge** [Sigil-Ebook/Sigil#326]
I just started to use Sigil, apologies if that is not a new idea.

I am trying to keep the books under version control. As a workaround I've configured LFS to track epub files, and unzip content and style file before git add/commit/push. But that is inconvenient.

I'd like to be able to use Sigil on books that are under version control, stored as merge'able text files, and build them into epubs from command line, preferably not having to implement that with 7zip ;-).

Something like this could be an answer:

1) be able to open and save to an uncompressed directory, preferably saving only the files that have been changed manually (ie. skip generated files)

2) use Sigil as a command line tool to "build" uncompressed directory to epub. (combine "import/export" in non-interactive mode)

Having that one could configure one's IDE (eg. VSCode) to use Sigil as a build tool and external editor.

Do you think it would make sense to implement this? Can this be achieved in a plugin?

**Comment by kevinhendricks** [comment]
This is something that could be accomplished quite easily using  Sigil input, output, and edit plugins.   Sigil plugins are written in Python3.  See Mobileread for a list of available plugins.   There are many existing  input and output plugins you can use as examples in creating something of your own.

Contact Sigil plugin developers on www.mobileread.com in the Sigil user forums.  Perhaps someone there could be convinced to help or you could pay someone to develop something for you if you are not a python coder.

Closing this a this feature will not be added to Sigil itself as interfacing to someone's preferred versioning system is best left to plugins.

**Comment by kevinhendricks** [comment]
FYI: There now exist Sigil plugins to read from and copy to Folders. 
See:
https://www.mobileread.com/forums/showpost.php?p=3632655&postcount=23

**Comment by dpurge** [comment]
I've already written my own plugin as well to export and import texts, stylesheet and media to folders. It turned out to be pretty simple and now that I do have a customization I can add other project-specific features (support for templates and exporting data from the book to other applications).

But thank you for your plugin - I think it fills a gap. Not everybody can write his own quickly, its good to have something.

This could be part of the application standard ecosystem. The proposal was not about "someone's preferred versioning system" but being "version-system friendly" in general. It does not matter which one you are using, as long as you support a project format that uses human readable text files that can be merged. 

Custom plugin means that I will have to maintain its compatibility as new versions of Sigil are released; if there was a standard format with some guarantee of compatibility with futer versions of Sigil, I would prefer to use that.

**Comment by kevinhendricks** [comment]
Glad to hear it!

BTW, you can use the Add Existing menu item in Sigil's BookBrowser to add multiple Styles, or multiple xhtml files, or multiple images, etc, at one time without needing a plugin.

The Sigil plugin framework is versioned and only new features and bug fixes have been added since its first implementation.  The only feature to be deprecated is Python 2.7 since it is end of life by its maintainer and Python 3.X is now embedded and required by Sigil.

So as long as you stick to the official Sigil Plugin Framework as documented, your plugins will remain fully supported by future versions of Sigil.

If you want to share you plugins with others, consider posting to:

https://www.mobileread.com/forums/forumdisplay.php?f=268

And we can add them to our Sigil Plugin Index hosted here:

https://www.mobileread.com/forums/showthread.php?t=247431
