### ISSUE TITLE
The "quick launch buttons" launch the plugins repeatedly.

### ISSUE THREAD

**Issue by sophronho** [Sigil-Ebook/Sigil#330]
The "quick launch buttons" on the toolbar cause the plugins to launch several times. The previous version 0.9.8 has no such issue.

**Comment by kevinhendricks** [comment]
Yes, this bug was already reported and even fixed in master.  

As a workaround, after adding or removing plugins or assigning plugins to buttons, you need to restart Sigil.  After a restart, launching a plugin via a button should work properly (only run once).

Thanks for your bug report.  Closing as this bug is already fixed in master.
