### ISSUE TITLE
missing files in Mac binary package

### ISSUE THREAD

**Issue by fredjzl** [Sigil-Ebook/Sigil#332]
hello Sigil team,

Some files are missing in Sigil 0.9.9 Mac binary package.

These missing files are part of lxml Python library, and are located at the following path : 

Contents > Frameworks > Python.framework > Versions > 3.5 > lib > python3.5 > site-packages > lxml > isoschematron > resources

This directory does not contain any file, whereas it should look like this :

![image001](https://user-images.githubusercontent.com/35179769/34744415-086c99ec-f585-11e7-8746-6118e7d42ec1.png)

This issue does not happen with 0.9.9 windows binaries.

**Comment by kevinhendricks** [comment]
I will investigate.  The difference could be that Windows uses a newer lxml package than what is used on the Mac.

When were these files added to lxml?

**Comment by dougmassay** [comment]
I'm using lxml 3.8.0 for the Windows packages. I've never really looked those files, to tell the truth.

**Comment by kevinhendricks** [comment]
I am using lxml 3.7.3.  That said, we should probably standardize on specific versions to minimize any craziness due to bug reports.

The difference in this case is not due to lxml version but instead due to differences in the pythonpkg code used:

Your version comments out the else clause allowing these files to get copied:
```
def ignore_in_dirs(base, items, ignored_dirs=None):
    ans = []
    if ignored_dirs is None:
        ignored_dirs = {'.svn', '.bzr', '.git', 'test', 'tests', 'testing', '__pycache__'}
    for name in items:
        path = os.path.join(base, name)
        if os.path.isdir(path):
            if name in ignored_dirs: # or not os.path.exists(os.path.join(path, '__init__.py')):
                ans.append(name)
        #else:
        #    if name.rpartition('.')[-1] not in ('py', 'pyd', 'dll'):
        #        ans.append(name)
    return ans
```

whereas my version still had those lines as active.  I can fix that so that we will be in sync for the next release.

I do think we should standardize so that we use the exact same Python 3.X.Y version as well as exact same versions of each of the site-packages as well to prevent future issues.  What do you think?

**Comment by kevinhendricks** [comment]
Committed fix for this to master.   

As a workaround until the next release you can manually install those missing lxml xsl sheets inside Sigil.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.5/site-packages/lxml/ into their proper directories.

Closing as this is now fixed in master.  

Thank you or your bug report!

**Comment by dougmassay** [comment]
Standardizing is fine by me. I've been locked on Python 3.5.2 for a while now. I'll inventory my site packages and email you my versions so we can work out standardized versions of our extra modules for Windows and Mac.

**Comment by kevinhendricks** [comment]
sounds good to me.

**Comment by fredjzl** [comment]
Thank you for your quick support!
