### ISSUE TITLE
UI Design 

### ISSUE THREAD

**Issue by strowk** [Sigil-Ebook/Sigil#339]
User Interface should be changed. 
See diffrence of Sigil with nice looking desktop UI:
![image](https://user-images.githubusercontent.com/25692644/37124196-4d157f94-2278-11e8-8178-a350b60fe154.png)

Work should be done on
1) Text fonts and sizes - ( size of text in main redactor in Windows 10 is AWFUL, I wanna cry )
2) Icons should be completely changed - has similar simple style, try to change all images including Windows default things like tree icond, etc
3) Remove many unnecessary buttons, work more on hotkeys support
4) Change margins - they should be with different size 
5) Maybe work on windows 10 DPI  scaling support ( http://www.thewindowsclub.com/dpi-scaling-improvements-windows-10 )

**Comment by dougmassay** [comment]
"Please change everything" is not a valid use of the Github issue system. We have to support multiple versions of Windows as well as multiple versions of Linux and Mac. Because of that, function is always going take precedence over cosmetics. Those who just can't stand how Sigil looks, have options to tailor it via Qt stylesheets to better suit their sensibilities.

**Comment by kevinhendricks** [comment]
Furthermore, text sizes and fonts in the editor are user controllable as are icon sizes via preferences.
Sizing of almost any widget is also user controllable via Qt Stylesheets.
