### ISSUE TITLE
Simplification de la chaine de production de livre

### ISSUE THREAD

**Issue by EmmaChambon** [Sigil-Ebook/Sigil#375]
Bonjour,

Je fais partie de ChezNous Editions, éditeur de livres actifs https://cheznous.coop.
Nous développons sous une forme unique des ouvrages qui donnent lieu à la création de communautés autour du sujet traité.
Nous sommes en train d'éditer un livre sur la Santé et nous avons utilisé et adopté Sigil pour créer les versions numériques française et anglaise.
Nous en sommes maintenant à la version papier et devons pour ce faire réaliser un PDF imprimeur.
Je suis passée par Calibre pour extraire le contenu sous forme de fichier TXT.
Et je l'ai importé dans Scribus.
Malheureusement, je dois redécouper le texte (345 pages) en "groupe de texte" (préface, chapitres, etc..) à l'intérieur de Scribus pour "caler" le texte correctement (haut de page impaire pour un début de chapitre).

Ma question est la suivante, pour disposer d'un modèle intégré, est-il possible d'avoir une fonctionnalité dans Sigil qui permette la génération de fichiers TXT correspondant à la nomenclature du livre (notion de pages dans Sigil) ? 
De façon à importer directement dans Scribus les bons "bouts" de texte ?

Vous remerciant d'avance de l'intérêt que vous porterez à ce message,
Emma Chambon

**Comment by dougmassay** [comment]
Hopefully Google translate will serve you as well as it served me for translation purposes.

If I understand what you're asking, then I'm afraid the answer is probably "no." Sigil, itself, will not be providing any text export functionality. It is quite possible for someone to create a Sigil plugin that might be able to accommodate your needs, however.  That's why we created the plugin framework in the first place: so people could extend the functionality of Sigil themselves.

**Comment by dougmassay** [comment]
Closing.
