### ISSUE TITLE
[Sigil 0.9.10 on Qt 5.12] Code View automatically scrolls down on window focus

### ISSUE THREAD

**Issue by UniverseIsProprietary2** [Sigil-Ebook/Sigil#389]
When Code View gets a focus, it automatically scrolls down to another location, and the more is the text, the more it scrolls down, stopping somewhere at the new line. This is very inconvenient, as I have to search for that location where I was editing code/text before switching the windows.

This bug only occurs starting with Qt 5.12, with version 5.11 it does not. As a temporal solution, I've downgraded Qt Framework to version 5.11 from 5.12.

To demonstrate what I mean:
![anim](https://user-images.githubusercontent.com/46316967/50588669-04742e80-0e7b-11e9-939c-3726a3fdb404.gif)

**Comment by UniverseIsProprietary2** [comment]
I'm still investigating the cause of this bug, but what I've found so far is that commenting this line produces no more automatic scrolling on window focus while in CodeView: 
`1857: m_Highlighter->rehighlight();` in src/ViewEditors/CodeViewEditor.cpp

Need to look further at XHTMLHighlighter::FormatBody function in src/Misc/XHTMLHighlighter.cpp. Not sure yet if this is a bug in Qt 5.12 or not.

**Comment by dougmassay** [comment]
It's not immediately apparent to me which platform you're on (though I'm assuming Linux since you don't mention building Sigil yourself and little else would have Qt 5.12). I'm not near my Arch system (Qt 5.12.0) to test, but I haven't noticed the issue you're referring to in my casual usage (that's not to say it isn't happening--just that I'm not all that observant sometimes).

Keep in mind that there was another cursor-jumping issue in Sigil 0.9.10 that has already been fixed in the current master branch.

**Comment by UniverseIsProprietary2** [comment]
> It's not immediately apparent to me which platform you're on (though I'm assuming Linux since you don't mention building Sigil yourself and little else would have Qt 5.12). I'm not near my Arch system (Qt 5.12.0) to test, but I haven't noticed the issue you're referring to in my casual usage (that's not to say it isn't happening--just that I'm not all that observant sometimes).
> 
> Keep in mind that there was another cursor-jumping issue in Sigil 0.9.10 that has already been fixed in the current master branch.

Sorry. Yes, I'm on Arch Linux. I build latest Sigil version from current master branch.

**Comment by dougmassay** [comment]
OK Thanks. I'll check when I get near my development machine.

**Comment by UniverseIsProprietary2** [comment]
>You've indicated that the issue doesn't manifest with Qt 5.11, so it almost has to be a change of some kind in Qt, no?

Yes. However, I I have yet to find a code in Qt 5.12 code base which causes this weird behavior.

One thing I would like to ask: why there is RehighlightDocument() in focusInEvent ? https://github.com/Sigil-Ebook/Sigil/blob/master/src/ViewEditors/CodeViewEditor.cpp#L1810

**Comment by kevinhendricks** [comment]
HTML code can be changed in many ways outside of the editor window itself so when it gets focus it must be highlighted properly.

As nothing has changed here on Sigil's end, from Qt 5.4, 5.6, 5.8, 5.9, 5.11 it all functions properly.  Qt is therefore the only element that has changed, which introduces the bug.  If you want to help look at related Qt commits that impact syntax highlighting introduced only to Qt 5.12.    As Qt 5.12.1 is supposed to be in beta now, you may want to try with it before spending any more time.  Qt 5.X.0 releases are notorious for regressions and new bugs.

**Comment by UniverseIsProprietary2** [comment]
>HTML code can be changed in many ways outside of the editor window itself so when it gets focus it must be highlighted properly.

Isn't highlightBlock is called on each repaint event anyway? The document in editor isn't automatically reloaded, so it will not display changes done outside of editor.

> As nothing has changed here on Sigil's end, from Qt 5.4, 5.6, 5.8, 5.9, 5.11 it all functions properly. Qt is therefore the only element that has changed, which introduces the bug. If you want to help look at related Qt commits that impact syntax highlighting introduced only to Qt 5.12. As Qt 5.12.1 is supposed to be in beta now, you may want to try with it before spending any more time. Qt 5.X.0 releases are notorious for regressions and new bugs.

Just tested with Qt 5.12.1, still same behavior.

![screenshot from 2019-01-09 17-28-57](https://user-images.githubusercontent.com/46316967/50911592-1c722200-1428-11e9-93dc-34672999749f.png)

**Comment by UniverseIsProprietary2** [comment]
I wonder if this is due to this change which was introduced in 5.11.3 and 5.12 branch: https://github.com/qt/qtbase/commit/dec7961709c90f6977d2447f7fa6c6625af41cb2 Need to test on 5.11.3.

**Comment by UniverseIsProprietary2** [comment]
> Looks quite plausible as a potential culprit as reformatblocks are invoked by contents changed signals in Qt and it used to preempt pending highlighting until after changes were done. This change appears to allow highlighting to happen when actually doing reformatting which the old setting of the rehighlghtpending flag to false in reformat at the beginning used to prevent.

Yes, I can confirm that the behavior in question occurs with this commit (tested by reverting to previous version). Hopefully, I could come up with some workaround soon.

**Comment by kevinhendricks** [comment]
Then you might want to comment at:
https://bugreports.qt.io/browse/QTBUG-71307

That their fix for this bug actually breaks longstanding code by now allowing rehighlights to be done during reformatting blocks that was impossible previously.

**Comment by kevinhendricks** [comment]
Or alternatively, we ship our own Qt version with that “fix” reverted.  We have had to do that a number of times before as Qt is often left broken or unfixed for long periods of time.

Our next release will be based on Qt 5.11.2 due to that is what appveyor on Windows uses.

Any other fix would require run time checks for Qt version inside Sigil as we want to keep it buildable with a large number of Qt releases for various MacOSX and Linux users who build from source.

**Comment by kevinhendricks** [comment]
FWIW, I added my comments to QTBUG-71307 (see link provided earlier) explaining how their "fix" broke important behaviour (i.e. that allowed the developer to control when the inital highlighting is done after a call to SetDocument) by removing the line of code that set the pending rehighlight flag to false in reformatBlocks.

As it stands now, even direct calls to rehighlight() will no longer reset their internal pending highlight flag which is obviously a bug since a complete document rehighlighting was just done but ...  

Based on past experience with Qt bugs, nothing will be done by Qt.  Therefore we will probably need to revert their broken "fix" in our own Qt builds at some point when we move to Qt 5.12.x for later official releases.  For the record, Sigils syntax highlighting is done is a synchronized manner by design because we need and use the contentsChanged/textChanged signals to not be generated by syntax highlighting itself.

**Comment by kevinhendricks** [comment]
Well it seems Qt agrees and has fixed their fix.  Wow, that is the fastest response I have ever had from Qt on any bug report!  Their patch is here: 

https://codereview.qt-project.org/#/c/249881/

It will not appear until Qt 5.12.2 and later (as 5.12.1 is too close to being released).   It will not be added to the Qt 5.11.x series.

So Qt 5.11.3, Qt 5.12.0, and Qt 5.12.1 will be broken releases of Qt for Sigil's purposes and therefore unsupported.  Going with Qt 5.11.2 for our next release would seem to make the most sense and staying there until Qt 5.12.2 is out there.

**Comment by dougmassay** [comment]
Wow! That has got to be some kind of record!

If someone points this out to Arch Linux, they may cherry-pick the fix. Most other distros probably won't be pushing out 5.12.x for a while yet anyway.

**Comment by kevinhendricks** [comment]
Does Eli still package Sigil for ArchLinux?  Do we know who packages Qt for Arch Linux?

**Comment by kevinhendricks** [comment]
I just wish Qt would stop pushing forward so hard and really focus on true LTS releases and on real bug fixes and spend less time on new releases meant mainly for mobile devices.   The Qt release plan and development cycle seems to be inherently too fast and therefore broken.

**Comment by dougmassay** [comment]
> I just wish Qt would stop pushing forward so hard and really focus on true LTS releases and on real bug fixes and spend less time on new releases meant mainly for mobile devices. The Qt release plan and development cycle seems to be inherently too fast and therefore broken.

No kidding. Will 5.12.x's LTS status mark the end of 5.9.x LTS? Or could there still be a 5.9.8?

**Comment by UniverseIsProprietary2** [comment]
> FWIW, I added my comments to QTBUG-71307 (see link provided earlier) explaining how their "fix" broke important behaviour (i.e. that allowed the developer to control when the inital highlighting is done after a call to SetDocument) by removing the line of code that set the pending rehighlight flag to false in reformatBlocks.
> 
> As it stands now, even direct calls to rehighlight() will no longer reset their internal pending highlight flag which is obviously a bug since a complete document rehighlighting was just done but ...
> 
> Based on past experience with Qt bugs, nothing will be done by Qt. Therefore we will probably need to revert their broken "fix" in our own Qt builds at some point when we move to Qt 5.12.x for later official releases. For the record, Sigils syntax highlighting is done is a synchronized manner by design because we need and use the contentsChanged/textChanged signals to not be generated by syntax highlighting itself.

Strange, this does not fixes the problem, neither reverting now this commit: https://github.com/qt/qtbase/commit/dec7961709c90f6977d2447f7fa6c6625af41cb2 (few days ago reverting this commit did not produce that scrolling effect in Sigil, or I've checked it badly, though I did a double check). I'm out of ideas currently what might be the cause of the problem. Do you have any suggestions? Can you verify that those changes in Qt are indeed cause of the problem?

**Comment by kevinhendricks** [comment]
Your probably mixing builds pieces or have multiple qt libs in your ld_library_path. 

I am currently working on compiling Qt 5.11.2 from source with needed fixes with macOS 10.14 SDK as that is the version of Qt that will be shipped with the next release of Sigil.

Once that is done, I will try building Qt 5.12.1 from source with their new fix added in to see what impact it has and confirm if it fixes things at least for macOS.  So it may be a week or 2 but I will test their new fix out.  Either way, their previous fix was broken.

**Comment by UniverseIsProprietary2** [comment]
Here's the commit which causes the problem: https://github.com/qt/qtbase/commit/5fe2ed48d60f383706274fa087f08a041c79dc73 . Another bug/feature in Qt which breaks compatibility? :)

**Comment by kevinhendricks** [comment]
Yes, block visibility changes would occur when covering a codeview window with a help or about dialog and then clicking back on a codeview window.  This itself must be causing issues with the broken syntax highlighting.

Not sure the best way forward as I still can not get a working Qt 5.12 build going on Mac osx under the latest toolchain.

**Comment by kevinhendricks** [comment]
This is so strange.  I built from source from qt-everywhere-src-5.12.0.tar.xz from the official qt archives.  This is the released source for the Qt 5.12.0 release and none of the problem changes in qsyntaxhighter.cpp are in this archive!  Then I looked at the qplaintextedit.cpp source and the problem change you pointed out as the culprit is in my official Qt 5.12.0 source archive, but I see none of the issues you have indicated!

This is for macOS not Linux.  Perhaps both changes are needed to create a problem?

This is a very strange bug indeed.

**Comment by kevinhendricks** [comment]
So to summarize, I downloaded qt-everywhere-src-5.11.2.tar.xz, qt-everwhere-src-5.11.3.tar.xz, and qt-everywhere-src-5.12.0.tar.xz and compared qsyntaxhighlighter.cpp files and qplaintextedit.cpp files:

5.11.2: neither problematic changes are present 
5.11.3: buggy qsyntaxhighter change present, but no changes in qplaintextedit.cpp
5.12.0: no qsyntaxhighter changes were present, but changesun qplaintextedit.cpp are here

Under macOS, Sigil works just fine with Qt 5.11.2 and Qt 5.12.0.  I have not checked with Qt 5.11.3 since it has the bugg qsyntaxhighterer change in it.

Has all of your testing been done on Linux?  Did you build Qt from source?  If so, can you please check the source archive and look at qsyntaxhighlighter.cpp and qplaintextedit.cpp and see exactly what versions of those files are being used since the buggy qsyntaxhighlighter change did not appear in the official released qt source archive.

**Comment by dougmassay** [comment]
I didn't build Qt5.12.0 from source, but I can verify that the Code View scrolling issue described in the first post manifests on Windows Sigil (built against 5.12.0) as well. This doesn't really surprise me. Qt bugs often affect Lin/Win the same while macOS doesn't get to share in the "fun." ;)

**Comment by kevinhendricks** [comment]
I wonder if the Windows source archive for 5.12.0 has both qsyntaxhighlighter.cpp and qplaintextedit.cpp issues?

**Comment by kevinhendricks** [comment]
I took a look at the changes to qplaintextedit.cpp that is said to becausing the issue.  I think their change makes the assumption that each QTextBlock only ever has a lineCount of 1 if visible and 0 otherwize.  If word wrap is enabled (as we use it) each block might represent more than one line depending on the layout so a visible lineCount may be greater than 1 (if visible).   This may be why longer lines cause more issues than shorter lines in CodeView during testing.  This messes up their visibility changed calculation and that causes erroneous documentSizeChanged signals being generated that have nothing to do with a user setting them to be visible or not, and instead is caused by the qplaintextedit widget getting hidden and revealed by another widget (the About Sigil Dialog) which should never impact layout or scroll bars.

So again, I think their "fix" *may* be quite broken especially for word wrap being enabled with long lines of text involved.

I have no idea how we get Qt to take another look at what they have done.  And all of this breakage is just so they can get smoother scrolling!!!!!  

Ideas welcome.  We may have to take the bug report testcase, and generate longer lines and enable word wrap to see if we can recreate the issue.

**Comment by dougmassay** [comment]
> I wonder if the Windows source archive for 5.12.0 has both qsyntaxhighlighter.cpp and qplaintextedit.cpp issues?

Do you mean the tarball vs the .zip of the source?

**Comment by kevinhendricks** [comment]
Yes, I downloaded the Windows zip file of 5.12.0 and diffed it against the linux/unix/mac tar.xz file and Windows has the qplaintextedit.cpp changes that are at issue but not the buggy qsyntaxhighlighter changes.  So that rules out the buggy qsynaxhighlighter changes as being part of the issue.   That leaves only the possibly broken qplaintextedit.cpo changes to look at.

**Comment by kevinhendricks** [comment]
Okay, based on my understanding of the code, I think I see a bug.  So I have created a patch to hopefully "fix" Qt 5.12.0 qbase/src/widgets/widgets/qplaintextedit.cpp so that the bug fix they made will now be correct in all cases.

I have not compiled this change, but it should be okay except for typos which should be obvious to fix.

I can not recreate the issue on my Mac, so would someone please try the following patch on Qt-5.12.0 source and rebuild just qtbase and let me know if this fixes the problem or not.

```
--- qplaintextedit.cpp	2018-12-03 06:15:26.000000000 -0500
+++ /Users/kbhend/Desktop/qplaintextedit.cpp	2019-01-17 12:44:02.000000000 -0500
@@ -312,11 +312,32 @@
         QTextBlock block = changeStartBlock;
         do {
             block.clearLayout();
+#if 1
+            // BUG:  block.lineCount() may be >= 1 when visible and NOT indicate a visibility change
+            // BUG:  and should not be reset to 1 if no visibility change occurred
+    
+            // LOGIC:  if block currently visible then block line count must be > 0 (not always 1!)
+            // LOGIC:  if block currently not visible then block line count must be = 0
+            // LOGIC:  otherwise a visibility change has happened
+            
+            if (block.isVisible()) {
+            	if (block.lineCount() == 0) {
+            	    blockVisibilityChanged = true;
+            	    block.setLineCount(1);
+                }
+            } else {
+                // block is currently not visible
+                if (block.lineCount() > 0) {
+            	    blockVisibilityChanged = true;
+            	    block.setLineCount(0);
+                }                
+#else
             const int lineCount = block.isVisible() ? 1 : 0;
             if (block.lineCount() != lineCount) {
                 blockVisibilityChanged = true;
                 block.setLineCount(lineCount);
             }
+#endif
             if (block == changeEndBlock)
                 break;
             block = block.next();
```

**Comment by kevinhendricks** [comment]
[qplainttextedit_fix.patch.zip](https://github.com/Sigil-Ebook/Sigil/files/2769923/qplainttextedit_fix.patch.zip)

**Comment by kevinhendricks** [comment]
[qplaintextedit_fix.patch.zip](https://github.com/Sigil-Ebook/Sigil/files/2770353/qplaintextedit_fix.patch.zip)

**Comment by kevinhendricks** [comment]
FWIW, I have rebuilt qtbase in Qt 5.12.0 with the qplaintextedit_fix.patch above applied on Mac OSX and rebuilt Sigil.

The patch appears to compile fine and have no negative effects but I can not tell if this fixes our issue since I can not recreate the original problem on macOS.  

Any testing on other platforms would be appreciated greatly.

**Comment by dougmassay** [comment]
I've got no quick way to get set up to compile all of Qt (especially on Windows). I might be able to get something going on Linux over the weekend (while we're getting buried with snow), but none of my hardware will make very quick work of it. I can eliminate a lot of the extra modules in a qt build, but I'm not familiar with the way to only build qtbase (unless you meant only RE-building qtbase after having already compiled everything else at least once).

**Comment by kevinhendricks** [comment]
Understood.  I meant the latter.  Hopefully @UniverseIsProprietary2  has access to a Qt build setup and can try this patch and report back if it helps or not.

**Comment by kevinhendricks** [comment]
Alternatively, there may be a way to build a single module source (ie, qtbase) with official binaries from the Qt installer.  Not sure if that is doable, but it may be.

**Comment by dougmassay** [comment]
Similar to how the annulen WebKit module is built using the official binaries and a git checkout of Qt's source? I've seen the individual module source downloads, but I've never seen clear instructions on how to use them individually. I know I can use configure to disable a lot of the extra modules,  but I doubt I can whittle it down to just qtbase with that method.

**Comment by dougmassay** [comment]
To make a long story short... the scrolling Code View issue was still present after patching qplaintextedit.cpp on Linux.

I managed to build the stock Qt5.12.0 from source, then patched qplaintextedit.cpp and rebuilt qtbase. Built the annulen QtWebkit, and then built Sigil against my custom Qt5.12.0. Used lddtree to verify that Sigil was, in fact, using the correct Qt5, but it was all for nought.

At least I should be setup for a quick turnaround should you want to test any other patches. :)

**Comment by kevinhendricks** [comment]
Wow, I could see nothing else wrong with their change.  Will you please grab an old version of qplaintextedit.cpp from 5.11.2 or 5.11.1 or even earlier and recompile once more to verify this problemis really is caused by that change to qplaintextedit.cpp.  If so, using an older version, should fix this problem completely.

**Comment by UniverseIsProprietary2** [comment]
@kevinhendricks Your patch fixes the problem, at least with Qt 5.12.0.beta3 (this is the version from which issue starts to occur). It is indeed strange, that the issue does not occur in macOS. Unfortunately, I don't have a Mac and my machine is too old to run macOS in VM, so I can't test Sigil on it.

> To make a long story short... the scrolling Code View issue was still present after patching qplaintextedit.cpp on Linux.

This is strange! The patch provided by @kevinhendricks at least works on 5.12.0.beta3, I will try on 5.12.0.

**Comment by dougmassay** [comment]
I'll try rebuilding to make certain the patch "took". It looked to me as if make picked up the changed file after applying the patch, but maybe I messed up.

**Comment by dougmassay** [comment]
I'll just rebuild everything (with the patch) with a clean build directory to be certain. I can start the build before I go to work and then test again this evening. Thanks, though.

**Comment by kevinhendricks** [comment]
If @dougmassay can confirm the fix, I will clean up the patch and attach it to that Qt bug report along with an explanation of how/why we think their previous "fix" is broken.

The bottom line is a block that is visible that has a lineCount of 2 or more does NOT indicate a visibility change.

**Comment by kevinhendricks** [comment]
This may be a better variation of that patch.  If anyone gets a free moment please try replacing the lines inside the #ifdef 1 with the following:
```
           // BUG:   block.lineCount() > 1 when visible should NOT indicate a visibility change                                         
           // LOGIC: a currently visible block should have a line count > 0                                                             
           //        a currently NOT visible block should have a line count of 0                                                        
           //        otherwise: a visibility change has happened                                                                        
           const int newlinecount = block.isVisible() ? 1 : 0;                                                                          
           bool changed = block.isVisible() ? (block.lineCount() == 0) : (block.lineCount() > 0);                                       
           if (changed) blockVisibilityChanged = true;                                                                                  
           block.setLineCount(newlinecount);                                                                                            
```

If this also fixes the problem, then I will submit this change to Qt in the original QtBUG-69310 report to try to get the attention of the author of the "fix" and see if I can get them to fix their "fix".
https://bugreports.qt.io/browse/QTBUG-69310

**Comment by kevinhendricks** [comment]
Attached is a new version of the fix as a patch file against the original code:
[qplaintextedit_fix_v2.patch.zip](https://github.com/Sigil-Ebook/Sigil/files/2774124/qplaintextedit_fix_v2.patch.zip)

**Comment by kevinhendricks** [comment]
FWIW, It alone should not break anything as it just corrects the logic of the original fix.  So as long as the original fix does not break other software, our version will not either.

**Comment by kevinhendricks** [comment]
Thanks @dougmassay and @UniverseIsProprietary2 for confirming the fix to their "fix".  I have added an explanation and attached our patch to the original bug report here.

https://bugreports.qt.io/browse/QTBUG-69310

Now all we can do is wait and hope someone from Qt will at least look at it and comment and hopefully include a variation of it in an upcoming Qt 5.12.x release.  If we hear nothing, then we will need to build our own Qt from source when we move to Qt 5.12.x for releases and beg the Linux Qt packagers to include it.

I will leave this issue open until we hear one way or the other.

**Comment by dougmassay** [comment]
If there's no response, we could always file a new bug report linking to the one that was "fixed."

**Comment by kevinhendricks** [comment]
Agreed.  I will wait until Wednesday and if we hear nothing, we can generate a new Qt bug report to see if that helps garner some attention.

**Comment by kevinhendricks** [comment]
There is hope.  I just got an e-mail alert that a Qt developer has reopened that bug.  That means they are at least willing to look at it.  So hopefully a fix of some sort will make it into Qt 5.12.2

**Comment by kevinhendricks** [comment]
@dougmassay @UniverseIsProprietary2  Please verify the following official Qt fix for ths problem and let me know if it works so that they can close this issue asap:

https://codereview.qt-project.org/#/c/250707/1/src/widgets/widgets/qplaintextedit.cpp

Logically it is identical to our patch but better in that it takes fewer lines and needs no local variables, so it should fix things.

I will rebuild on Mac and test things too.

**Comment by dougmassay** [comment]
I'll do my best to build/test on Linux tonight, but I'm still not tooled up to build Qt5.12.x on Windows yet.

**Comment by UniverseIsProprietary2** [comment]
> @dougmassay @UniverseIsProprietary2 Please verify the following official Qt fix for ths problem and let me know if it works so that they can close this issue asap:
> 
> https://codereview.qt-project.org/#/c/250707/1/src/widgets/widgets/qplaintextedit.cpp
> 
> Logically it is identical to our patch but better in that it takes fewer lines and needs no local variables, so it should fix things.
> 
> I will rebuild on Mac and test things too.

The official fix also fixes the bug. Thank you both @kevinhendricks and @dougmassay for your work on fixing the issue. This bug seems complex, as other editors like calibre do not have this issue, so there must be something else also, but I don't know yet what is it.

**Comment by dougmassay** [comment]
The official change tests out OK on my Arch Linux system.

**Comment by UniverseIsProprietary2** [comment]
> Calibre does not use QPlainTextEdit at all, it uses the QTextEdit widget. The code in QTextEdit was not touched and already detected if visibility changed properly. The QPlainTextEdit widget is supposed to be optimized for large text file editing according to Qt, so Sigil uses that widget. So I would not expect any editor which does not use QPlainTextEdit to be affected.
> 
> I pass along the testing info to Qt.
> 
> Thank You

Ah, I see, though I've tested some example/demo editors supplied with Qt (with basic code highlighting, line wrap, etc.) which uses QPlainTextEditor and I couldn't reproduce the issue on them.

**Comment by dougmassay** [comment]
It's a cobbled-together nightmare on my sole, physical Windows machine right now, but I've verified that the official Qt fix remedies the original issue on Windows as well.

**Comment by kevinhendricks** [comment]
Great Doug!  Thanks.

**Comment by dougmassay** [comment]
He sure seems to be having a heck of a time getting this fix past staging. I don't think it has anything to do with the fix itself, but still ... I'll be happy when I see this thing merged.

**Comment by UniverseIsProprietary2** [comment]
> Do they synchronize syntax highlighting? Do they rehighlight on "focus in" events? Sigil does both of these and Qt has supported it for years and years. Qt's recent bug "fixes" were NOT well thought through logically and as a result created problems. I am not a Qt developer but I could easily see both changes were broken by just staring at the code and their "fixes".

No, the code I tried were not synchronizing rehighlight, but it did rehighlight on various events, like focus in, focus out, etc. That's why I've asked to prepare some proof of concept, a minimal set of code, where the issue with scrolling would be present. Anyway, debugging Qt isn't the most pleasurable thing in the world, especially when you are not familiar with it's code as me.

**Comment by UniverseIsProprietary2** [comment]
> That's why I've asked to prepare some proof of concept, a minimal set of code, where the issue with scrolling would be present.
> My 2 cents ... Logically incorrect bug "fixes" done by official Qt developers, should never need a proof of concept. If just eyeballing the code and their "fixes" makes the bug evident, why would anyone need more?

I agree with you on that in general, however, I was asking for a PoC to rule out at once other possible factors.

> It seems many younger developers seem fixated on test case code when if fact they should spend less time on that and more time on actually studying the code of their on project. Linus himself has pushed exactly this idea for a long time ... know/read the code and do not just rely on a debugger and simple tests.

I don't know how much of this is true, but it seems that you are right in this case. Have you not considering join Qt development? No doubt, there would be less bugs.

> In fact, one could easily argue that it was the simple code to reproduce the scrolling issue in the original bug report combined with a developer that was unfamiliar with the code, that made this bug possible. Their broken fix worked only for the simple provided test case and not for actual working code in the field where block.lineCount() can easily be greater than 1 if the block of text is long and the layout determines it will take more time.

To be fair, I don't even know, why some code submitted to Qt, which was not even supposed to work the way author described, was classified as a bug or missing feature in Qt.

**Comment by kevinhendricks** [comment]
Closing this as the bug is really in Qt and we have an official Qt fix.

**Comment by dougmassay** [comment]
Qt5.12.1 (with the fixes for our bugs back-ported) has recently been released on Arch Linux. I can confirm that it fixes the original issue prompted by this report.

**Comment by eli-schwartz** [comment]
> Does Eli still package Sigil for ArchLinux? Do we know who packages Qt for Arch Linux?

Please feel free to @mention me at any time, I follow downstream bugtrackers much less frequently than releases but I have no intention of stopping as the sigil packager for the foreseeable future. :)

And yes, as discussed via PM on mobileread I was requested to get these backports into Qt and our Qt packager was more than happy to do once I linked him the relevant commits which @dougmassay pointed me to.
