### ISSUE TITLE
Highlighting text too slow with mouse

### ISSUE THREAD

**Issue by lodgerz** [Sigil-Ebook/Sigil#39]
Hi,
highlighting text (in Code View) is very slow if i use mouse (and if in my system clipboard there is a text too long) :-(
Instead if i highlight text with "SHIFT+ Arrow keys"  it works good. :-O
it's very strange :-|

I use sigil-git on ArchLinux.

**Comment by kevinhendricks** [comment]
Not reproducible.  Closing

**Comment by MisterAP** [comment]
This is reproducible.  I believe it is a timing problem.
Ubuntu 14.10, 64-bit, up-to-date.  sigil 0.8.2.
sigil uses:
-rw-r--r-- 1 root root 5.3M Oct  3 10:04 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.3.0

If I launch 'sigil' from the command line - blank/new file, highlighting is slow.
But 'strace sigil' highlights at the expected speed, which makes me think it is timing.
Is there anything I can provide to help track this down?  The strace output is 1.5MB including launch and exit if that would be useful.

**Comment by user-none** [comment]
@MisterAP  Realize that Linux is not an officially supported OS. Sigil may have packages for Linux made by various distributions and Sigil is designed to be cross platform so it will run on Linux that doesn't mean Linux issues will be investigated. Only issues that are reproducible on OS X (primary development is on OS X) or to a lesser extent Windows will be considered and investigated. Any Linux specific issues is not considered a problem.

If you disagree then please provide a patch to resolve the issue.

**Comment by MisterAP** [comment]
I have not seen anywhere that says only bugs for OS X will be looked at.  Not a criticism, just an observation.
I like sigil, which is why I was interested in getting things to work a bit better.

Anyway, for Linux (ubuntu) users, I have a cheap and nasty avoidance for the problem.
I created sigil.sh which just does:
strace /usr/bin/sigil "$1" >/dev/null 2>&1
then I made sigil.sh the default for .epub files.
Don't forget the "" round the argument.

I can cope with the inefficiency/slight slowing of the strace as it more than makes up for problems with highlighting.  It does hide any error output, though, should there be any.

If I get a chance to delve further into the code and find the actual problem, I will let you know.

Thanks for creating the program.

Alan

**Comment by user-none** [comment]
@MisterAP it's been the policy for years and has been discussed on the official support forum, it's been on the old wiki. It's even (I made it clearer the other day) in the install.md file in the docs directory.

**Comment by anubisthejackle** [comment]
I don't see the point in ignoring clear bugs in your code. I understand that you wouldn't make these a high priority, but simply ignoring them isn't the way to go about it.

How about reaching out to the linux community, and working on making a true cross-platform system?

**Comment by user-none** [comment]
@anubisthejackle 

Feel free to submit a patch. I never said i'd reject it. I just said it's not a bug as far as Sigil is concerned because it isn't present on any other platform which points to it being a bug in Qt. Unless you can prove it's Sigil and not Qt or provide a patch this isn't considered a Sigil bug.

Also, again Linux receives ZERO support. That's been the policy for years if you want to know why please read http://john.nachtimwald.com/2014/11/28/why-i-love-and-hate-linux-distros/ especially the bad parts where my projects have been screwed by Linux distros on multiple occasions and simply getting fixes into Linux distros is nearly impossible.

**Comment by anubisthejackle** [comment]
You'll get no argument from me that linux distros are pretty horrible, my argument is simply that distros aren't the users, and closing out issues such as this move them out of the list, and make it harder for people like myself to find them, and fix them, and submit those very patches you said you'd review. 

My suggestion would be to label them separately, and let them fall to the end of the tickets list, so that we might chip away at them as time allowed.

**Comment by MisterAP** [comment]
Could I point out that it is not easy to discover that Linux is not supported as far as bugs are concerned. The link above about distros was very informative, BTW.
Users new to Sigil bugs (as opposed to using Sigil use) will not have seen the forum discussions.
No Wiki that I have found mentions the support issues.  The ReportingProblems link comes up Not Found.
The sticky sections and the FAQ don't mention the support issues.
@John S. Despite what was said earlier about the information being available, I cannot find anything in the Install.md file.  Plus I installed via a repository rather than from source, so didn't get to see the install file.
I'm not trying to criticise - I know how it is dealing with users who didn't RTFM - but in this case I can't find the information in TFM.  The release notes for 0.8.3 DO mention the support issue, but I installed 0.8.2.
If the "cross-platform" heading mentioned that only bugs associated with Mac or Windows would be considered, you would save yourselves a lot of hassle.  Or put it in a sticky note on the forum, or in the FAQ.

**Comment by mapreri** [comment]
From docs/Install.md (with the text wrapped):
```
Primary development happens on OS X. Limited testing happens on Windows.
Linux is not considered a platform for user submitted bug reports. Only patches
to fix issues specific to Linux will be evaluated. But only if they do not interfere
with other platforms.
```

It's sad, yes.
As I said in a email I sent to John I'm not convinced (this with my debian maintainer hat), but I fully understand his position, and I respect it.
I'll try to change his mind another time, when sigil will finally land in the debian archive.

**Comment by user-none** [comment]
@MisterAP I'm sorry for the confusion. Sigil is moving homes from Google Code (which Google is basically abandoning). Right now the main home page is this GitHub project. In the future I plan to have a real home page not dependent on a third party url (like now) that can point people to the current code (no matter where it is) will have info such as support policy.

Also, as @mapreri Linux is not supported for bugs. But that doesn't mean people on the forums won't help or aren't allowed to help with Linux related issues. The forum is a completely different beast than the bug tracker. At one time the bug tracker had to be disabled because it was the same series of bugs post over and over again closed as won't fix because that version of OS X isn't supported and is so out of date it's scary you're still using it.

So closing issues that are not something that will be addressed I don't see as wrong. You can still issue a pull request with code that fixes the issue. In that case I'll evaluate it. Not to mention, you can and should be searching closed bugs as well as open ones.

**Comment by anubisthejackle** [comment]
@user-none Might we, then, create a label "linux" so when a bug needs to be closed as Linux, it can be labeled to make searching the closed tickets easier?

**Comment by anubisthejackle** [comment]
Or even a Wiki page to post references to the open Linux issues, so one might go through and fix them as they choose without cluttering the open issues?

**Comment by user-none** [comment]
I've added a Linux label.

**Comment by user-none** [comment]
A wiki post doesn't make sense as there is really only one issue and it's this one. Which again, isn't a problem on OS X or Windows which leads me to believe it's really a Qt issue. It should be brought up with Qt upstream. Unless proven otherwise this issue has honestly become a waste of time.

**Comment by anubisthejackle** [comment]
I agree, was simply spitballing ideas. Label is the perfect idea.

**Comment by MisterAP** [comment]
Steep learning curve.
Just so you know - 0.8.4 seems to fix the problem (on Ubuntu 14.10), at least sufficiently to make the highlighting useable.
I agree it is probably a QT problem, but sigil is the only program I have used where it shows up, so at first glance/google it looks like sigil itself.
And I do know how much time and effort it takes to keep documentation in step. Always a balance between giving people code they demand and documentation they would use (or anyway, say they would).

**Comment by lodgerz** [comment]
sigil 0.8.4-1 (ArchLinux) is better, but it is still slow if I copied something from other programs.
i made a video who shows this strange bug:
http://quellen.altervista.org/Sigil_qt_bug.mkv

**Comment by kevinhendricks** [comment]
Reopening as others can now recreate your issue.  I still cannot recreate what you are seeing in MacOSX, Windows, or Linux Mint 17.2.  Will update if there is any progress.

**Comment by eli-schwartz** [comment]
And for context, the issue came up again here: http://www.mobileread.com/forums/showthread.php?p=3244797

The issue seems to be related to whether or not the system clipboard has (any) content when Sigil is launched. At least, I can make Sigil slow down or speed up by adding to or clearing the clipboard, then restarting Sigil.

**Comment by kevinhendricks** [comment]
Okay, I can now recreate this in a new way that really tells me this is a bug in Qt.

1. open firefox or any browser to any page
2. xsel -bc
3. sigil
4. Play with text highlighting in default file 1 - it is fast
5. Click on your browser window and select some text (any text) and copy it to the clipboard, then return to sigil
6. Now try highlighting text again in Sigil it will be slow
7. highlight a small piece of text in Sigil and copy it to the clipbord
8. Now try highlighting text again in Sigil and it will be fast again

So the mere presence of any data not from Sigil in the clipboard will freak things out.

I searched and found this bug:

https://bugreports.qt.io/browse/QTBUG-38585

Which reports a problem with sleeping too much in clipboardWaitForEvent in qclipboard_x11.cpp causing slowdowns and delays.

There was a patch supplied but of course Qt ignored it and then someone at Qt claimed the file qclipboard_x11.cpp no longer exists so they abandoned the patch completely.

Of course, during the interval of qclipboard_x11.cpp was removed and replaced by qxcbclipboard.cpp and it has the exact same issue. Any time it wants to communicate with an outside app (another app that owns the current clipboard contents) it sits in a wait loop for 50000 us or 50 ms. Since highlighting text in X11 is a clipboard activity, as long as anything foreign is in the clipboard, it will sit and sleep many many times here while we are trying to highlight something waiting to talk to the owner of the current clipboard contents.

This problem does not exists in Windows or Mac because the system clipboard is global and there is no such thing as owners of clipboard contents, and because simple selection (highlighting text) is not a clipboard activity on Mac and Windows.

My guess is Qt will never fix it given how they ignored the problem and the patch offered and then abandoned it when they moved to qxcbclipboard.cpp which almost always uses the event loop approach. Sigil has about 3 or 4 other bug reports at Qt for years now that have never seen any action. One includes a use after free that could be used to attack the application. I have no hopes of anyone at Qt even looking at this issue at all, let alone fixing it.

So the question is how can we work around it on Linux? Given simply copying anything to the clipboard inside Sigil will prevent the issue (replacing the foreign ownership) there should be something Sigil can do. I am thinking of having Sigil check for ownership of the item on the clipboard and if necessary copying it and then pasting it back as its new owner. This should be doable.

Anyone have any pull with Qt about bug fixes for Linux that could get them to at least fix this, would be nice.

Kevin

**Comment by kevinhendricks** [comment]
Last commit, confirmed to do the trick.  Closing this as fixed.  The fix will appear in the forthcoming Sigil 0.9.3 release which should be out within a week or two.

**Comment by mapreri** [comment]
oh, cool!

I pinged the Debian Qt maintainer to see if he can push that stupid patch forward (if it's enough).
Anyway, nice this got workarounded here, Qt updates takes time to come, this is much quicker.

Thank you for it, I'm gonna test the patch soon ! ♥

**Comment by perezmeyer** [comment]
I'm the Debian Qt maintainer whi mapreri refers to ;)

I looked at upstream's bug report and of course it will not be processed because the patch is for Qt4 which is currently dead upstream.

@mapreri Can you reproduce the issue with Sigil+qt5? I'll try to reproduce it later tonight or tomorrow. If I can reproduce it and get the proper place to fix this in Qt 5 I can probably make it happen for 5.6 (and even backport it to 5.5 if needed).

@kevinhendricks Can you reopen the bug please? That commit doesn't cares wether the code is compiled against Qt 4 or 5, and I'm pretty sure I will be able to fix it for Qt 5 if I can reproduce it with it.

Thanks!

**Comment by mapreri** [comment]
yes, the current package in debian shows the issue, and it's compiled against qt5 (so it's pretty easy for you to test it out).

BTW, Sigil needs Qt 5.4 or higher, I don't think there are needs to check if it's compiled against Qt4 here.

And thank you for picking that bug up!

**Comment by kevinhendricks** [comment]
That earlier Qt patch will no longer apply anymore, but someone can and should at least try reducing the sleep time in the Event Wait routine to be something much shorter as the patch basically does but apply it in the equivalent spot in qxcbclipboard.cpp.  The problem is there somewhere, and that earlier bug report just gave me the clue as to what may be going on.  Nothing else I can think of, fits the symptoms we are seeing.

Thanks,

Kevin

**Comment by kevinhendricks** [comment]
The only bug report I control is here in Sigil.  

The current Qt bug filed by a Sigil user is here.
https://bugreports.qt.io/browse/QTBUG-44849 but it is not my bug.

As far as I know that bug is still open. 

Hope this helps.

Kevin

**Comment by perezmeyer** [comment]
Right, either that loop needs tightening or a better solution like the proposed Qt4 patch did. I have added mor einfo to the bug and will poke upstream to assign it.

**Comment by perezmeyer** [comment]
@kevinhendricks Oh, you found a much detailed bug report and already popped in, cool! I've already starting watching it and I'll try to give more info if possible. Thanks a lot!!!

**Comment by perezmeyer** [comment]
I tried to reproduce the bugin Debian using KDE with no avail. Just to be clear: by "highlighting" you mean selecting text? Or am I missing something?

**Comment by perezmeyer** [comment]
As long as highlighting means "selecting text" I can't reproduce this issue neither on Plasma 5 nor Fluxbox.

**Comment by kevinhendricks** [comment]
The steps to reproduce this are as follows (I have added in some details)


	• open firefox or any browser to any page


	# this will clear the clipboard
	• xsel -bc   

	# fire up sigil (not master from today because it has a workaround in it)

	• sigil

	# click mouse anywhere anywhere in the xhtml code and hold it and move around
	# area being selected should follow you mouse movement promptly

	• Play with text highlighting in default file 1 - it is fast


	# For the next step, click and select text in Firefox or whatever browser window you had open **outside** of Sigil
        # right click and use the menu Copy so that it gets copied to the clipboard and is 
	# not just the current selection

	• Click on your web browser window and select some text (any text) and copy it to the clipboard, then return to sigil

	# again click and hold anywhere in the xhtml code window and quickly move pointer, the selection highlighting will now not follow the mouse well
	• Now try highlighting text again in Sigil it will be slow

	# In the same window in Sigil, click on a small piece of text and select it and right clikc to copy it to the clipboard
	• highlight a small piece of text in Sigil and copy it to the clipbord

	# After the copy is done, try clicking and holding the mouse in that window and see that selection (highlighting) text again prompty follows the pointer
	• Now try highlighting text again in Sigil and it will be fast again


I have just added a commit today to Sigil to work around all of this so use any earlier build than todays.

Hope this helps.

Kevin

**Comment by kevinhendricks** [comment]
Did you selected text from outside Sigil (in an external program such as a web brower) and used right click to get the Copy menu to copy it?

> On Jan 23, 2016, at 8:42 PM, Lisandro Damián Nicanor Pérez Meyer <notifications@github.com> wrote:
> 
> As long as highlighting means "selecting text" I can't reproduce this issue neither on Plasma 5 nor Fluxbox.
> 

If so, what version of Qt are you running with?  I have tested with Qt 5.4.2 and all earlier versions.  Multiple people have been able to recreate this on Arch, Linux Mint 15, Linux Min 17.2, and others.

Kevin

**Comment by perezmeyer** [comment]
Yes, I'm using chromium and right click to select "copy".

Also I'm using sigil 0.9.2, qt 5.5.1 on Debian.

I'll try now with your extended steps.

**Comment by kevinhendricks** [comment]
Could your Desktop have a better / newer improved version of xcb library managing the Linux system clipboard?

**Comment by kevinhendricks** [comment]
The current master still says 0.9.2, the workaround was just committed today in prep for a Sigil -0.9.3 release later this week.  If you have access to any earlier version you should see the problem.

**Comment by perezmeyer** [comment]
libxcb 1.11.1. This is what both Debian testing and unstable have. @mapreri Can you try to reproduce with an up to date testing machine? or have you tried in unstable?

**Comment by perezmeyer** [comment]
I'm using sigil's content.opf file and the default one is "Section0001.xhtml which is empty and I see no problems, same behavior both in Plasma 5 and Fluxbox.

**Comment by perezmeyer** [comment]
Also tried with iceweasel (firefox), I can't perceive any issues.

**Comment by mapreri** [comment]
I use unstable, and I can reproduce it anytime.
maybe let's try figure it out via IRC? (but gonna fall asleep pretty soon,
so it's either now or tomorrow afternoon)

**Comment by kevinhendricks** [comment]
Hi,

The xhtml is not empty.  You must be in BookView.  Click on the little <> icon near the top of the window to change to CodeView so you can see the xhtml code.  Sigil uses a stacked widget with both side of the file available.  Problem happens only in xhtml in its CodeView windowdue to xhtml highlighting and QWebpage associated stacked widget (in other words due to load) not in the content.opf which has no webpage stacked widget side (ie. not BookView side)..

So just in the xhtml side in CodeView (you should see the xhtml codes - not BookView) when you click and drag after copying something outside of sigil it should be slow.

Kevin

**Comment by kevinhendricks** [comment]
My Linux Mint 17.1 Cinnamon has libxcb 1.1.0 which is a bit older than yours.  Maybe that is the difference?

**Comment by perezmeyer** [comment]
Right, my bad, I was seeing the WYSIWYG editor. 

But I'm afraid I can only reproduce the bug in sigil, not in Qt5's example sdi nor in kate, so we still have a great chance of really being a sigil bug.

@kevinhendricks Can you make a very small app that has the same editor as the code one? The fewer the lines the better. If we can reproduce it in a small example we can go and ask upstream to take a look at it.

**Comment by kevinhendricks** [comment]
Sorry, not gonna happen.  I took the time to do that for other Qt bug reports in the past and even used Qt's own Creator to demo a bug and NOTHING ever came from it.  If you understand that Sigil is only effected on Linux (same code base for all platforms and both Windows and MacOSX all work like a charm) and that a simple copy of something to the clipboard from outside Sigil is enough to cause the slowdown, and that Sigil never even has to use that clip in any way, combined with the earlier bug report about the huge delays in the qclipboard_x11/qxcbclipboard event loop, then all the evidence points to Qt and specifically how they handle the system clipboard and ownership of clips on Linux. 

I will happily just use my workaround.  I have worked around a number of Qt bugs after finding that my bug reports go no place there.

**Comment by perezmeyer** [comment]
@kevinhendricks that's totally fine :-) The good news are that the bug moved forward in upstream and now there is even a more in-depth analysis of the problem.

May I suggest you to keep this bug open? It would be really cool if we can get your work-around code to compile only with versions of non-fixed Qt (if we get a fix at some point).

Another idea could be to open a new bug stating this issue and close this one.

Thanks a lot for your efforts!

**Comment by kevinhendricks** [comment]
@perezmeyer, @mapreri 

Would you both please take a look at the discussion about QWebKit here at this Qt Issue:
https://bugreports.qt.io/browse/QTBUG-50686

Is it true Qt 5.6 removes QtWebkit completely?  All less than 13 months after they said it was feature complete,  and only a little over 6 months from when they said it was deprecated.  

As a result None of my bug reports will ever be fixed.  I totally wasted my time even reporting them. 

According to that Qt person, no new releases with Qt WebKit will ever be made?  Does everyone at Qt agree with this position?  How do the Linux Distributions and KDE people feel about this?  Is there anyone with any pull at Qt to at least question the sanity of this plan?

It seems like Sigil epub3 development is going to have to be put aside until we completely redesign BookView and Preview to use QWebEngineView and then start filing bug reports for all of the broken things we find in there.

As an alternative, has anyone played around with Mozilla's Gecko web widget and how hard would it be to use that in a project like Sigil.  At least it supports MathML natively and has no plans to drop support for it anytime soon.

**Comment by perezmeyer** [comment]
This is, believe me, a hairy issue :-/

* It's not going to be *completely* removed, source package should still be able to build with newer versions. Distros will probable ship it for as long as possible (ie, in the best case scenario, for Qt5's lifetime).
* For other OSs you should still be able to produce binaries by compiling it.

Allan is actually the qtwebkit/qtwebengine maintainer. As he said the change went too fast, but it was sadly unavoidable.

There was a loooong thread last year in Qt's development mailing list about it. The sad true is that you need an enormous group of coders to keep up with webkit. Webengine upstreams seems to be more reachable so it was decided to do the switch. Believe me this was really discussed in many ways. I do agree with upstream that keeping up with webkit was really complicated.

With respect to distros, the BSDs are having quite some issue to package webengine. Fedora and Debian had also embedding problems, but Fedora later relaxed it's rules and it seems they are now moving into packaging in. On the Debian side no one has stepped up to do the job, and I really don't want to put time on webengine.

On the KDE side I can't comment. I *guess* feelings are mixed, but don't take my word for that.

With respect using web widgets: I really don't know, as I never had the need to use them.

So yes, not a nice situation at all.

**Comment by dougmassay** [comment]
What a fucking nightmare.

The pre-compiled binaries were the only thing that made it possible for the average Linux user (read: not complete geek) to quickly "roll their own" Sigil. Now if we want to continue to use WebKit AND take advantage of Qt5.6+ bugfixes, those same average users will also be forced to build their own Qt from source (or hope their distro maintainers continue to include  Webkit). If we port to QtWebEngine, we leave those same average Linus users in the lurch.

This constant requirement to have a bleeding edge system (or to build everything from scratch) to be able to take advantage of the latest Qt advancements/bugfixes is bullshit. Sigil used Qt4.8 for freaking _years_ . Would love to see a stable, steady Qt5.X so that Linux could hang its hat on something for a while instead of always scrambling to keep something in the repos that's not obsolete already.

Really disappointing.

**Comment by kevinhendricks** [comment]
@ Doug,
I agree completely.  Sigil could just pick a release and stay there for a few years.  If so, should we stick with Qt 5.5.1 (the most up to date version) or just stay with our current Qt 5.4.2?   Of course - if we did decide to simply pick a version and stay with it,  the highlight bug fix and all future bug fixes would never make it into Sigil (so we just stick with the workaround).  Given Qt has never once fixed any of my bug reports - I am not sure if we gain much by staying with a current version.

BTW, QWebEngineView has many of the same bugs AND pre-compiled versions will NOT play mp3 audio at all. They have the exact same XHR bug and audio/video bug we reported.   I have no idea about mp4 video or not.  So even if we updated to QWebEngineView, users would still have to build from source just to enable basic mp3 support which is a requirement for epub3 and supported in many epub2’s.   And given how few projects use QWebEngineView, I am sure there are going to be a million tiny corner cases that will need to be fixed.

My playing around with QWebEngineView briefly shows it is much slower to startup then QWebView was as well.  Given all of the javascript we use in BookView editing to detect the cursor position alone ie. find its equivalent place in CodeView) and the fact that javascript access is no longer synchronous, we will be adding signals and slots and callbacks everyplace, just to make sure the positions are set and read correctly before allowing things to proceed (QWebView had a synchronous javascript model).  I frankly think moving to QWebEngineView is going to be a nightmare for something as complicated as WYSIWYG editing in BookView.  I hope I am all wet.

**Comment by MisterAP** [comment]
@kevinhendricks - many thanks for the effort you have put into this.  I did look at it a while ago, but without any real knowledge of how QT worked I didn't get far before I ran out of time.
It does look as though it has shown up more problems than it has avoided.  From an outsider point of view, sticking with a known set up bugs in a fixed QT version sounds like the least frustration.

**Comment by lodgerz** [comment]
with 0.9.3 version the issue has been resolved.
thanks @kevinhendricks !

**Comment by kevinhendricks** [comment]
@lodgerz Glad to hear the workaround for the Qt/Linux bug has done the trick.
