### ISSUE TITLE
jumping error while manually correcting code with spellcheck open

### ISSUE THREAD

**Issue by lemacklemack** [Sigil-Ebook/Sigil#393]
While using the Spellcheck to view possible typos, when I manually change the error in codeview, after pushing one key (whether it be backspace, or a specific letter to replace another) the codeview jumps to  a different random location in that same xhtml doc. The cursor is not misplaced, it happens almost always, though in instances where I go from codeview to wysiwyg back to codeview THEN make the manual change, it does not occur.

**Comment by kevinhendricks** [comment]
I can not recreate this in any recent build from master.  

Please provide more details.  Which version of Sigil? 

Is this Windows or Mac and if so which OS version? 

If Linux, which distribution and version and python version?

Also which version of Qt?

**Comment by lemacklemack** [comment]
Sigil 9.10

Windows 10

5.6.2 Qt

I'm working on an older epub2, the jumping doesn't occur in epub3.

**Comment by dougmassay** [comment]
I know they said the cursor was not misplaced, but there was a fix in the changelog after 0.9.10 that had to do with cursor-jumping and spellcheck. Perhaps it's related (and fixed)?

When I go from CV to BV and back again, my cursor is nearly always moved toward the beginning of the current block element. This is expected I think. It used to jump to the top of the file and we came up with the current block element as a compromise. With some super-long paragraphs, this could cause the CV window itself to scroll.

The main concern is keeping things synced between CV and Preview, I think.

**Comment by kevinhendricks** [comment]
Something is very strange if the problem only happens with epub2 and not epub3 as reported.  Over 99% of the code doesn't care which epub version.  That would rule out Qt issues as well.  

Perhaps our earlier fix does fix this issue.

We hope to release an updated version of Sigil within a week or so and have closed the tree to changes for translations people to have a chance to update their translations.  

I propose we shelve this issue until after the release.  If the release fixes the problem, great and we close this issue.  Otherwise we can start fresh trying to track this one down.

**Comment by kevinhendricks** [comment]
I can not recreate this with the new build either.  So I am closing this.  If anyone can recreate this issue, we will reopen the issue.
