### ISSUE TITLE
Cursor not visible when renaming a text file

### ISSUE THREAD

**Issue by mrprobert** [Sigil-Ebook/Sigil#398]
The cursor in the filename box is initially invisible during a file rename operation. Environment: Windows 10 64-bit, Sigil-0.9.12.

1. Open a new Sigil document.
2. Right-click on Section0001.xhtml and select rename.
3. Move the mouse pointer to somewhere on the filename and left-click  --> cursor is not visible.
4. Press the left or right arrow key to make the cursor visible.

**Comment by kevinhendricks** [comment]
Yes this is a known Qt bug since 5.8 and it impacts all platforms.  There are many open bug reports about it on Qt but none have been worked on for a while.  Not sure how or even if we can work around it at all in Sigil.  

As you said only pressing a key will make the cursor visible so using up, down, right or left arrow keys will make the cursor visible again.  The actual blinking of the cursor inside the QLineEdit was even broken in Qt 5.6 and still is not fixed.

**Comment by kevinhendricks** [comment]
Okay, I found a horribly hackish way to work around this issue by injecting a fake shift key press and release event into the qlineedit used in Sigil/src/Misc/FilenameDelegate.cpp.  The key release event will update the cursor starting the process inside the qlineedit.

It seems to work in my testing.  When you rename, if you mouse click, the cursor should now appear where you clicked.

Pushed this fix to master.

As a workaround, simply manually hitting the shift key and letting go before clicking with your mouse the first time should do the same thing.

Closing since this is now "fixed" - argh!  in master.  

Thank you for your bug report!
