### ISSUE TITLE
Qt translation is not loaded correctly

### ISSUE THREAD

**Issue by cges30901** [Sigil-Ebook/Sigil#400]
Hello, I am using Qt 5.12.1 on Manjaro Linux.
After completing zh_TW translation, I find that some strings in Sigil are still in English, like file dialog.
![_2019-03-01_22-10-52](https://user-images.githubusercontent.com/19516286/53643415-f2422100-3c6e-11e9-8465-7ce1de7e1fcb.png)
It seems that Qt translation is not loaded correctly. In https://github.com/Sigil-Ebook/Sigil/commit/c4f54a64e2d7ff1427c7cfbf9cb8302566377be9, Sigil loads both qtbase_XX.qm and qt_XX.qm. However, in https://github.com/Sigil-Ebook/Sigil/commit/8710254ae58af7df557235719e0bd8e51bfc175c, only qtbase_XX.qm is loaded. The problem is that there is no qtbase_zh_TW.qm. Only qt_zh_TW.qm is present. So I think qt_XX.qm should also be loaded.

Related issue: https://github.com/Sigil-Ebook/Sigil/issues/346

**Comment by dougmassay** [comment]
This is a qt translation issue. If those translating Qt for your language don't provide a qtbase_zh_TW.qm file (as has been the Qt translation standard for a long time now), then you'll need to take it up with them. The logic to determine whether or not the base file has been properly provided is not something I want to get into in our build process. The second commit you linked to was superceded by the first commit precisely BECAUSE loading qt_XX.qm files led to problems and broken translations. qt_XX.qm files are simply not the way things are done anymore. Take a look at how many are left (that contain valid translations) in the Qt distributions.

qt_xx.qm was originally supposed to be meta-file that indicated the actual translation file(s) to be loaded. Some still do that, but some (a very small amount) insist on using it for the full translations. I'm not going to try and make our cmake build logic determine if the correct translation files were provided or not. Sorry. It's only the last few versions of Sigil that those internal Qt strings were even translated for _any_ language.

**Comment by cges30901** [comment]
I just saw that Chinese (Taiwan) translation for Qt got updated and qtbase_zh_TW.ts was added. (http://code.qt.io/cgit/qt/qttranslations.git/commit/?id=4622012565e28bffec22daff5fa81addece703e3)
So I guess this will be solved soon.

**Comment by dougmassay** [comment]
Yes. When and if Sigil moves to Qt5.12 for it's Windows packages, this should be resolved. In the meantime, however, I wouldn't be at all afraid to grab the qtbase_zh_TW.qm file from a Qt5.12.x installer and manually add it to Sigil's translations folder. The base GUI strings haven't really changed across versions, in a long, long time, and several people have reported success when doing this Sigil was still using Qt5.6.x.

Or you can use Qt language tools and compile the .qm from the .ts in the source code yourself, if you don't want to download/install the whole Qt5.12.1 package just to get that one .qm file.

**Comment by cges30901** [comment]
> Or you can use Qt language tools and compile the .qm from the .ts in the source code yourself

Thank you for your suggestion. I used `lrelease` to compile and I got Qt translation.

> download/install the whole Qt5.12.1 package just to get that one .qm file

No, since Chinese (Taiwan) translation just got updated yesterday, it is not in Qt 5.12.1 yet. I guess it will be available in Qt 5.12.3 or Qt 5.13.
