### ISSUE TITLE
Validation Errors in EpubCheck 4.0.x Using Sigil 0.9.13 - File Element "div" tag

### ISSUE THREAD

**Issue by ghost** [Sigil-Ebook/Sigil#422]
Using Sigil 0.9.13 (Loaded Qt: 5.11.2) for first time, upgraded from 0.9.9. I received a host of errors when validating with EpubCheck 4.0.x (but none using KindleGen). The error: Error while parsing file 'element "div" not allowed here; expected the element end-tag, text or element "a", "abbr", "area", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "command", "datalist", "del", "dfn", "em", "embed", "epub:switch", "i", "iframe", "img", "input", "ins", "kbd", "keygen", "label", "link", "map", "mark", "meta", "meter", "ns1:math", "ns2:svg", "object", "output", "progress", "q", "ruby", "s", "samp", "script", "select", "small", "span", "strong", "sub", "sup", "textarea", "time", "u", "var", "video" or "wbr" (with xmlns:ns1="http://www.w3.org/1998/Math/MathML" xmlns:ns2="http://www.w3.org/2000/svg")'. The epub still appears fine in book view, in ADE, and Kindle Previewer 3. The errors have to do with the <div> tag, skipping many before reporting an error all the way into the third chapter of the book. Something seems remiss.

**Comment by Mott74** [comment]
Well, I’ve never received this error until using Sigil 0.9.13. I’ve created hundreds of epubs over the years using Sigil. Only this upgrade generated this huge list of errors. I do not believe it is a user or content issue.

I’m not sure what other data you need.

Mark

* * * * * * * * * * * * * *
Mark Highman
Ebook Conversion Tech
mhighman@bakerpublishinggroup.com<mailto:mhighman@bakerpublishinggroup.com>




On May 8, 2019, at 10:11 AM, Kevin Hendricks <notifications@github.com<mailto:notifications@github.com>> wrote:


How is this a Sigil issue? For other users' help please use our MobileRead.com<http://MobileRead.com> support forums. But without file, line, column info about the issue, and access to the xhtml to see what is actually being checked by epubcheck, no one can be much help.

Closing this as epubcheck validation errors are not Sigil issues. They are user/content issues.

Please use our Mobileread forums and supply the missing info and someone there should be able to help.

**Comment by kevinhendricks** [comment]
Given how many users we have and how no one else has complained, I very much doubt this is caused by Sigil unless your sigil.ini files have been corrupted.  If so, please see our release notes.

 Again, go to the Sigil support forum on www.mobileread.com, present the full error message, with file name, line, and column info, and show a snippet of the xhtml code around that issue and ask for help.

**Comment by Mott74** [comment]
Gracious. My apologies. It is my error. Argh!

It was my first use of Sigil 0.9.13 and after all the troubles I had with 0.9.11 and 0.9.12, I was immediately suspicious that something was wrong with 0.9.13. It was the first thing that came to my mind when I saw this huge list of errors when validating. Also, in doing a search on the Internet for the error I had found a reply from Github that this error was an internal error of some kind, though the response is dated back a couple years ago. I figured the same error was happening again in Sigil with this update.

My apologies for taking your time by jumping to conclusions.

I am very appreciative of all the work you guys do with Sigil. I’ve been using it since 2011 and am generally very happy with it! Thank you.

Respectfully,
Mark

* * * * * * * * * * * * * *
Mark Highman
Ebook Conversion Tech
mhighman@bakerpublishinggroup.com<mailto:mhighman@bakerpublishinggroup.com>




On May 8, 2019, at 10:14 AM, Mark Highman <mhighman@bakerbooks.com<mailto:mhighman@bakerbooks.com>> wrote:

Well, I’ve never received this error until using Sigil 0.9.13. I’ve created hundreds of epubs over the years using Sigil. Only this upgrade generated this huge list of errors. I do not believe it is a user or content issue.

I’m not sure what other data you need.

Mark

* * * * * * * * * * * * * *
Mark Highman
Ebook Conversion Tech
mhighman@bakerpublishinggroup.com<mailto:mhighman@bakerpublishinggroup.com>




On May 8, 2019, at 10:11 AM, Kevin Hendricks <notifications@github.com<mailto:notifications@github.com>> wrote:


How is this a Sigil issue? For other users' help please use our MobileRead.com<http://mobileread.com/> support forums. But without file, line, column info about the issue, and access to the xhtml to see what is actually being checked by epubcheck, no one can be much help.

Closing this as epubcheck validation errors are not Sigil issues. They are user/content issues.

Please use our Mobileread forums and supply the missing info and someone there should be able to help.
