### ISSUE TITLE
Different code for italics in Book and Code view (Mac Version)

### ISSUE THREAD

**Issue by fahirsch** [Sigil-Ebook/Sigil#429]
This occurs in the Mac version. I don't know if it happens on other versions.
In Book view Italics is `<span style="font-style: italic;">  </span>`
In Code view Italics is `<i> </i>`

Edit: This also happens with bold, underline, delete, sub, sup
I suspect it's deliberate. May I suggest that it be a preference?

**Comment by kevinhendricks** [comment]
Yes, this is due to a bug in Qt's WebKit which BookView uses that tried to use deprecated and obsolete tags.  The only solution to generate legal code in BookView is to use inline styles.  CodeView does not have this limitation.

If you actually care about the exact code used, you should never edit in BookView.  BookView has been deprecated and will go away after the next release.

Closing as both sets of code are legal.
