### ISSUE TITLE
EPUBCheck complains about epub file edited by Sigil

### ISSUE THREAD

**Issue by cges30901** [Sigil-Ebook/Sigil#447]
EPUBCheck complains about epub file edited by Sigil. I am using Sigil 0.9.16 and EPUBCheck 4.2.2 on Manjaro Linux. Here is the output of EPUBCheck:
```
Validating using EPUB version 3.2 rules.
ERROR(RSC-005): /home/bill/untitled.epub/OEBPS/content.opf(2,92): Error while parsing file: element "package" not allowed anywhere; expected element "opf:package"
ERROR(RSC-005): /home/bill/untitled.epub/OEBPS/content.opf(4,93): Error while parsing file: element "package" not allowed anywhere; expected element "opf:package"
ERROR(RSC-005): /home/bill/untitled.epub/OEBPS/content.opf(5,34): Error while parsing file: element "package" not allowed anywhere; expected element "opf:package"
ERROR(RSC-005): /home/bill/untitled.epub/OEBPS/content.opf(6,36): Error while parsing file: element "package" not allowed anywhere; expected element "opf:package"
FATAL(OPF-019): /home/bill/untitled.epub/OEBPS/content.opf(-1,-1): Spine tag was not found in the OPF file.
Spine element not found within package root document OEBPS/content.opf

Check finished with errors
Messages: 1 fatal / 4 errors / 0 warnings / 0 infos

EPUBCheck completed
```

Here is the epub file: https://drive.google.com/open?id=1n7AzVXNtmACvRdQZOqVEGnqmwUCQzaqc

Steps to reproduce:

1. Open Sigil. A new empty epub will be opened automatically
2. Save the epub file
3. Open the epub file, and save it again
4. check with EPUBCheck

**Comment by cges30901** [comment]
EPUBCheck no longer complains after I change `xmlns:opf` to `xmlns` in line 2 in `content.opf`. For epub with ncx, I also need to change `xmlns:=` to `xmlns=` in ncx.

**Comment by dougmassay** [comment]
This a bug that was caught and fixed in the master branch. https://github.com/Sigil-Ebook/Sigil/wiki/Linux-Notes#lxml-440

The latest version of the lxml python module (4.4.0+) is incompatible with Sigil's sigil_bs4 python module.

Arch Linux has backported the fix for it's latest Sigil package. Other workarounds (until Sigil 0.9.17 is released--which we hope is soon) is to roll back to version 4.3.x of lxml, or build Sigil yourself from the latest master branch which contains the fix to work with all versions of lxml.

**Comment by cges30901** [comment]
Thank you! Sorry that I didn't notice that this is already fixed. Closing this issue.

**Comment by dougmassay** [comment]
No problem. I added a note above that you can also simply patch the python file in the Sigil installation.
