### ISSUE TITLE
Open with PageEdit: files out of sync with internal state

### ISSUE THREAD

**Issue by eli-schwartz** [Sigil-Ebook/Sigil#452]
Looking at the new "open an OPF in PageEdit" feature, if I extract a book into a directory, and then  open its OPF using PageEdit I can browse through every page, with CSS and images referenced and stuff.

If I try to open the exact same content.opf using sigil's Open with external editor, I still see all the different xhtml files, but images and stuff are broken.

Inspecting the resources shows that Sigil's temporary working directory /tmp/Sigil-GUCjgm contains reorganized files (moving "xhtml" to "Text", "styles" to "Styles", "images" to "Images") and the content.opf has been updated, but the individual xhtml files have *not* been updated. Saving the book to disk will also write out those changes to the temporary working copy and make opening with PageEdit work.

This is somewhat surprising behavior because the only thing that was "edited" was Sigil's initial "let us reorganize all the files as soon as the book is opened" step. And it is partially, but not fully, updating the on-disk representation of Sigil's editor state... which PageEdit depends on. Possibly the only thing that is updated on-disk is the folder reorganization, as well as the content.opf when Open With is used?

**Comment by kevinhendricks** [comment]
Yes, this is expected behaviour.  The Open-With functionality in Sigiul when used on the OPF file will assume you want to use a pure xml editor to edit the OPF.

If you instead open an epub in Sigil and bring the content.opf file tab to the front, and then hit the new open External Editor icon (the pencil), Sigil will properly save each file to disk and set a file watcher on each xhtml file before launching PageEdit and passing it a copy fo the OPF, which PageEdit will pare to get the list of xhtml files in spine order you might want to edit or proof.

Inside Sigil, to speed up initial loading and general editing,  xhtml files are often loaded into QTextDocument via its resource and cached there.  No file is actually written to disk until they are required to be.  So when editing in CodeView, the changes are only kept in the QTextDocument and its Resource cache. 

When launching a plugin, or doing reports, all changes are flushed to disk before the plugin is launched or report generated.  When using "open-with" in Sigil, only that file is flushed to disk and its file watcher enabled.    But when use the Open External XTML Editor with the OPF Tab present, all xhtml files are flushed to disk , and file watchers are enabled on them.

This is expected behaviour.  So instead of using Sigil's "open-with" on the OPF (which is basically saying I want an external xml editor to work on the content.opf file itself), use the newer External XHTML Editor icon (see Sigil Prefs to set the External XHTML Editor to PageEdit) when the OPF tab is front and centre, and you will see that PageEdit can and does see everything.

**Comment by eli-schwartz** [comment]
Hmm, okay. Yeah, that route works as expected. Thanks for clarifying.

I cannot think of a good way to make this do what the user "meant", so I cannot fault Sigil's current behavior. Feel free to close this issue.

**Comment by kevinhendricks** [comment]
FWIW, since there is no communication channel between Sigil and PageEdit (PageEdit is started in a detached state), PageEdit has no way of knowing if the OPF file it was sent was from the External XHTML Editor icon or the "open with" menu.  I will look into seeing if I can modify Sigil to reject choosing PageEdit via "open with" on a content OPF file.

**Comment by eli-schwartz** [comment]
Yeah, that seems like it would be helpful for such confusion. Thanks! I guess I will keep an eye on the future.

**Comment by kevinhendricks** [comment]
FWIW, If we can not easily prevent PageEdit from being assigned as an "open with" for the OPF, we can certainly change the code to force write everything to disk and assign file watchers any time "open-with" editing of an OPF is done.  It can not hurt any xml editor being used to edit the OPF file, and would then work as a replacement for the open External Xhtml editor icon approach.  

That might actually be the best idea if any confusion exists.  Also creating a PageEdit User Guide would also help.
