### ISSUE TITLE
Sigil does not launch anymore

### ISSUE THREAD

**Issue by cptmarc** [Sigil-Ebook/Sigil#465]
Since I installed WIN64 0.9.18 version of Sigil, it does not launch. I uninstalled and installed again. No success. I installed a prior version but with the same problem.

**Comment by dougmassay** [comment]
The issues database is not for general user-support. It is for reporting coding issues/bugs. Please use the [Sigil User forum at MobileRead](https://www.mobileread.com/forums/forumdisplay.php?f=203) to ask for help with an installation.

Off-hand, I'd say your Sigil.ini file is corrupt. Please see: the [note in the Sigil Wiki](https://github.com/Sigil-Ebook/Sigil/wiki#if-youre-here-because) that applies to it. If you still can't get Sigil to launch after that, head to the Sigil User Forums for more help. Thanks.
