### ISSUE TITLE
Can't Insert Images

### ISSUE THREAD

**Issue by hkimmick23** [Sigil-Ebook/Sigil#475]
Every time I try insert an image in my epub file, I get an error message. I get the message every time, even when I try jpeg, png, or gif.
![Sigil Error](https://user-images.githubusercontent.com/58831987/71303613-712c5580-2378-11ea-8c80-96083ba3fbef.png)

**Comment by BeckyDTP** [comment]
Unfortunately, I confirm this.
The file is added to the "Images" folder (or equivalent in its custom layout), but no code is inserted. You have to do it again by selecting an image from the list.

**Comment by kevinhendricks** [comment]
I am confused.  Typically I add any image files I want to Sigil using "Add Existing ..." then insert links to them using the "Insert Images".

Are they going to "Insert Images" and then using "From Disk" and selecting an image file that is not part of Sigil?

**Comment by BeckyDTP** [comment]
> Are they going to "Insert Images" and then using "From Disk" and selecting an image file that is not part of Sigil?

Yes. It always worked.
You could choose an image already existing in the EPUB file or a completely new one from disk and immediately insert the code <img ...>

**Comment by kevinhendricks** [comment]
Okay, I am on it.  I just never actually tested that combination as I never use it personally.

**Comment by kevinhendricks** [comment]
This has now been fixed in Sigil master.   The fix will appear in the next release (probably shortly after the holidays).

In the meanwhile, to workaround this issue  please use the "Add Existing .." menu first to add any external image files to the epub, and then use Insert Image and choose the already  added image.  This will prevent the error message temporarily until this fix is released.

Thank you for your bug report!

**Comment by kevinhendricks** [comment]
Closing this issue since ti is fixed in master.
