### ISSUE TITLE
Win32-Build

### ISSUE THREAD

**Issue by ionum** [Sigil-Ebook/Sigil#488]
Since Sigil 0.9.13 or 0.914, 32-bit builds are no more available. Any reasons for that? I still have 32-bit Windows runnig and would appreciate a 32-bit build.

BTW: Great piece of software! In my opinion best ePUB-editor ...

**Comment by dougmassay** [comment]
The reason is mainly because I don't have the time to maintain patched builds of Qt/QtWebEngine for both 64 bit and 32 bit. Not to mention maintaining two build environments and making sure they stay in sync.

It's still perfectly possible to build 32-versions of Sigil's source, though. If someone wanted to take up the cause to make 32-bit builds available, I wouldn't mind. Though I believe 32-bit versions of Windows (w7 and up) are getting pretty rare these days.
