### ISSUE TITLE
An interesting issue related to the interface language

### ISSUE THREAD

**Issue by BeckyDTP** [Sigil-Ebook/Sigil#492]
Today during the translation tests, I wanted to do an additional test on a "clean" environment, i.e. without .ini files.
What happened?
On my system (Windows 10 Professional Polish) Sigil with Polish translation started right after the start. I thought "Wow!", but I look at Preferences, and still "English".
Interestingly, until you open "Preferences" and `ui_language` not saved to the file sigil.ini - the Polish (and probably also different) interface starts every time.

Interesting, is not it?

This is not a significant problem, so you don't have to stop preparing for release.

**Comment by kevinhendricks** [comment]
If no ini file exists SettingsStore will return the equivalent of the following:

QLocale::system().name()

So what exact string is that returning on your system?  

I am betting it is returning pl_PL which does not actually exist in the Misc/Language.cpp tables which as far as I can tell only has this entry:

        "pl"    << tr("Polish") <<

Because Polish does not have variants spoken in different countries or English.

So I guess the best solution here would be to try the initial value first and if it can not be found, then if a "-" or "_" exists in the language code, try again with just the string before the "-" or "_".

I will give that a try.

**Comment by BeckyDTP** [comment]
I confirm.
I checked it through qDebug.
`QLocale::system().name()` returns `pl_PL` on my system.

**Comment by kevinhendricks** [comment]
Okay, I think my latest commit should have now fixed this in master.
Please give it a try.

**Comment by dougmassay** [comment]
Could it be that just the routine that populates the preference combo box is defaulting to English when there's no ini?

As described, it sounds like everything is basically working properly (the interface is displaying Polish). It's just that when the preference dialog is opened (before there's an ini) English is being loaded into the combobox.

**Comment by kevinhendricks** [comment]
No, it tries to look up whatever settings.uiLanguage() returns after replacing underscores with hyphens) in a LanguageMap stored in Misc/Language.cpp.  Since no pl-PL exists in that Language table, it then gets set to English.  

The code should now (after my commit) split the language code at the hyphen and try the piece at the front (in this case "pl") and so it should now handle things properly I hope.

**Comment by kevinhendricks** [comment]
By the way, no ini file will be written until some setting is touched that deviates from the defaults (which makes sense!) at least to me.

**Comment by BeckyDTP** [comment]
Everything works for me.
Sigil detected the Polish language from system correctly and the language was right in the preferences.

**Comment by kevinhendricks** [comment]
Sounds good.  Closing this.
