### ISSUE TITLE
Add Existing Files uses non-native dialog on macOS; folder aliases treated as files

### ISSUE THREAD

**Issue by pfahlstrom** [Sigil-Ebook/Sigil#529]
My assumption is that the Add Existing Files dialog not being the native macOS dialog as of version 1.2.0 (and perhaps earlier?) is a design choice. However, this makes it quite difficult to navigate around when the dialog box starts at the hard drive or user root directory. My working ebooks folder is several levels deep on Dropbox. 

So I tried to find an accommodation and placed a Finder alias to my working folder in my user folder. But Sigil does not see this alias as a link to a folder; instead it sees it as a file. When I double-clicked on the alias, it added a file (a few bytes large) to the ebook instead of navigating there in the dialog box.

I am sure that Sigil used to use the native macOS dialog box for things like this. Can this behavior be reverted on macOS?

**Comment by kevinhendricks** [comment]
No due to a qt bug, using a native file dialog on macOS 10.14 and 10.15 can leave behind zombie dialogs after they are closed that can not be interacted with and can not be dismissed until the entire application exits.  I have repeatedly tried to track this bug down to which specific versions on macOS and Qt have this issue to no avail.  I only solution was to use Qt file dialogs not the native ones where ever I could.

Sorry but until Apple and Qt get their act together and stop creating zombie modal file dialogs, I had no choice.

That said, I it should work just fine with unix symlinks.  Apple OS Aliases are not quite the same thing.  Try using a symbolic link  (man ln -s) in Terminal.app to point at your destination folder and the qt dialogs should just work.

**Comment by dougmassay** [comment]
I was thinking there was another issue involved with using native file dialogs on Mac. Didn't they prevent users from being able to select plugin zip files for installation? It just browsed right into the zip archive instead of being able to select it. Or was that something else?

**Comment by kevinhendricks** [comment]
That was selecting apps with “open with”.  That is still native as the qt non-native dialogue did not know .app files were bundles ie a folder.

That is the only place where we still use native file dialogs on macOS.

**Comment by dougmassay** [comment]
Ahhh... I knew it something like that. I forgot it was .app files that were problematic with Open With and not .zip files. Thanks!

**Comment by kevinhendricks** [comment]
I will close this as it is really not a Sigil issue exactly.  The qt non-native file dialog groks true symlinks just fine so you have a path forward.  I will look into supporting Apple Finder aliases as well.

**Comment by pfahlstrom** [comment]
Thanks. I did put a symlink and it's working perfectly.
