### ISSUE TITLE
Files starting with #

### ISSUE THREAD

**Issue by WS64** [Sigil-Ebook/Sigil#531]
Hi, I was using Sigil 0.9.18 until yesterday, updated to the new version (1.2), and found a bug which makes 1.2 unusable for me.

I checked other versions, this bug exists since 0.9.991.

To check it, create a new and empty epub,
You have by default one text called "Section0001.xhtml"
Add a blank text (=> Section0002.xhtml)
Rename the new text to #Section0002.xhtml
You will notice immediately that this text does not stay at its (second) position but jumps up to the top position.
Save the file, and reopen it.
Sigil will complain that files exists that are not listed in the manifest, and after opening #Section0002.xhtml is gone.

The really bad thing here is that I openend a file that had some text starting with an #, creatd with 0.9.18.
1.20 opened it without problems. All the #-texts showed up. But renaming one of those puts all the #-ones on top, and after a save they were all gone. No warning while  saving the file, only when trying to reopen it (in other words, when it was too late)

I'm back to 0.9.18, which does not have any isses with #-texts, 
Oh, all on Win64.

One more thing, not a bug, but I wondered about this one all the time.
I have stored many own searches.
When I use one of them on a large text with "count all" I usually get pretty quick a result. Assume it does not find anything, then count all tells me "0 results" let's say in half a second. But when I do "replace all" it takes 10 seconds to find out that it does not find anything. Why can't "replace all" be as fast as "count all" when it does not find anything to replace?

**Comment by kevinhendricks** [comment]
Given a fragment in a url begins with the # sign, starting any filename that may be the target of a link (or even using a # sign anyplace in the filename) is a sure recipe for disaster.

I would strongly recommend against it.

**Comment by kevinhendricks** [comment]
That said, I will look into hand encoding the # to %23 since it appears the Qt's urlencode of the character "#"  itself does NOT return %23 as it is assumed to be the fragment separator.

Given this bug in Qt/Chrome's handling of "#" in filenames, means use it at your own risk.  If you are actually trying to reach the largest epub reader installed base, I would stay completely away from it in filenames that may be uri targets as mentioned earlier.

**Comment by WS64** [comment]
I would have stayed awway from it if I had known it would be problematic. But Sigil never complained against this character (it does with others).
The big problem is the behaviour with files that already have files with that name...

Btw, # is not a problematic character in Windows at all.

**Comment by kevinhendricks** [comment]
No, it is problematic for linking on all platforms.   Given the # in the filename is not properly url encoded, it is being interpreted as the fragment separator (ie. what you put after a filename and before the target id) and is considered a reserved delimiter in html uri (ie links) including internal Sigil book paths which are links.

**Comment by kevinhendricks** [comment]
The reason files appear to be lost is that you out the # char first, effectively truncating the file name to be a null string (everything after it was considered a fragment id).  Repeating this for multiple files means you removed the filename from multiple files of the same kind effectively overwriting them.

I have actually never seen any epub file anyplace that included the # char as part of the filename.  I will try to modify Sigil's rename functions to no longer allow its use in a filename.

You may want to check out this article about uris and stay away from anything in the reserved or delimiter groups:

https://tools.ietf.org/html/rfc3986#page-11

**Comment by kevinhendricks** [comment]
I have now modified Sigil's Rename and Regular Expression Rename in BookBrowser to not allow use of any of the officially reserved uri-delimiter characters as part of a filename to ensure maximum compatibility across epub readers.

The following characters will not be allowed in new filenames as they are delimiter characters for any link (url) created to that file:  : / ? # [ ] \@

In addition, using any of the following characters in a filename is probably not a good idea - but should be properly handled by Qt's and Pythons url encode, and url decode routines but may not be properly handled by reading devices:

! $ & ' " ) ( * + , ; = 

and of course the windows file path separator \

This will be a stop-gap bug filler for the next release, as tracking down where and how "#" signs are not being handled properly in url encoding and decoding routines in either Qt or Python will take some time and be quite messy.

Thank you for your bug report!

I will be leaving this bug report open to remind me to find and fix the Qt and Python urlencode / urldecode related source code in this regard.

**Comment by kevinhendricks** [comment]
Notes to self:

Note:  UrlEncode on paths should be called **BEFORE** adding any fragment identifier and it  should %23  encode # chars in the path! 

Only after encoding should the # and the fragment be added.

Note: you need to worry about the reverse case as well 

Since a fully decoded path with a # sign will make detection of a fragment impossible.

You need to handle this in Utility.cpp and in python3 hrefutils then make sure all calls to either are in the proper order.  

Once decoded, fragment and path components must be kept separate!  So use std::tuples, std::pairs, or QStringLists to pass them around together but separate.  You can no longer just use one fully decoded QString.

This will take a serious rewrite of both Sigil's Cpp and python3 href/ link updating routines.

**Comment by WS64** [comment]
Thx!

**Comment by kevinhendricks** [comment]
Pushed a set of fixes for this to master.  
Thank you for your bug report.
Closing this issue
