### ISSUE TITLE
"DLL load failed" when launched from Calibre

### ISSUE THREAD

**Issue by WS64** [Sigil-Ebook/Sigil#532]
I'm using plugins based on https://github.com/Kennyl/Sigil-Ebook-Plugins/tree/master/prompt-user-example
When I open Sigil and start this plugin it works fine.
When I open Calibre and double click on an ebook it opens Sigil with that book. But the above mentioned plugin does not run anymore:

Status: failed

Traceback (most recent call last):
  File "C:\Program Files\Sigil\plugin_launchers\python\launcher.py", line 135, in launch
    target_script = __import__(script_module)
  File "C:\Users\WS64\AppData\Local\sigil-ebook\sigil\plugins\prompt-user-example\plugin.py", line 6, in <module>
    from PyQt5.QtWidgets import (QWidget, QPushButton, QLineEdit, QLabel,
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.
Error: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.

"Die angegebene Prozedur wurde nicht gefunden." translates to "The specified procedure was not found."
What is the difference here between starting Sigil directly and starting Sigil through Calibre? When I double click on an epub in Windows' file explorer it also launches Sigil fine with the plugin working, only when started through Calibre the QtWidgets cannot be found.

**Comment by dougmassay** [comment]
The difference is that one way involves using a Python/PyQt5 app to launch a C++/Qt5 app that's in turn launching a Python interpreter in order to run a PyQt5-based plugin. Depending on whether you're using Sigil's bundled Python to run the plugin or not, you're potentially mixing 3 different Python/PyQt5 environments/versions (calibre, sigil-embedded, sigil-plugin-interpreter).

We typically only support launching Sigil with Calibre's inherent "Open With" feature (using Sigil's bundled Python for plugins). And only then when the latest version of both are being used.

**Comment by WS64** [comment]
What is Calibre's "open with" feature? I have set up Calibre (years ago, cannot find right now where exactly this setting is) to open Sigil when I double click a book. Is there anything in Calibre or in Sigil that I can change to prevent this behaviour so that Sigil always uses its own environment and not Calibres?
I have to admit that my Calibre is not the latest version (I am afraid that some plugns might stop working if I update)

**Comment by dougmassay** [comment]
I'm afraid I'm not really comfortable using Sigil's issue database to discuss calibre configuration/usage matters. It's better suited for either program's user forums at Mobileread.com.

**Comment by WS64** [comment]
Okay, than let me put this the other way...
I have unchecked "Use bundled Python".
But now Sigil does not accept any path to the python3.dll I give it...

**Comment by dougmassay** [comment]
That's because the path it needs is the path to a python executable, not a dll. Besides, using a system version of Python for plugins means that Sigil is at the mercy of how that system version of python is configured. I always recommend using the bundled python (leave the box checked) for maximum compatibility. But again ... this is not the place to ask for configuration/usage advice. That's what the user forums are for.
