### ISSUE TITLE
Unable to undo text changes made prior to saving a document

### ISSUE THREAD

**Issue by a-p-** [Sigil-Ebook/Sigil#540]
This is with:

* Sigil 1.3.0
* Qt 5.12.9
* macOS 10.15.6

If the text of a document is changed, and then the document is saved, the change made prior to the save can't be undone.

Steps to reproduce:

1. Create a new ePub2 document.
2. Save it.
3. Insert a line of text within the body element of the default Section0001.xhtml document.
4. Select the line of text that was just added, and delete it.
5. Undo the change. Notice that the deleted text is restored.
6. Select that line of text again, and delete it again.
7. Save the document.
8. Try to undo the change (i.e., restore the text that was just deleted prior to saving). Notice that the deleted text isn't restored.

I think it should still be possible to undo changes that happened prior to the document being saved.

**Comment by kevinhendricks** [comment]
This is not a bug.  It is expected behaviour.  Saving a file clears the undo buffer.

If you need to revert to things before a save, simply create a Checkpoint which much more extensive than Sigil undo capability.

**Comment by a-p-** [comment]
Is there a Sigil-specific reason why it intentionally behaves that way?

Other editors (such as PyCharm, Atom, VS Code, LibreOffice, TextEdit) seem to allow changes made just prior to a save to be undone right afterwards.

This unexpected behaviour of Sigil has caused me minor data loss during routine editing.

For example, several times I've made a minor edit (say, removing a paragraph), saved, and then soon after wanted to try a different approach instead.

While other editors easily allow the removed text to be restored with an undo, Sigil's editor unfortunately does not.

Having to use a checkpoint seems excessive for something that other editors make so easy to do.

I think it'd be good if this behavior were configurable, so Sigil could optionally behave like other editors do.

**Comment by dougmassay** [comment]
It's not "unexpected behavior" in my opinion. Regardless of the offered examples where this behavior is allowed, this is the first such complaint we've had about it from a user in years-worth of releases. So how unexpected can it be?

The examples you give are editors that, regardless of how many files they allow you to have open at once, don't require cascading changes an updates between the files in question. Sigil is not a simple file editor. It's an EPUB editor. As such, a "simple" change in one file can cause updates to other which must also be accounted for in the Undo process. This complication is precisly why checkpoints and vcs repos are the better choice for tracking, diffing, and `restoring (undoing) changes in a collection of interconnected files in an archive. It's precisely why we implemented the Sigil checkpointing feature in the first place.

Comparing Sigil to simple file editors RE feature expectations is a mistake.

**Comment by kevinhendricks** [comment]
This is exactly correct.  Simply reloading the xhtml text into the QPlainTextEdit after performing any operation on it (such as mending, splitting, updating, saving, parsing, loading, etc) clears the Qt undo buffer.  This is not something we can control.  Given the need for things beyond simple line editing in Sigil's CodeView (such as syncing to Preview, checking for well-formed, spellchecking, etc,) can and will grab the plaintext from the widget, process it in some way, and load it back, putting the cursor back where it was.  This kills the internal Qt undo/redo buffers.    This has long been the behaviour of Sigil.   So as explained earlier, this is not a bug but expected behaviour.  Use SaveAs or Checkpoints as needed or even just copying and pasting to the system clipboard.
