### ISSUE TITLE
Source highlighting from preview.

### ISSUE THREAD

**Issue by a4a4** [Sigil-Ebook/Sigil#564]
When clicking on text in the Preview View, the yellow line in the Source View moves to the corresponding line.
However, when the following line is missing from the HTML-file the yellow line highlights the wrong paragraph.
``` 
<?xml version="1.0" encoding="utf-8"?>
```
In one epub (with htm-files) the following had to be added to make the highlighting work properly, but it didn't matter in another epub (with xhtml-files).
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
```
The "Well-formed epub check" didn't find it a problem when either of those lines were missing. But the "mend all HTML-files" tool did fix it.
In preferences, general settings, I have the "mend not well formed HTML-files" option enabled on open and close.

**Comment by kevinhendricks** [comment]
Well formed is just to check if parseable, not correctness. 

Passing the well-formed check just means that automated processing of the xhtml is possible.

Just run Sigil's Mend (on a file by file basis or on the entire book) and it will properly add the proper xml declaration and proper DOCTYPE (they differ for epub2 and epub3).

I set my Sigil Prefs to run mend on startup, but it is easy to run it at any time.

If you want to check an epub for correctness, then I recommend the epubcheck plugin.  It is often updated to the very latest spec.

Closing this as not an issue, but expected behaviour given poor input.

**Comment by kevinhendricks** [comment]
FWIW, Mend on start-up only touches things that fail the non-well formed check.  When invoked at any other time is will happily mend things (even more minor things) no matter if well-formed or not.

This was done to give advanced users more control of when and how mending is done.

**Comment by kevinhendricks** [comment]
FYI, the next version of Sigil extends the well-formed check when loading an epub to include checks for xml header, DOCTYPE, and the existence of a single "html" tag, a single "head" tag, and a single "body" tag in each xhtml file loaded.

If you have Mend On Open set in Sigil preferences, this will now trigger the warning and request to automatically fix the files preventing the issue you posted about above.

Of course you can still decide to not fix on load and later run Reformat Mend on all files if you would like to manually fix things.
