### ISSUE TITLE
Indesign > ePub

### ISSUE THREAD

**Issue by jporaca** [Sigil-Ebook/Sigil#571]
This EPUB has HTML files that are not well formed or are missing a DOCTYPE,..... This is an old and tested epub file and works properly on any device but when I try to open it with this new Sigil update, this message suddenly pops up, Is this normal?

![issue](https://user-images.githubusercontent.com/67301456/99480310-cd399880-2992-11eb-80f1-9f25d16c96cf.png)

**Comment by kevinhendricks** [comment]
Yes. That is completely normal if your xhtml files are missing the required DOCTYPE at the start of the file.    Epubcheck does not detect this condition (they have an accepted bug report about it).
The epub spec clearly states it is required.
This was quietly auto fixed by Sigil before Sigil 1.0 but that auto fix got lost during Sigil 1.0-1.3.  Sigil 1.4.1 now checks for missing DOCTYPE during its Well-Formed checks on load.

Simply allow Sigil to auto fix this issue or use Sigil's Mend tool.  Alternatively, you can manually efit each xhtml file and manually add the correct DOCTYPE (they differ between epub3 and epub2).

**Comment by kevinhendricks** [comment]
For more info see our Mobileread  Sigil User support site.  Specifically these posts:

https://www.mobileread.com/forums/showpost.php?p=4058689&postcount=37

https://www.mobileread.com/forums/showpost.php?p=4058701&postcount=42

https://www.mobileread.com/forums/showpost.php?p=4058704&postcount=43
