### ISSUE TITLE
Stop Auto Checking

### ISSUE THREAD

**Issue by budikesuma** [Sigil-Ebook/Sigil#577]
Dear Devs,
Please <b>Stop Automatic Checking</b> <i>(I prefer Manual Checking)</i>, which results in the app freezing for hours while checking large ePub files just because I am typing a single letter.  It's a waste of time and hard work.  So I had no choice but close it forcibly.
Thanks in advance.

**Comment by dougmassay** [comment]
You are the very first person to report that length of freezing/lockup when editing an epub of any size. But you've not given us a single piece of information that we can use to attempt to recreate/investigate your issue. What OS? What version of Sigil? How large are your "large epub files"?

It's not possible for us to stop "automatic checking" AND update the Preview Window at the same time. So if you have no need of seeing your edits immediately reflected in the Preview window, then close the Preview window while editing.

Other things that can slow Sigil down considerably are massive html files that contain very few line breaks. Large epubs with many smaller html files will always work much, much better than the same sized epub with a single massive html file.

Even so... "freezing for hours" is unheard of. I can't duplicate that with the largest of single-html-file epubs I have at my disposal. So unless you're talking full-set-of-encyclopedias-in-a-single-html-file big, then I suspect something else is going on. But without  enough info to help us recreate the issue, there's very little we can do.

**Comment by kevinhendricks** [comment]
As DiapDealer says this bug report is basically worthless as it stands.

A few words of advice:

- a single very large xhtml will break most of the older epub readers since they had limits of 200k bytes in size.  Use Find and Replace to insert Sigil Split markers at appropriate points and then run Split at Markers.

- using files that have had all linefeeds removed is never a good idea in a line oriented editor like Sigil's.  Try running Mend and Prettify after first load to create a proper line based readable structure.
This will fix the missing linefeeds.

- single xhtml files over 2mb in size will cause QtWebEngine to abort.   That limitation will be lifted in the next release.

- Turn off Preview as Preview constantly reloads your epub in a browser window to show you what you gave typed.  Preview works well for even large files on my machine so this could be something specific to your specific xhtml file structure.

And please remember to file a useful bug report, since you are giving us no information to go on here at all.

**Comment by kevinhendricks** [comment]
Also, without additional information added soon or better yet a sample epub that causes the problems, I will close this issue since I am unable to recreate the problems you are seeing with any reasonably structured xhtml files.

**Comment by kevinhendricks** [comment]
Closing this as "unable to recreate your issue".  Feel free to post a sample epub along with the additional information requested and I will reopen this.
