### ISSUE TITLE
Sigil 0.9.14

### ISSUE THREAD

**Issue by Fleuralie** [Sigil-Ebook/Sigil#581]
Hello community

I'm new in code and I'm also a new writter ( text book ;-) ) I would like to transform my paper book in epub with Sigil. For now I have it in my Windows 7, but soon I want to go on Linux xubuntu.  My question is how can I download the Sigil version 0.9.14 (I like this one because it have the BookView) and install in the Linux xubuntu.  (I've try to read about it but I still not understanding how). Please help me.

Thanks all for you help

**Comment by eli-schwartz** [comment]
Linux binaries are not provided, since different distros do different things. You'll need to compile Sigil yourself, from the source code.

Why not just use PageEdit instead of BookView?

**Comment by dougmassay** [comment]
There are instructions in the Docs folder for how to build Sigil on Linux. That's the most help I have the time to offer, I'm afraid. There are tutorials aplenty on the internet for learning how to compile programs from source code in general. If you run into an error that you believe to be because of a bug in Sigil's source, feel free to reopen this issue at that time.
