### ISSUE TITLE
Software needs to be updated

### ISSUE THREAD

**Issue by bbsamazon** [Sigil-Ebook/Sigil#588]
It looks like your latest version of the Sigil for Mac needs to be updated to conform to Big Sur OS. I'm running a late 2013 iMac.
<img width="265" alt="Screen Shot 2021-02-15 at 12 55 41 AM" src="https://user-images.githubusercontent.com/6842694/107924924-93901380-6f28-11eb-9b62-73247deec7d0.png">

**Comment by kevinhendricks** [comment]
It runs just fine on Big Sur.  We have not submitted our open source software for Apple to "notarize" and we currently have no plans to do so.  I already pay over $100 annually for a digital signature because Apple required it with no relief from Apple for Sigil being completely free and me volunteering my time for over that last 5 years to help develop it).  More importantly, Apple has no right to final say as to whether users can use OpenSource software that is *NOT* distributed through their App store.

Aside from that  ... for Big Sur and Catalina, simply right click on the Sigil icon and select "open".  MacOS will then warn you.  Then right click on the Sigil icon the second time and select "open" again and Sigil will launch, my digital signature will be verified as it has for over 5 years, and run just fine.

If users let Apple completely determine what runs on their own desktop machine, they will be completely in a walled garden and subject to Apple's whims.  I will not aide or abet Apple in doing this and neither should anyone else. They are using FUD (fear uncertainty and doubt) just like Microsoft has long been accused of to try to take complete control of the desktop.  If that is what you want, then stay completely away from OpenSource software.

Hope this explains how to both run Sigil just fine under Big Sir and Catalina and why "notarization" will not be supported by Sigil as long as I am the one developing for macOS.  The day macOS desktops stops running what I tell it to on my own machine, will be the day I abandon macOS and return to Linux.
