### ISSUE TITLE
just to know why wysiwyg doesn't exist anymore

### ISSUE THREAD

**Issue by jean-raphael** [Sigil-Ebook/Sigil#589]
for me the wysiwyg was indispensable. I have a 700 pages book to edit I just can't have fun managing xml from a conversion from libreoffice wirter.

Not to mention the fact that making a book is extremely inaccessible without wysiwyg, it's a shame.
In fact it was the only thing that made me use sigil.
especially since it worked pretty well

I'll have to find something else or use old versions or forks of sigil.

**Comment by dougmassay** [comment]
You're perfectly welcome to use PageEdit Or any older version of Sigil that suits your needs. But there will be no further discussion of the decision to remove Book View and WYSIWYG editing from Sigil. Any future issues of this nature will be closed without comment. We've taken nothing from anybody. Every version of Sigil is still available fir download. Use them in good health,

**Comment by dougmassay** [comment]
https://github.com/Sigil-Ebook/Sigil/wiki#yes-book-view-is-really-gone

**Comment by jean-raphael** [comment]
Thank you very much for your quick answers and sorry to bring this up again.
In the meantime, I don't know why this decision was made, but it doesn't matter.
It's just that for you, if you look at the sigil tutorials on youtube for example, they all stopped at the wysiwyg version, and integrating pageEdit by default would be in my opinion a good idea (or more guiding the user to pageEdit).
Because if I finally found pageEdit, there's no indication that it's there and it took me a long time to find it.

Especially since next to the software as calibrated the only interest of sigil is the wysiwyg.

Translated with www.DeepL.com/Translator (free version)

**Comment by kevinhendricks** [comment]
This was all explained repeatedly literally years ago.  

As explained in the README shown on this site, the place for user questions is our Mobileread Sigil Users Forum, not in our developer issues.

https://www.mobileread.com/forums/

There you will find the Sigil forum.  Posted at the top is a link related to this topic:

https://www.mobileread.com/forums/showthread.php?t=321081

Including a detailed set of instructions on installing PageEdit.

As to why it was removed ...  WYSIWYG editing is live HTML (not XHTML)  editing internal to the browser engine (Chrome in this case) and not under our control.  It can and often does generate code that appears to work but is NOT valid xhtml required by epub and will not pass flightcrew (now a plugin so you may want to install that) or epubcheck (also a plugin for Sigil) that most publishers require.  

The illegal xhtml code generated by the old BookView was a constant source of pain that consumed much energy and took away from Sigil  development itself.  Since it is internal to the browser engine we can not fix or change how it operates.

Therefore we removed BookView and replaced it with a separate tool for those who still want some of that functionality that may be still useful for final proofing and very minor edits.

Using CodeView and Preview mode will allow epub developers to see the impact of their code changes immediately without the need to toggle back and forth.  That way correct xhtml can be generated and epubcheck detected errors can be easily tracked down and fixed.  These were determined to be more important for professional epub developers.  Shedding BookView has freed up enough developer time to add many many new features to Sigil.

**Comment by eli-schwartz** [comment]
Can we just have this bug locked and point people to the forums, so that anyone interested in discussing the whys and wherefores can do so there?

I'm sure it cannot be fun for you to put thought and effort into re-explaining all of this rather than using pre-canned FAQ answers, so maybe also just point to the FAQ and revise the FAQ any time a *forum* discussion inspires you to further elaborate on your existing explanation.

**Comment by dougmassay** [comment]
That's why I'm just posting this link to the wiki in response to this subject from now on.

https://github.com/Sigil-Ebook/Sigil/wiki#yes-book-view-is-really-gone

I've made sure the wiki post has links to MobileRead, PageEdit, the last release of Sigil with Book View, and when the decision  to remove it was made. I'll happily add anything to the first post of the wiki that anyone thinks is missing in that regard

The reasons why we removed Book View are always going to be insufficient and immaterial to the people who want to complain about it being gone, so I'm not going to waste time trying to explain it any more. I'm posting the wiki link and closing the thread.

**Comment by jpmorgan58** [comment]
FWIW, the explanation that BookView was based on calling into the browser engine didn’t come through in your previous explanations. For me, that totally cleared up the reason for removing it. Would you be open to further development on PageEdit, if someone wanted to make it more useable for their purposes?

 - John

**Comment by eli-schwartz** [comment]
(I would actually go one step further and respond with "this is a discussion / user support query rather than a bug report. Please open a forum thread at LINK. Closing and locking to prevent further off topic discussion.")

**Comment by kevinhendricks** [comment]
Pull Requests to the PageEdit GitHub repo will always be considered.  Any discussion of PageEdit features should be done in Sigil’s User Forum on Mobileread.

**Comment by kevinhendricks** [comment]
Our MR sticky related to this topic is very thin on “why” and although some people will never agree others will be curious.  So I will copy and paste the “why” from this thread into our sticky on MR.  In the future as DiapDealer said, we will just close any future issues with a link to that wiki and sticky post without further comment.

**Comment by dougmassay** [comment]
I'll add a link to the MR sticky thread in the wiki post.

**Comment by kevinhendricks** [comment]
And I copid the "why" from here edited for clarity to DiapDealer's first sticky post since that thread was already closed.  Feel free to modify it as you see fit.

That should at least help deflect traffic to MR and away from here.

**Comment by matkoniecz** [comment]
Maybe add to https://github.com/Sigil-Ebook/Sigil/wiki#yes-book-view-is-really-gone


> WYSIWYG editing is live HTML (not XHTML) editing internal to the browser engine (Chrome in this case) and not under our control. It can and often does generate code that appears to work but is NOT valid xhtml required by epub and will not pass flightcrew (now a plugin so you may want to install that) or epubcheck (also a plugin for Sigil) that most publishers require.

> The illegal xhtml code generated by the old BookView was a constant source of pain that consumed much energy and took away from Sigil development itself. Since it is internal to the browser engine we can not fix or change how it operates.

> Therefore we removed BookView and replaced it with a separate tool for those who still want some of that functionality that may be still useful for final proofing and very minor edits.

there is "it's been discussed forever in the Sigil support forums at Mobileread" but link goes to general forum, not some specific thread

**Comment by kevinhendricks** [comment]
The link above goes to a Forum "sticky thread" that is prominently seen (stuck at top) and easily available. Please confine any Wiki is outdated related topics to your recently created issue.
