### ISSUE TITLE
Unnecessary new line added when updating links to style sheets

### ISSUE THREAD

**Issue by BeckyDTP** [Sigil-Ebook/Sigil#596]
_Step-by-step:_
1. Create a new EPUB file.
2. Add two style sheets.
3. Update links to stylesheets in xhtml files (add, remove)
4. Every time an unnecessary new line will be added until we prettify the code.

![link-stylesheet-new-line](https://user-images.githubusercontent.com/22416021/110236029-f37c4780-7f33-11eb-8a51-19edc54b1a85.gif)

_Fix:_
Let's remove all whitespaces after the </title> tag
Additionally, let's add two spaces before the link to the style sheet to minimize the need to prettify the code after updating these links [as suggested by @Tex2002ans [here](https://www.mobileread.com/forums/showpost.php?p=4099985&postcount=170).

```diff
@@ -26,6 +26,7 @@
 #include <QtCore/QtCore>
 #include <QtCore/QString>
 #include <QtConcurrent/QtConcurrent>
+#include <QRegularExpression>
 
 #include "ResourceObjects/HTMLResource.h"
 #include "Misc/Utility.h"
@@ -48,11 +49,12 @@ void LinkUpdates::UpdateLinksInOneFile(HTMLResource *html_resource, QList<QStrin
     foreach(QString stylesheet, new_stylesheets) {
         QString ahref = Utility::buildRelativePath(html_resource->GetRelativePath(), stylesheet);
         ahref = Utility::URLEncodePath(ahref);
-        newcsslinks += "<link href=\"" + ahref + "\" type=\"text/css\" rel=\"stylesheet\"/>\n";
+        newcsslinks += "  <link href=\"" + ahref + "\" type=\"text/css\" rel=\"stylesheet\"/>\n";
     }
     QWriteLocker locker(&html_resource->GetLock());
     QString newsource = html_resource->GetText();
     QString version = html_resource->GetEpubVersion();
+    newsource.replace(QRegularExpression("</title>(\\s)+"), "</title>");
     GumboInterface gi = GumboInterface(newsource, version);
     gi.parse();
     newsource = gi.perform_link_updates(newcsslinks);
```

**Comment by kevinhendricks** [comment]
This should really be fixed in the GumboInterface perform_link_updates... as it is what updates the links in the code.   Using re before running the routine would effectively parses  the document twice.

Also  the added spaces make no guarantee to match the existing indentation of the code so it just moves the problem.

So please see where the extra new line in being added in the GumboInterface code and try to fix it there.  If not, I can take a look at it.

**Comment by kevinhendricks** [comment]
Took a look at the changes needed in GumboInterface, it is a bit complicated as the whitespace following a link node is in a separate whitespace node so this will have to be fixed in the serialize_contents routine in two places.

So unless you want to dig into that code (which is a bit complex since you have to understand how gumbo handles whitespace nodes including new lines), I can take a shot at it.  Is that okay?

**Comment by BeckyDTP** [comment]
Sure.

My quick&dirty solution in perform_link_updates works too:
`result.replace(QRegularExpression("</title>(\\s)+"), "</title>\n  ");`

But of course I know you can do better with std :: string directly.

**Comment by kevinhendricks** [comment]
The real issue is that the title need not be the last tag found before  the link.  The order in the head tag is not fixed.

By doing it in GumboInterface it should not matter which tag comes immediately before the link tag that is being replaced.

I have taken a shot at it which combines your LinkUpdates changes to leading whitespace with backend changes in GumboInterface.

I will push it now.

Please give it a try and let me know.

**Comment by kevinhendricks** [comment]
Closing this as fixed in master.  Please reopen it if you are still seeing the issue.
Thanks!
