### ISSUE TITLE
Explore Feasibility of a Readium Reader plugin for Sigil

### ISSUE THREAD

**Issue by kevinhendricks** [Sigil-Ebook/Sigil#614]
I have been playing around with the Readium project and more specifically the Readium Viewer develop branch from Github.

I think we could easily use the cloud-reader-lite javascript with a small amount of Python and PyQt5 to create a Readium Reader plugin for Sigil so that users can see what their book would look like in a real e-reader while still inside Sigil.

This would require us to require the PyQtWebEngine package so that plugins could create their own QWebEngine widgets just like we require the remaining PyQt5 for plugins anyhow.

To explore this I built a very very rough proof of concept.

Using Python3 I did the following:

pip3 install PyQt5
pip3 install PyQtWebEngine

Once installed I unzipped the attached viewer.zip on my Desktop as follows:

cd 
cd Desktop
unzip viewer.zip
cd viewer
python3 ./reader_demo.py

This created small  Readium viewer QWebEngineView that I had to manually resize (the code is quick and rough so I gave no sizing hints).  I was able to see the book in paged form, control the number of columns, work through the table of contents, follow links, etc.  The book itself is the huge Tex2002ans test case public epub unpacked into the viewer/cloud-reader-lite/epub_content/ebook/ folder.  We would of course point into our own copy of an unpacked epub in the plugin.

It appears to work and could easily be polished to have a specific screen resolution or allow the user to drag and drop it as they see fit.

If we decide we would like to add a reader tool directly to Sigil instead of following a plugin approach, I could code up some C++ to create a simplified version of the Preview window to act as an internal Readium reader for the book currently being edited in Sigil.

Please give this a try and let me know your thoughts.

I will attach the viewer.zip to this issue.

**Comment by kevinhendricks** [comment]
[viewer.zip](https://github.com/Sigil-Ebook/Sigil/files/6381508/viewer.zip)

**Comment by kevinhendricks** [comment]
Okay:
- fixed two javascript bugs in the cloud-reader code base that were throwing exceptions  
- updated the fonts with the ones provided by BeckyEbook that support a wider range of languages/characters better.
- extended reader_demo.py to add our own WebView and WebPage classes so that we could filter out all of "ResizeObserver: loop limit exceeded" exceptions that according to my search are harmless and should be ignored
- also added support for saving and restore screen geometry, added browser size to title bar, added a Close button.

This version of the demo seems to work okay.

I will attach it here (again with the Tex2002ans test case epub all unloaded.

**Comment by kevinhendricks** [comment]
[viewer_v2.zip](https://github.com/Sigil-Ebook/Sigil/files/6394726/viewer_v2.zip)

**Comment by kevinhendricks** [comment]
The next step would be to add PyQTWebEngine as a required python package and then change our internal code to properly bundle it.  I will look into doing that in my local tree and then create a plugin.

**Comment by dougmassay** [comment]
Throw the plugin in a github repo and I can help. There'll need to be some HighDPI considerations (on Windows and Linux) to make sure that the PyQt app in the plugin scales the same as Sigil itself. Otherwise, the PyQt plugin could launch very, very tiny. Also, I've tried to maintain compatibility with PySide2 in some of my plugins in case we ever decide to move that direction. It's not that difficult to do, but it's probably not entirely necessary, either. It seems the Window to make that move might be closing.

**Comment by kevinhendricks** [comment]
Will do once I get something running.

Take care,

Kevin

**Comment by dougmassay** [comment]
Defaults to PySide2 if installed, otherwise PyQt5.

Added HighDPI capability (with some plugin documentation).
Might have to use `python ./reader_demo.py --highdpi off` if you don't have a highdpi capable monitor (highdpi stuff ignored on macos).

[reader_demo.py.zip](https://github.com/Sigil-Ebook/Sigil/files/6398897/reader_demo.py.zip)

**Comment by kevinhendricks** [comment]
Riverside computing seems to have taken PyQtWebengine for Qt 5.12.x source code down.  On the download page it asks about a commercial license!  I can find a PyQtWebEngine for Qt 5.15.4 sdist on PyPI but not the earlier one.

Does PySide2 come prebuilt in Qt5.12.x?  I thought I read someplace about PySide now being part of Qt.  Is that true?

It seems Riverside computing is starting to control source code drops as it is not on their sourceforge page either.

Would we be better off moving to PySide if it is officially part of and supported by Qt?

**Comment by kevinhendricks** [comment]
Thanks for the improvements to reader_demo.py.  I will incorporate them into a Sigil repo for it.

I am thinking of it being an "output" plugin since it will not communicate anything back to Sigil.  The output plugin would simply use the plugin interface to copy the unpacked book out of Sigil into its local epub_content/ebook folder and then launch the reader app.  Perhaps we should try and pass in a temp/ based folder path instead so that the reader can open multiple books and not just one at a time.

**Comment by dougmassay** [comment]
Hi Kevin,

The whole Qt for python thing is just an absolute disaster right now. PyQt
hides their source and both (PyQt and PySide2) hide any worthwhile
documentation (for building and deployment). Both use Qt-specific
versioning numbers, but only one seems to require matching the Qt versions
with the python binding versions.

For instance, Ubuntu 20.04 is using Qt 5.12 LTS but are using PyQt5 5.14.4
source code to build their python-pyqt5 packages. I assume they're using
the PyQtWebEngine 5.14.0 source for their pyqtwebengine addon. Just a mess.

I guess I would ultimately like to go to PySide2 (mainly because you can
clone their source repo and simply checkout whatever version you want). But
unfortunately, Python 3.8 is not supported by PySide2 until PySide2 version
5.14.x, and unlike PyQt5, it seems that the building of PySide2 requires
you to match the minor versions of PySide2 with the Minor version of Qt.

So in short: we can't go to PySide2 without jumping to Qt5.14 or 5.15. So
for now, I would suggest sticking with PyQt5 and see if you can build
PyQt5/PyQtWebEngine 5.14.0 against our Qt5.12.9 and get everything to work.
I know that probably means a new Python package for you, but I'm not sure
it's avoidable. You *might* be able to build PyQtWebEngine 5.14.0 on its
own, but it might not be compatible with the version of sip you built PyQt5
with. I've not built or used sip version 5+ to build PyQt5.

I'll just be distributing the pypi provided binaries for PyQtWebEngine
5.12.1 (works with Qt5.12.1 - 5.12.10) since I already use the pypi
binaries for PyQt5 5.12.3 (good for Qt5.12.3 - 5.12.10.

The numbers seem to be the same for macos if you want to skip building
pyqt5/pyqtwebengine entirely. I've been doing that with my Windows
installers for a long, long time. I've not seen any licensing issues with
my approach, but I haven't looked all that hard either. I'm not
redistributing any Active State stuff. Just Python.org and PyPi
binaries/libs.I

I also know that none of that may be feasible with your Apple codesigning
requirements.

Later,
Doug

**Comment by eli-schwartz** [comment]
I'm not completely sure but I think 5.12 might simply have been so old that PyQt wasn't yet uploading sdist tarballs to PyPI. Nowadays they do, and I think the riverbankcomputing.com download locations have been deprecated. The missing sources for older PyQt might simply be accidental fallout.

I think there may have been posts to the PyQt mailing list about this very topic, if you can't find such an email thread by searching the archives then I'd directly ask about it now. It's probably an accident and the upstream developer will probably be open to providing the necessary archives -- you shouldn't just assume those are commercial-only by design until you've ruled out an accident.

**Comment by eli-schwartz** [comment]
As for building against different versions of PyQt vs. Qt I know that arch packages typically upgrade Qt shortly before new PyQt releases are available to officially support it. So it should typically be safe to build with a little leeway in versions.

**Comment by kevinhendricks** [comment]
Hanks for that info.  I thought the pip3 installed pyqt5 and pyqtwebengine instaaled their own full copies of the Qt libs.  For example when I used pip3 to install pyqtwebengine it installed almost 60 meg!

I thought the only way to get pyqt5 to use our Sigil embedded Qt 5.12.x was to built it against the version of Qt you were embedding?  Am I wrong?

**Comment by dougmassay** [comment]
They do install their own full copies of the Qt libs. I'm just not using those Qt libs they include in their wheels for my installer package.

They include the Qt libs (when installing via pip) so people don't have to worry about making sure they have compatible Qt libs of their own available to them, but they seem to work/link fine with any Qt libs their wheels' claim they're compatible with. The PyQt5 5.12.3 PyPi wheel (for all three platforms) is billed as being compatible with Python 3.5 - 3.9 and Qt5.12.3 - Qt5.12.10. I can attest to the fact that they're compatible with the custom Qt5.12.9 and Python.org Python binaries I use in my Windows installers. I've been shipping the PyPi 

You might still have some otool diddling to do on the mac side of things, I think, but I think the included mac sip.so and the other PyQt5 .so's (or dylibs, I forget) should be compatible with your Qt5.12.9 and Python3.8.3 on any Mac that's 10.6 or higher (according to the wheel's naming convention). You should be able to plug the pieces into an existing Sigil Mac installation and see, no?

We only ever use PyQt5 with out bundled (but external) python interpreter via plugins. There's really no need to use it on the embedded side.

**Comment by dougmassay** [comment]
I also blot out the __init__.py script in the PyQt5 directory in site-packages on Windows. It tries to add its own Qt libs directory to PATH and/or searches for the Qt libs on PATH. It's unnecessary in my Windows implementation. It could also be modified to use the location of Sigil's bundled Qt libs.

**Comment by kevinhendricks** [comment]
I search the pyqt archived mailing list to no avail.   I searched and found the oldest sdist on pypi to be PyQtWebEngine for 5.14.0.  I will try building it from source alongside Q 5.12.9 (plus our patches) and see if that is doable.
 
Dropping older source releases is for the birds.

**Comment by kevinhendricks** [comment]
pyqt sourceforge

**Comment by kevinhendricks** [comment]
For the record:

I finally found a place that had the source archives stored on sourceforge:

    https://sourceforge.net/projects/pyqtwebengine/
        Released /PyQtWebEngine-5.12.1.tar.gz

I grabbed it and it built and installed like a dream with Qt 5.12.9 and Python 3.8.3 after PyQt5 and sip were built.

I will push the modifications to the Sigil/src/Resource_Files/pkg_python for macOSX to master.  We can revert it if we decide to not go the plugin approach.

**Comment by dougmassay** [comment]
Great! Sounds good. I'll look into modifying the equivalent Windows python packaging script. Even if we don't go the plugin route for this feature, adding WebEngine python bindings might be welcomed by plugin devs in general. It doesn't add very much size.

**Comment by kevinhendricks** [comment]
One question, the reader_demo.py immediately opens a QApplication and you set the highdpi and those things.
How do we do the equivalent of that inside a plugin run(bk) routine?  There already is a main function running inside of sigil's plugin code?  Can we just use that run(bk) routine to create a QApplication and set highdpi right in it or do we need to use a subprocess to run the editor where it would have its own main?

I have never done a pyqt5 app in a plugin.  Is there one of your plugins or one you know that actually uses QApplication inside a plugin without using a subprocess to launch it.  Or am I making this harder than I should?

**Comment by dougmassay** [comment]
My TagMechanic plugin is PyQt5 (no suprocess to launch it). As are several others. But yes, you can do it inside the run routine of a bk container. I just tend to keep the gui stuff out of plugin.py and import it from another file. Checkout launch_gui() in dialogs.py of the TagMechanic plugin.

**Comment by kevinhendricks** [comment]
I am pulling my hair out with this plugin.  I can get it to work just fine if the path to the index.html file has no spaces in it at all.  If however there are spaces (even if they are % encoded) in the url we load, the readium javascript freaks out and stops loading resources like images!

So I can get it to work from a plugin but because plugins in macOS live in:
/Users/kbhend/Library/Application Support/sigil-ebook/sigil/plugins/ReadiumReader

I simply can not get the images to load.

I have not had a chance to get a repo going for it yet but I will upload what I have here, in case you can figure things out.

I think this is a built in limitation of the javascript used to create readium as it is normally looking at the root of a webserver and down with no spaces anyplace.

Not sure how to deal with this as we can not force people to remove all spaces!

This sucks!

**Comment by kevinhendricks** [comment]
[ReadiumReader_v010.zip](https://github.com/Sigil-Ebook/Sigil/files/6402750/ReadiumReader_v010.zip)

**Comment by dougmassay** [comment]
I'll take a peek later today. Thanks!

**Comment by kevinhendricks** [comment]
Just to test this I created a symlink from "Application Support" to "Application_Support" and used the symlinked version in the href and all of the images started appearing just fine!

So unless we can track this down and fix it inside the readium javascript we are going to be out of luck.

**Comment by dougmassay** [comment]
Very weird. It definitely can't handle the spaces, but when passing it a path with the spaces percent-encoded, the Readium code is trying to percent-encode the percent sign!

%20 becomes %2520 in an image link (right-click "Copy image address" from the context menu)

So there's some sort of percent-encoding capability of some kind inherent in Readium's javascript, it just seems to be badly broken. It doesn't encode the space on its own, and it badly mangles correctly encoded stuff.

Out of luck indeed if we can't track it down. Even using C++/Qt directly, plugin directories and tmp directories can, and will, still have spaces in them.

**Comment by kevinhendricks** [comment]
Okay, I tracked it down to a very broken URIjs module.  Its path encode decode never bothered to handle spaces.
I fixed it.

I must say the "quality" of all of these npm javascript packages really leaves a lot to be desired.
It is like they miss basic things!

Please check out the latest version of the plugin.  If this works for you I will try to create  Sigil repo for it.

**Comment by kevinhendricks** [comment]
[ReadiumReader_v020.zip](https://github.com/Sigil-Ebook/Sigil/files/6406130/ReadiumReader_v020.zip)

**Comment by dougmassay** [comment]
Works great on linux! I'll check it out on Windows a bit later (but I doubt there will be any issues). Good catch.

**Comment by dougmassay** [comment]
On Windows (using an external python interpreter since I don't have PyQtWebEngine incorporated in the bundled python for windows yet), the slashes in the query portion of the url to the index file are being encoded to %5C. The view fails with the error:

Invalid or corrupted EPUB package    epub_content\tmpxn0u0m7g\

I'm assuming it's something with stupid Windows' back-slashes in paths?

**Comment by kevinhendricks** [comment]
Hi Doug,

Yes it should.  Please push that change to the new Sigil-EBook/ReadiumReader repo on our Github site.
Mainly to test you have full permissions there!

Thanks,

Kevin

**Comment by kevinhendricks** [comment]
I am  closing this as any further discussions can happen at Sigil-Ebook/ReadiumReader repo which has the latest version of the code.

**Comment by kevinhendricks** [comment]
One more thought ... it seems a number of people make html5/css/javascript based epub e-readers for browsers.
They should be easily supportable using the ReadiumReader codebase and PyQtWebEngine as a starting point.

I believe this includes calibre's server reader/viewerer, and futurepress's epub3 reader to name just two I know about.

Is there any interest in us adding more Reader plugins for Sigil?  Or should we leave those projects to interested third parties?

**Comment by eli-schwartz** [comment]
Finally got around to searching my email and looking into this.

> As for building against different versions of PyQt vs. Qt I know that arch packages typically upgrade Qt shortly before new PyQt releases are available to officially support it. So it should typically be safe to build with a little leeway in versions.

https://www.riverbankcomputing.com/static/Docs/PyQt5/installation.html#understanding-the-correct-version-to-install

> I think there may have been posts to the PyQt mailing list about this very topic, if you can't find such an email thread by searching the archives then I'd directly ask about it now. It's probably an accident and the upstream developer will probably be open to providing the necessary archives -- you shouldn't just assume those are commercial-only by design until you've ruled out an accident.

https://www.riverbankcomputing.com/pipermail/pyqt/2020-September/043157.html

> > And source distributions were only available on PyPI since 5.14 I think.
> 
> Because earlier versions were not sdists.

This discussion recommended the sourceforge project too, but regrettably this is incomplete -- latest is 5.11.3, then PyPI picks up with 5.14, seems like some things went completely missing.

Official word on PyQt is "you should use PyQt 5.15 even when building against Qt 5.12" and suchlike.

I really do think these just went completely missing to *everyone*, not just opensource users, in the transition to PyPI sdists.
