### ISSUE TITLE
Allow CSS files to be externally edited

### ISSUE THREAD

**Issue by pgilfernandez** [Sigil-Ebook/Sigil#615]
I use a lot Sigil with Atom (or any other IDE) but I don't understand why Sigil doesn't allow to use this external editor with other text based files such as .css...
It would be great to allow it.

Thanks

**Comment by kevinhendricks** [comment]
Have to tried Sigil's  "open with" feature.  It works with any  file type editable in Sigil. Simply right click on the css file in Book Browser and select open with.  Then navigate to the app you want to edit css with and select it and give it a name.

You can then use open with with it via the right click menu.  This is all described in Sigil's User Guide.  See the chapter on Book Browser.

Closing this.
In the future, please do not use github issues to get answers to questions.  We have a User's Guide and a MobileRead Users forum for such things.

**Comment by pgilfernandez** [comment]
> Have to tried Sigil's "open with" feature. It works with any file type editable in Sigil. Simply right click on the css file in Book Browser and select open with. Then navigate to the app you want to edit css with and select it and give it a name.
> 
> You can then use open with with it via the right click menu. This is all described in Sigil's User Guide. See the chapter on Book Browser.

Indeed, I tried it and it's a solution, but it is not as fast and straightforward as the toolbar button.

As a regular user, I thought that the "Launch external XHTML editor" would be "Launch external text editor" and, so that, it would work with any text based file, while the "Open with..." feature would be suitable for other kind of files such as images, audio, video that need another kind of editors that are not text based ones.

Think it this way: if you are using the Code View editor for XHTML and CSS (both text based files), why only allow XHTML to be edited with an external text editor and not CSS?... it is somehow unexpected...
It is just my modest opinion.

> Closing this.
> In the future, please do not use github issues to get answers to questions. We have a User's Guide and a MobileRead Users forum for such things.

Sorry about it, I thought it was a missing feature because I considered it "unexpected", and so that, I considered it a small issue. If you prefer I can move it to the forums so that other users could discuss about it.

Thanks

**Comment by kevinhendricks** [comment]
The launch External XHTML editor was and still is designed as a hook into PageEdit to help non-html savvy new users who want something closer to the old BookView.

It will change its interface in Sigil-1.6.0 to always pass the path to the opf and spine position number.  This was to make things even easier for users converting from really old versions of Sigil that still had BookView.

The way to open specific files in another editor and have Sigil watch behind the scenes for writes to the underlying file is to use "open with".  Once set to your preferred application, instead of double clicking in BookBrowser to launch CodeView you right click and select open with your app.  It can not get any easier or faster.
