### ISSUE TITLE
MetaData Editor inserts wrong tags for Date: publication, Date: Creation and Date: Modification

### ISSUE THREAD

**Issue by Octet-nl** [Sigil-Ebook/Sigil#616]
In the MetaData Editor I choose Add Metadata, Date: Publication. This leads to the following entry

![image](https://user-images.githubusercontent.com/64270367/117281419-e9a78f80-ae63-11eb-837f-c774b16e1eea.png)

When I save this (button OK) and reload the metadata editor this is changed so it now reads

![image](https://user-images.githubusercontent.com/64270367/117281679-34290c00-ae64-11eb-9d95-41a32e92cf86.png)

Obviously, this tag is not recognized by my OPDS library.

The same applies to the modification and creation dates.

Double clicking this (opf:event-blication) gives a dropdown list (Creation, Modification, Publication). Selecting Publication, saving the metadata and reopening gives the correct result:

![image](https://user-images.githubusercontent.com/64270367/117282018-9550df80-ae64-11eb-9428-12cbdcdf99cb.png)

Sigil for Windows, version:

![image](https://user-images.githubusercontent.com/64270367/117282401-fc6e9400-ae64-11eb-9ba3-56b7ec1c00bd.png)

**Comment by kevinhendricks** [comment]
Yes, a bug in mapping from opf attributes into Human Readable language and back.  I will look into it.

**Comment by kevinhendricks** [comment]
This has now been fixed in master.  To workaround this bug in Sigil-1.5.1 "Add Metadata  and then choose "Date" (not one of the specific date types) and then on your newly added Date element use set "AddProperty" and select "Event".  You can then use the pulldown.

This fix will appear in the next release (Sigil-1.6.0) hopefully later this month.

Thank you for your bug report!

**Comment by Octet-nl** [comment]
Thank you for your fast response. No hurry, it's no problem using the workaround.
