### ISSUE TITLE
Windows Defender: "Windows protected your PC"

### ISSUE THREAD

**Issue by lll000111** [Sigil-Ebook/Sigil#622]
I asked Google first and it did not find anything. Is it expected that I get this warning from Windows Defender?

Installer file downloaded from https://github.com/Sigil-Ebook/Sigil/releases/tag/1.6.0

![image](https://user-images.githubusercontent.com/25476357/120226992-a1a04080-c248-11eb-850f-cf1e901814d3.png)

I think that's probably because of "Unknown Publisher" but since I did not find anything, and I think at least _some_ people should have asked a question at some point, I want to make sure this is okay. Should probably be mentioned somewhere in the release notes for installing the Windows version.

I don't think I got this message for previous releases, I think I would remember since it's the first time in years that I saw something like this when installing something, which I don't do all that often and always updates for stuff I already have a version of installed for years.

I also checked if there is something written in https://github.com/Sigil-Ebook/Sigil/wiki/Windows-Notes &mdash; there is not.

**Comment by kevinhendricks** [comment]
Yes this is a known defender issue generating fear, uncertainty, and doubt for no good reason just because we do not buy a Windows signing key.  

Sorry but as long at you downloaded your binary from our github releases (and not from anyplace else) and its sha256 checksum exactly matches that found in our posted checksums file, the  you know you have a valid installer and that nothing interfered with your download.

For more info see our User Support forums on Mobileread.

**Comment by dougmassay** [comment]
Correct. Windows found nothing at all wrong with contents of the installer. It's only complaining because the publisher is "unknown." 

Nothing short of buying an enterprise signing certificate (which can run as high as thousands of dollars) will guarantee this message will never be seen. I'm not spending that kind of money to make people feel warm and fuzzy about installing free, open source software I work on as a hobby. ;)
