### ISSUE TITLE
renaming XHTML file produces error when the change is small-capital letter only

### ISSUE THREAD

**Issue by UnrulyNatives** [Sigil-Ebook/Sigil#640]
A small glitch when doing rename operation:
when the filename change is just a change between capital and small letter, I receive  error "filename already exists". 

That's simply it. Best wishes.

**Comment by kevinhendricks** [comment]
Not a bug.  That same change on a Windows box or any case-insensitive filesystem should fail otherwise you have a potential name clash.  So we make it fail on all filesystems because a name clash could occur.

Just rename it to something that is not just a case change and if desired you can move it back to be what you want.
