### ISSUE TITLE
[Bug]: 'Count All' in 'Find & Replace' opens first file searched

### ISSUE THREAD

**Issue by waldoluisribeiro** [Sigil-Ebook/Sigil#670]
### Bug Description

In v1.9.0 the _Count All_ option in the _Find & Replace_ panel opens the first file that is searched, regardless of whether there is a match and in all search modes. If _All HTML Files_ is selected, the first HTML file is opened, whereas if _All CSS Files_ is selected, the first stylesheet opens. This unexpected and undesired behaviour (it didn't happen in v1.8.0) doesn't occur the first time _Count All_ is selected after toggling _Minimal Match_, but it resumes from the second use. Clicking on _Restart_ causes the behaviour to stop until the scope of the search is altered. Perhaps this will help to narrow it down.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

11 21H2 (Build 22000.493)

### What version of Sigil are you using?

1.9.0

**Comment by kevinhendricks** [comment]
Yes.  Thank you for your bug report.  This bug was already reported in our Sigil Forum in MobileRead. We have a current build being tested by users there to try to fix this and other related search issues.  Once that passes testing, we will be releasing a quick Sigil-1.9.1 follow up release (soonish).

**Comment by waldoluisribeiro** [comment]
I appreciate your prompt response and look forward to the new release.
