### ISSUE TITLE
Installing over existing install with different bitness (Windows)

### ISSUE THREAD

**Issue by yonizaf** [Sigil-Ebook/Sigil#682]
### Bug Description

Steps to reproduce:
1. Install the 32bit  Windows version of Sigil.
2. Install the 64bit version over it (without uninstall). 
        This will overwrite all shortcuts and icons to the new install, and hide the 32bit uninstaller from the Apps & Features screen in Windows Settings (so you can only uninstall the 64bit one).
4. Uninstall the 64bit version. This will remove all icons and shortcuts, but leave the 32bit version installed - only there's no shortcuts to run it.

Expected behavior could be one of the following:
- Allow side-by-side installs with different shortcuts and uninstall entries (as Calibre does, I believe).
- Uninstall older, different bitness installs as part of the install process.
- Warn the user during installation that a different bitness version is installed and prompt them for options, or abort the install. (this one should include a different solution for unattended installs)
- Create a universal installer that installs the correct bitness automatically.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 10 64bit

### What version of Sigil are you using?

1.9.2

**Comment by dougmassay** [comment]
Side by side installs of Sigil are neither supported nor recommended. There will be no changes in this regard. When it comes to updating, I always recommend uninstalling Sigil first. Doing so causes no loss of data, preferences of plugins. I'm simply not interested in trying to get InnoSetup to head off any and all ways things can get hosed. Sorry.

**Comment by yonizaf** [comment]
Fine. Consider this then: The Chocolatey package for Sigil 1.9.1 installed the legacy version for everyone (as you should already know). Assuming the package for 1.9.2 is to be corrected now, it will leave a hidden Legacy install for everyone who updates from 1.9.1. 

How do you suggest this should be handled? Should the Chocolatey install script search for all older Sigil versions and uninstall them?

**Comment by dougmassay** [comment]
I have no interest in the Chocolatey version of Sigil. They've broken it, and I have no interest in fixing it for them. Starting with version 1.9.2, the Legacy version of Sigil installs as a completely different entry in Windows' Add/Remove programs. From this point on, there will only be two versions of Sigil: the 64-bit official version, and the 32-bit Legacy version. Both can be removed/installed independently, and both have their own shortcuts (desktop and menu). Though both will still share the same preferences.

I can't go back to the past and fix problems that happened when earlier versions of 32-bit Sigil were installed. Nor am I going to get involved in fixing the mess Chocolatey created by choosing to install the legacy version of Sigil by default starting with Sigil 1.9.1.

**Comment by yonizaf** [comment]
I intend to become the maintainer of the Chocolatey version of Sigil - that's why I asked.  From your comments on that page, you said you were happy to work with package maintainers, and that you nudged hoping they could get that right. Are you taking that back? Then maybe I really shouldn't bother.

**Comment by eli-schwartz** [comment]
If chocolatey installed the old version, shouldn't it know which uninstaller to use in a one-time migration?

I assume it's not chocolatey's responsibility to handle issues with externally installed versions.

**Comment by dougmassay** [comment]
No. I'm not taking that back. If you take over maintainership, I will be happy to assist. As I already said, most of this will already handle itself in the future (Since Sigil-Legacy will be installed as a different program than the standard Sigil).

I don't know the ins and outs of packaging for Chocolatey, so I don't know how best to handle the situation where they installed the 32-bit Legacy version of Sigil (while under the hood, it looked like they were installing a 64-bit version of Sigil) by default. If uninstalling Sigil first is an option, I would say that can be done with no loss of preferences.

As I mentioned, there will only two different Windows installers for Sigil moving forward: the official 64-bit version (only suitable for Window 8 and higher), and the 32-bit Legacy version (suitable for Windows 7+)

My recommendation would be to only install the 64-bit version of Sigil with the existing Chocolatey Sigil package (but limiting it to Windows 8 or higher). If that's even possible, of course.

The if there's a need to continue supporting Windows 7 and/or 32-bit architecture. A new and separate Chocolatey package for  Sigil-Legacy should be created. And ne'er the twain should meet.

**Comment by yonizaf** [comment]
The way I'm doing it now ([this is the package source](https://github.com/yonizaf/ChocolateyPackages/blob/main/Sigil/tools/chocolateyinstall.ps1), it's a powershell script) is to install the Legacy installer on windows 7 only, and the regular installers on newer versions. Although creating a separate package sounds like a possibly good idea, I would have to check if that's a common practice for Chocolatey packages, and how to handle it exactly. 

It would still leave me with the headache of handling previous installed versions (and may be even more annoying if it's a different package). Or I can just leave it at that and tell people that complain to clean up the old mess by hand.

**Comment by dougmassay** [comment]
That's not a bad approach (using the Legacy installer on Win7 only). Those wanting to install a 32-bit version on Windows 8+ are going to get exceedingly rare. I'm not entirely sure when the url32 (Sigil-x.x.x-Windows-Setup.exe) installer will go away, but it will be fairly soon. I won't be patching/custom-building another 32-bit version of Qt when we eventually move to Qt6. The Legacy version installer with Qt5.12.9 and Python3.8.3 with then be kept in feature-sync with the official 64-bit version for as long as it remains feasible to do so.

**Comment by yonizaf** [comment]
Thanks for the information, also for your time and patience.

I will push the package as is for now, just so people can install the latest version if they want. For future versions, I will keep researching the best method to uninstall older versions (possibly even ones not installed by chocolatey, if you say it's the recommended course of action).

**Comment by dougmassay** [comment]
No problem. If you need anything in the future, just remind me you're the Chocolatey Sigil maintainer. :)

**Comment by dougmassay** [comment]
If you get some time, I was wondering if you'd be willing to edit the Chocolatey Package description for Sigil sometime?

Book View and WYSIWYG editing have been gone from Sigil for several years now (but are available in the separate companion PageEdit program). 

The bullet points from https://sigil-ebook.com/sigil/ and the short description from the README are up-to-date, and should have just about everything relevant.

We'd sure appreciate it.

**Comment by dougmassay** [comment]
Thanks! No rush at all. I just happened to notice it was a little outdated.

**Comment by dougmassay** [comment]
Pinging @yonizaf that Sigil 1.9.20 has been released.

Also to note that when Sigil eventually officially switches from Qt5 to Qt6, the only versions that will be released will be the Windows 64-bit and the Legacy 32-bit. There will be no Qt6 32-bit version of Sigil.

**Comment by yonizaf** [comment]
Noted.

**Comment by dougmassay** [comment]
Pinging @yonizaf that starting with Sigil 2.0 (the upcoming release), the minimum supported OS will be Windows 10 (1809). There will also be no official 32-bit version starting with Sigil 2.0. This is due to Qt6.5 and QtWebEngine requirements.

I hope to eventually provide an unofficial 32-bit legacy version of Sigil. But if so, I will try to take that on myself as a separate chocolatey package.

Let me know if I can help with anything. I posted a similar message in the Sigil Chocolatey discussion section so that users won't be blindsided.

**Comment by yonizaf** [comment]
Thanks for letting me know.

**Comment by yonizaf** [comment]
Since this issue was somewhat established as our point of contact regarding Chocolatey package maintenance, I'm using this to notify that I'm stepping down as the maintainer of Sigil Chocolatey package. (The reason may or may not be [this mess](815))

I'm not going to try and find someone else to take over, mostly because I have no idea how to do that.
