### ISSUE TITLE
[Bug]: Metadata Editor Error

### ISSUE THREAD

**Issue by SirGryphin** [Sigil-Ebook/Sigil#689]
### Bug Description

When trying to edit metadata using the editor, when I try and save or changed anything I get this error.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

19044.1766

### What version of Sigil are you using?

1.9.10

### Any backtraces or crash reports

```shell
Traceback (most recent call last):

  File "sre_parse.py", line 1039, in parse_template

KeyError: '\\U'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Program Files/Sigil/python3lib\metaproc3.py", line 324, in set_new_metadata
    newopfdata = _metadata_pattern.sub(newmetadata,opfdata)

  File "re.py", line 327, in _subx

  File "re.py", line 318, in _compile_repl

  File "sre_parse.py", line 1042, in parse_template

re.error: bad escape \U at position 366 (line 7, column 28)
```

**Comment by kevinhendricks** [comment]
Is your opf file properly utf-8 encoded?  That error is not occurring in Sigil code, but instead is deep in the python re module.

**Comment by kevinhendricks** [comment]
Based on a google search this appears to be related to a bad escape sequence in aregular expression, but \U is not used in any regular expression used in the metaproc3.py file.  So I am not sure what is going on.

Would you please zip up a copy of that epub's OPF file and attach it to this issue so that we can try to use it to hopefully recreate what you are seeing.

**Comment by kevinhendricks** [comment]
Yes this is a bug.  The re pattern sub will process the replacement string forescape and your opf has a "\U" someplace in it triggering the error. 


I will need to handle that substitution in a different way to prevent that bug from the new behaviour.

**Comment by SirGryphin** [comment]
Sorry for late reply, here is the opf file in a zip
[content.zip](https://github.com/Sigil-Ebook/Sigil/files/8986353/content.zip)

Hope this helps.

**Comment by kevinhendricks** [comment]
There does not appear to be any escape sequences in that opf metadata at all.  When you are  editing the metadata, are you adding a \U someplace?

**Comment by kevinhendricks** [comment]
What was originally in the dc:subject tag before metadata editing?  Why is there a completely empty tag?

<dc:subject/>

**Comment by dougmassay** [comment]
Possibly an invisible character being pasted into one of the Metadata
Editor fields?

**Comment by kevinhendricks** [comment]
@dougmassay,
To recreate this error, start with an empty epub2 or epub3, and fire up the metadata editor.  Add a Subject tag and for its contents add the string "\\U vs \U" and make sure that field is saved before hitting okay.

You will see the KeyError that was reported.

So according to the error message in this bug report somewhere in the dc:subject line after editing there is a \U character sequence.  Unknown escape sequences never used to be a problem but re.sub changed in the Python 3.8 or 3.9 time frame to throw an exception with unknown exceptions and so re.sub is no longer useful for replacing a segment of text with another string that may contain unintended escape sequences like \U (or \ and other ascii character).

In metaproc3.py (and metaproc2.py), I have now replaced the use of _metadata_pattern.sub() by a code sequence that manually builds up the new string from pieces of the old without trying to process the string being inserted for escapes.

This will be much safer in the long run.  If I remember correctly, this approach for using re.sub was heavily used in KindleUnpack as well so we may need to revisit things there given the change in how re.sub works now.

This bug is now fixed in master.

@SirGryphin, to temporarily work around this bug until the next Sigil release is made, in your dc:subject field look for any \U character sequences and replace them with \\U which re.sub should now happily convert back to \U when closing the editor and that will prevents your error for the time being.

**Comment by dougmassay** [comment]
Thanks for the info. Have we checked to see whether the problem persists in
Barnett's regex.sub? It will always be available in any of our Mac/Windows
bundles. If so, perhaps we should use it and make the newer regex module a
mandatory dependency for linux.

But if you've already worked out an alternative, perhaps that's the better
approach.
