### ISSUE TITLE
[Bug]: Sigil has encountered a problem.

### ISSUE THREAD

**Issue by SirGryphin** [Sigil-Ebook/Sigil#690]
### Bug Description

So I get this error message box.

![Screenshot 2022-07-01 122951](https://user-images.githubusercontent.com/36343615/176886280-7a4d9ccc-d1d6-4acc-a3bc-f31dcd3cd331.png)

You click close on error message box and signal loads as normal. It only happens when opening certain epubs. I've can included epub that causing error, I'm not sure if that's allowed if not please let me know.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

19044.1766

### What version of Sigil are you using?

current

### Any backtraces or crash reports

```shell
Error info: Critical: QWindowsFontEngine::QWindowsFontEngine: GetTextMetrics failed (The operation completed successfully.)
Sigil version: 1.9.10
Runtime Qt: 5.12.9
Compiled Qt: 5.12.9
System: Windows 10 (10.0)
Architecture: x86_64
```

**Comment by kevinhendricks** [comment]
This is an error message and exception that is thrown by Qt on Windows only.  There have been reports with this error message in the past and it was due to old/corrupted ini files defaulting to a font for use by Sigil that was no longer on that system.  Backing up the old Sigil ini file and renaming it was enough to get things to work again.

But your bug only happens with specific epubs and not all epubs.  So this may be something different.  Do the epubs that cause this error have embedded fonts in them.  If so the font file they embed may actually be faulty and missing its font metrics.  If that is the case you could try replacing that font with a known good one.

If no fonts are embedded, and if the epub is your epub (you are the author and own copyright) or in the public domain they please zip it up and post it here.  If not, then please post the epub privately someplace and on www.mobileread.com , pm (personal message)  KevinH (me) with a link.

**Comment by SirGryphin** [comment]
@kevinhendricks Yeah it has multiple fonts files, I managed to find that one of the was corrupt would even open when I extracted it and try to preview it, I replaced it and it works fine now.

Thanks for all the help.
