### ISSUE TITLE
Release signature bad, also signed by different key than documented

### ISSUE THREAD

**Issue by alerque** [Sigil-Ebook/Sigil#710]
# Bad signature

The signature on the `.tar.gz` download artifacs is bad:

``` console
$ gpg --verify Sigil-1.9.30.tar.gz.sig
gpg: assuming signed data in 'Sigil-1.9.30.tar.gz'
gpg: Signature made Tue 14 Mar 2023 08:29:19 PM +03
gpg:                using RSA key 6EC59D41083E5F0F7E61424C56CD953D30E1BBCD
gpg: BAD signature from "Doug Massay <douglaslmassay@gmail.com>" [unknown]

$ sha256sum Sigil*
262c43ec0ce9ea9486fc19074dd0a687a39d9df1829732e9006d8c5fbb242458  Sigil-1.9.30.tar.gz
4ee121e8e067c5f1fee2ba405bd15984325a63e96a4a143c33c50cf397a17bfb  Sigil-1.9.30.tar.gz.sig 
```

# Undocumented key

Secondarily today's v1.9.30 release artifacts are signed by a different GPG key id than previous releases.

Previously: B5A56206AB0FBC1A24EFAB8AA166D29A8FCDAC63
Today: 6EC59D41083E5F0F7E61424C56CD953D30E1BBCD

This appears to be a signing subkey of the other one so I'm going to go ahead and trust it, but the release notes still reference the primary key as the one to expect signatures from. Usually when the signing key is changed one would expect a signature from the previous keyholder for attestation. In this case it is the same master key so we don't need attestation for the change, but updated docs / release notes are probably in order.

**Comment by dougmassay** [comment]
I'll check, but I've done absolutely nothing different in the way Sigil's tagged sources are signed and binary artifacts are checksummed.

**Comment by dougmassay** [comment]
Github must've changed the way their source tarballs are generated. So my macro to created the detached signature is no longer working. I've updated the correct sig file to the 1.9.30 release.

I'll take the subkey recommendations under advisement. Fact is: Sigil has been released under this particular subkey/primary key arrangement (including the fingerprint provided in the docs/release notes) for several releases now.

**Comment by eli-schwartz** [comment]
Git itself switched the default `tar.tar.gz.command` config setting from defaulting to "gzip -cn" to instead default to "git archive gzip", an infernal version of gzip that doesn't fork, for systems where you don't have a gzip or your gzip is really slow, like a whole second slower on Windows or something. :D

GitHub preserves compatibility and stability by having this site use a manually configured "gzip -cn" regardless of git version. Future editions of gir itself, may unbreak the flaw of having their own incompatible gzip, or otherwise arrange to guarantee that the output format is versioned so changes can be made that don't break.

If you set that config knob yourself for your local dev machine then you should be able to get stable, predictable tarballs again.

**Comment by dougmassay** [comment]
Great. Thanks for letting me know about the bad sig so quickly! Two distros had already updated to 1.9.30 before I even had the gpg sigs attached to a release!
