### ISSUE TITLE
[Bug]: onepiece of translations to chinese is wrong

### ISSUE THREAD

**Issue by whongsheng** [Sigil-Ebook/Sigil#712]
### Bug Description

im using sigil 1.9.20 for chinese, found one place of translations is wrong:
in the "格式" menu, the "下标（S）" is wrong, should be "上标（S）".
by the way, thank you for your work.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

win10

### What version of Sigil are you using?

1.9.20

**Comment by kevinhendricks** [comment]
We do not do translations.  We pull them in.   We have volunteer translators at Transifex for all languages.

See https://explore.transifex.com/zdpo/sigil/

File your issue there so that the Chinese translators see and fix the issue, otherwise it will just reappear when translatiins are updated from Transifex again.
