### ISSUE TITLE
[Feature Request]: Win7 x64

### ISSUE THREAD

**Issue by crogonint** [Sigil-Ebook/Sigil#717]
### Bug Description

Pretty simple. Can we get a legacy export for Win7 that uses x64? I understand that crunching the ePub when you publish it can take some serious horsepower, so utilizing the 64 bits would have to help.. right?

(Sorry, I couldn't figure out how to switch the Label from Bug to Feature Request>)

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Win7 x64

### What version of Sigil are you using?

1.9.30 legacy

**Comment by kevinhendricks** [comment]
Because if you read the README.md we specifically ask people NOT to post feature requests our github issues.

Instead it instructs people to reach out on our Sigil Forum on MobileRead (www.mobileread.com) so that other users may see the request and comment about its usefulness.

Closing this issue since not an actual bug
