### ISSUE TITLE
[Bug]: version 2.0.1 crashes at start

### ISSUE THREAD

**Issue by jr2893** [Sigil-Ebook/Sigil#721]
### Bug Description

crash at start with windows 10 last updates. Open sigil windows and after 3 seconds crash

### Platform (OS)

Windows (Default)

### OS Version / Specifics

22H2 19045.3324

### What version of Sigil are you using?

2.0.1

**Comment by dougmassay** [comment]
Unable to replicate your crashing issue. I'm running Sigil 2.0.1 on multiple Windows 10 machines (using different display card manufacturers). Can you check Windows Event Viewer after a crash and provide any more info?

Are you running a recent display driver? Qt6 will require more that Qt5 in that regard.

**Comment by kevinhendricks** [comment]
Probably interference from a system extension or from anti-virus or defender software?

**Comment by dougmassay** [comment]
A couple of things to try:

1) make sure the crash happens when opening Sigil by itself, and not by a) double-clicking a particular epub, or b) Calibre's Open With feature or plugin.

2) if opening sigil completely on its own is still crashing, try checking "Disable GPU Acceleration in QtWebEngine" in Sigil's settings (found under the General Settings section/Advanced tab). If you can't get to Sigil's preferences before it crashes, enter a "disable_gpu=true" (without the quotes) line in the Sigil_v6.ini file under the [user_preferences] section header.

If you don't know where your Sigil preferences folder is located: https://sigil-ebook.com/sigil/tips/#locating-your-sigil-preferences-folder-on-windows

**Comment by dougmassay** [comment]
Due to there not being any follow up on this, I'm going to close this issue for the time being. Feel free to reopen it when/if you are ready to provide further documentation on the crash.
