### ISSUE TITLE
[Bug]: Menus at the top always open on primary monitor with multiple monitors

### ISSUE THREAD

**Issue by jamescastle** [Sigil-Ebook/Sigil#722]
### Bug Description

When I click on any menu (File, Format, Search,...), the drop-down box always opens on my primary monitor in my dual-monitor-setup. If I use Sigil on the primary one, they open downwards normally. But when I use it on my secondary monitor, they will pop up on the top left corner of my primary monitor.

I attached a screenshot for visualisation
![sigil_issue](https://github.com/Sigil-Ebook/Sigil/assets/20130781/81c13fae-97b4-44a5-95dd-b0f97006770b)

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 10 Pro 22H2 build 19045.3324

### What version of Sigil are you using?

2.0.1

**Comment by kevinhendricks** [comment]
Are your two monitors by chance absolutely identical?  Same manufacturer, same size, same dpi, same scaling, etc?

We have had one other person in our Mobileread User forum with identical monitors reporting the exact same issue.   Many users with two different monitors are reporting it all works as expected for them.

**Comment by jamescastle** [comment]
Yes, they're both Acer XF270HUA. And they're both 2560x1440 at 144Hz.

Strange behaviour, if I may say so.

**Comment by kevinhendricks** [comment]
Yes, previous versions of Qt6 used to use the user set-able monitor Display names to distinguish between otherwise identical monitors.  But people filed a bug report with them  since most people do not bother to set different display names in Windows Control panel. So for Qt 6.5.2 (the version we use in Sigil for 2,0.0 and 2.0.1, they moved to using Monitor serialNumbers (not set-able by the user) as these should always be unique.

But for for some users it appears that these "serialNumbers" as discovered by Qt are blank (empty strings) making the monitors completely identical again with the added problem that the user can no longer set anything to help.

I tested this on macOS but my monitors are different and not problems occur.  But both return n empty string for serialNumbers.

My guess is this is related to security changes made by either Defender/Microsoft and/or Apple to prevent browsers from creating "digital fingerprints" to enable tracking across websites.

We are  planning to create a debug build of Sigil that will dump the monitor information for all screens based on Qt's perspective in an effort to help track down if missing serialNumbers are indeed the culprit.  If we can nail things down we can create a patch for Qt6 and future builds should not have this issue.

When we have a debug build of Sigil, we would appreciate you testing it and reporting back on a clean install of Sigil (ie. rename the Sigil Preferences folder so that it is saved) to see if it can confirm our hypothesis. so that we can try to develop a patch.

Sorry I can not be more help here as but my primary platform is macOS and our main Windows developer does not have a way to generate identical monitors in order to test.

**Comment by jamescastle** [comment]
As far as I'm concerned, this already was very helpful. And I would be glad, if I could test a possible patch for this.
For now, it's just an inconvenience and I can deal with it.

**Comment by kevinhendricks** [comment]
Based on debug test Sigil run by the other reporter, It turns out that some monitor manufactures did not bother to update the serial number in the monitors EDID blocks.  That is against the rules but it happened and according to some, it is common.

Qt6 uses the EDID blocks to extract name, manufacturer, and serial number to uniquely identify each display monitor.  Since both monitors are literally identical, even by serial number, it confuses Qt so much they can not tell which monitor they are on.

There really is no easy fix, as the EDID serial numbers are meant to be unique always. 

We will have to wait to see if Qt will adapt how they recognize multiple identical displays in a future release.

**Comment by kevinhendricks** [comment]
We now have a workaround fix for the bug in Qt that causes this problem.  

If you feel comfortable downloading a patched qwindows.dll.zip tile, unzipping it, and using the resulting qwindows.dll file to fully replace the its namesake inside the platforms folder inside the installed Sigil program directory, you are welcome to try it.

After copying the new dll into place, you should probably restart your machine to force it to be used when you next start Sigil.

The qwindows.dll.zip can be downloaded from one of my personal github repis here:

https://github.com/kevinhendricks/BuildSigilOnMac/releases

My site is Mac Oriented but that file is meant for Windows.

If it works, feel free to keep using it.  Our future releases will include it until Qt actually fixes their bug.

**Comment by jamescastle** [comment]
The downloading and replacing of the DLL was no problem at all.
Unfortunately, I must report, it didn't fix it here. First, I just tried to replace it and start Sigil: still the same. After that, I rebooted my whole machine as suggested, but same negative result.

**Comment by dougmassay** [comment]
The new, patched qtwindows.dll needs to be the only thing in that platforms folder in Sigil's program directory. renaming the old one and leaving it in place has not always worked. It doesn't make sense to me that it wouldn't work for your case, too. This change reverts things back to what worked for older versions of Qt/Sigil. 

We'd probably need to see some debug output to make sure the new code in the dll is doing what it's supposed to be doing.

**Comment by jamescastle** [comment]
That did the trick. I made a backup copy of the old DLL and it probably still used this. Now I moved the backup to a different folder and everything works fine.

**Comment by kevinhendricks** [comment]
Are you sure you completely removed the qwindows.dll file that existed in the platforms folder inside of the Sigil program folder and replaced it with the qwindows.dll  you unzipped.  If you just renamed it, the old dll file will still be used for some reason.  The new qwindows.dll must be the only file in the platforms folder.

Then restart.

The reason I ask, is the other person who I thought had the same issue as you did and has identical monitors also tested that fix and said it worked like a charm.

Please try again and make sure you are using Sigil-2.0.1 and not Sigil-1.9.30.

If it still does not work, then perhaps you have a different issue than what our first bug reporter on Mobileread had.   If so we have a debug build of Sigil that might help us see what is going on.

Thanks.

Kevin

**Comment by kevinhendricks** [comment]
This fix will appear in future releases of Sigil until Wt fixes their bug.  I will close this bug as fixed.

**Comment by dougmassay** [comment]
> That did the trick. I made a backup copy of the old DLL in the same folder and it probably still used this. 

Great! The same thing happened to me in my testing is why I asked. Windows does weird things by keeping dll functions in memory, but I still don't quite fully understand why it would still load the renamed one after a reboot. Qt must flag those plugins dlls in some way (after the first open) other than by name alone.

Thanks for sticking with it.
