### ISSUE TITLE
[Bug]: Crash when add exist files on Mac

### ISSUE THREAD

**Issue by Narga** [Sigil-Ebook/Sigil#726]
### Bug Description

This problem happened with the latest version. I had a pack of boilerplate epub files, when I was trying to add some exist files like styles.css, fonts. the Sigile crashed.
Sigil v1.9.3 is still working fine.
Here is the crash reports by system: https://pastebin.com/4dP4GVTU

### Platform (OS)

MacOS

### OS Version / Specifics

12.6.8 (M1)

### What version of Sigil are you using?

2.0.1

### Any backtraces or crash reports

```shell
https://pastebin.com/4dP4GVTU
```

**Comment by kevinhendricks** [comment]
You are running both rosetta and are using Quartz according to that backtrace?  Where did you download this binary from?  Why are you not using the native arm64 build we post instead of rosetta since you have an M1 machine?

Your backtrace shows things I would not expect to see in a build I made for release.

Are you by chance using Apple Accessibility tools or features?  
Current Qt has lots of issues with Apple Accessibility tools and features.  
Qt has tracked most of these down and fixed them but these fixes will not appear in Sigil until its next release.

We previously posted a test build (arm64) with many of these Qt bug fixes in place.  Please give it a try and let us know if it fixes your issue.

https://github.com/kevinhendricks/BuildSigilOnMac/releases

Get the Sigil.app-testbuild2-Mac-arm64.tar.xz

**Comment by kevinhendricks** [comment]
If this test build does not help, please zip up the full Mac CrashReport it created and upload it as a zip attachment here.

**Comment by kevinhendricks** [comment]
Closing this as now fixed in master.

**Comment by Nathaniel-Wu** [comment]
I had a similar problem with the released version 2.0.1, when I tried to add a new plugin, the file selection window crashed the application. The Sep 6 arm64 build from https://github.com/kevinhendricks/BuildSigilOnMac/releases does not have this issue.

**Comment by kevinhendricks** [comment]
Yes. It is a known bug in Qt 6.5.2 when MacOS Accessibility features or tools that use them are being used with Sigil.

The next release will move to Qt 6.5.3 that was released on Sep 2th.  It fixes those Qt issues.
