### ISSUE TITLE
[Bug]: six is required?

### ISSUE THREAD

**Issue by pgajdos** [Sigil-Ebook/Sigil#730]
### Bug Description

Documentation states six is required, but I do not see import anywhere. Is that dependency correct?

### Platform (OS)

Linux

### OS Version / Specifics

SUSE Linux

### What version of Sigil are you using?

2.0.1

**Comment by dougmassay** [comment]
How is this a bug report?

**Comment by eli-schwartz** [comment]
Well, I suppose it is a documentation bug report.

Superficially it looks like that dependency is probably in the wrong section of the documentation -- maybe it should be listed in the section after (rather than before:

> That's all the Python 3.5 (or higher) stuff you will need to get Sigil "up and running", but if you want to make use of Sigil plugins that people are developing, you will also want to install the "standard" modules that ship with the binary version of Sigil

**Comment by kevinhendricks** [comment]
It was required by earlier versions of bs4 and html5lib and css_utils.  If it is not needed by anything anymore I will remove it in a future release.

**Comment by kevinhendricks** [comment]
And it still is required for html5lib according to its requirements.

https://github.com/html5lib/html5lib-python/blob/3e500bb6e4188ea087f5b743a720ed9f4d9216f9/requirements.txt#L2

So this is not a bug and no changes needed.

**Comment by kevinhendricks** [comment]
This "non-mandatory" or "optional"  nonsense is a complete artifact made up by Linux distributions that creates differences and problems for everyone.  

We, the creators of Sigil , do not and never will consider plugin support to be "non-mandatory" or in any way "optional".  Plugins are an integral part of Sigil ever since I designed the interface and it was first released.  

Six was used then because it was needed for html5lib and because we supported both Python 2 and Python 3 at the time.  Since then it has become part of the plugin environment and we will not break plugin user land without long deprecation notices.

If Linux could ever decide on a single app standard layout and min abi, we would happily create our own Linux releases just to prevent nonsense like 3rd party maintainers deciding what constitutes Sigil proper and what doesn't.

So this is not a bug, nor is it something we are going to change.

The true bug is Linux "maintainers" trying to make decisions on what is "optional" in any way shape or form for an app they do not create or support.

**Comment by kevinhendricks** [comment]
And I think we already work hard to support Linux and get little to nothing back for our efforts.   

We sent out notices in advance about the move to default to Qt6 and found nobody listened at all at first.  We have numerous Linux distributions that never update at all because the maintainers personal preference for his platform powerpc (Fedora stuck on 0.9.14 for example) even with offers of help.  Most Linux users never even get to try plugins at all because of the Linux  "non-mandatory" policy they created, never mind that plugins are used for many essential epub dev tasks such as epubcheck, converting epub2 to epub3, css validation, importing kindle books, converting inline styles to styesheets, etc and etc. Or they use the old Mathjax ...

 And this completely ignores the lack of standardization throughout Linux.  

Yet, you can build Sigil and PageEdit out of the box on most popular Linux distributions because of DiapDealer's efforts.

And third party app packages do not make anything better as Flatpak via its "sandboxing" disables copy and pasting from clipboards, disables the entire "open with", disables "XEditor and therefore PageEdit, etc;   And other third party app packages must be built with horrifically old glibc and qt versions and/or relocatable python packages.

Perhaps Linux should focus on cleaning up its own house.
