### ISSUE TITLE
[Bug]: Translation Error

### ISSUE THREAD

**Issue by shelling4d** [Sigil-Ebook/Sigil#738]
### Bug Description

<img width="593" alt="屏幕截图 2024-02-14 105620" src="https://github.com/Sigil-Ebook/Sigil/assets/17538958/d6dbc967-017d-4e37-b855-c654d04f4f04">
Translation Error

### Platform (OS)

Windows (Default)

### OS Version / Specifics

windows 11 23H2

### What version of Sigil are you using?

2.0.2

**Comment by kevinhendricks** [comment]
Sorry.  Sigil gets its translations from volunteer teams via Transifex.
Check out our README for links.

Translation errors must be fixed by the language volunteers at Transifex for your language.  Otherwise the error will just cime back once we pull updated translations from Transifex which we do for every release.
