### ISSUE TITLE
[Bug]: Sigil on MacOS will not save toolbar changes after new install 

### ISSUE THREAD

**Issue by v-v-x** [Sigil-Ebook/Sigil#757]
### Bug Description

After any closing of the working window, the set of buttons is not saved

### Platform (OS)

macOS

### OS Version / Specifics

Macos 12

### What version of Sigil are you using?

2.2 and 2.2.1

**Comment by kevinhendricks** [comment]
What version of macOS Apple Silicon (arm64j or Intel (x86_64)?

What set of buttons?  Please be specific.

Please attach screenshots to illustrate the issue.

Please provide detailed step by step instructions how to recreate the issue.

Without this, I have no idea if what you are seeing is even a bug?

**Comment by kevinhendricks** [comment]
In Addition, are you using FullScreen or Maximized the MainWindow?

Have you yet been prompted for local disk access and approved it?

Have you ever manually resized the Main Window?

**Comment by v-v-x** [comment]
Macos 12.7.5, Intel
I just open the program (I don't use full screen mode or manually resize the window). Then drag and drop buttons for more convenient work, some sets of buttons I delete. Then close the program window or exit it. When I reopen the program window, all the buttons are in their original place.
<img width="1280" alt="originaled" src="https://github.com/Sigil-Ebook/Sigil/assets/6433095/64842b20-8b61-4f66-a40b-3d0a2583e184">
<img width="1280" alt="reodered" src="https://github.com/Sigil-Ebook/Sigil/assets/6433095/871d6a48-f802-44d7-886b-d56fc5cbe3a1">

**Comment by kevinhendricks** [comment]
It appears that MacOS has started treating un-notarized software differently from notarized software.

This appears to be an "feature" of how MacOS has decided to deal with programs that are not-notarized.  It prevents the untrusted program from writing its Sigil settings ini file.

Since we will not be notarizing our software, here is how you workaround this "feature" in macOS.  You need only do this once.


1. Open Sigil.app

2. Manually resize the MainWindow to any new size that you like (do not use Maximize or Full Screen for this).  **This is a required step to show macOS that you know this application is running under your control.** 

3. Next use Sigil's menus to open *any* epub that is on your local disk.  MacOS will prompt you to allow access to your Local Disk.  Say yes (as Sigil needs to write its settings ini file to someplace when it closes).

The OS should now have given Sigil permission to save its settings file ini to your local disk.

4. Close the MainWindow that originally opened leaving just the new MainWindow with an epub loaded.  This is important as the last Window closed is the one that sets Sigil settings.
So remember to close the originally opended Window first leaving just one.

Now feel free to drag and drop toolbars to where you like.

Then close the Sigil Main and exit out of Sigil.

Your new toolbar locations should now happily appear in every launch of Sigil after that.

I will try to figure out a workaround that will stop the need for this nonsense for a future release.  But this should be enough for MacOS to trust Sigil even though it is un-notarized.

**Comment by v-v-x** [comment]
I did this procedure, but something seemed to have gone wrong. The system did not ask me for permission to access local files. To clarify: after installing Sigil (unzipping it and putting it in the Application folder), the system won't let me run it, so I open System Preferences > Security & Privacy and allow Open Anyway. After that Sigil starts successfully. Is there any other way to install Sigil?

**Comment by kevinhendricks** [comment]
Yes, Just unpack the tar.xz and mov Sigil.app directly to your /Applications folder.  Then directly right click on Sigil.app and select "Open" and it will give you that nastigram about not being notarized.  Immediately right click it again on it and slect Open again.  This time Apple will ask do you really wan to run this and you should say okay.

**Comment by v-v-x** [comment]
Unfortunately, that didn't help either ((

**Comment by kevinhendricks** [comment]
In waht way does it not work.  I just followed my own set of steps on my wife's laptop which does not have Sigil installed and it worked just fine.  After resizing the MainWindow manually and then opening an epub from her local drive, I was able to change toolbars before closing out of Sigil and then relaunch Sigil and the toolbars changes were all remembered.

So please start fresh.  Delete Sigil.app from your /Applications folder.  Download a fresh copy from github releases.  Unpack it.  Copy it to the /Applications folder.  Right click on it there and select Open, get the nastigram, right click again on it and select Open and say yes when the Mac asks do you really want to open it.

Then once Sigil launches - manually resize the Window.  Then play around with the toolbars then close that MainWindow and exit out of Sigil.

Relaunch and see if your toolbars are now being properly remembered.

**Comment by v-v-x** [comment]
О! I mis the step with resizing the window. It works. Thank you so much!

**Comment by kevinhendricks** [comment]
Glad to hear you have it working.  This issue really seems to only happen for new users of Sigil. I can not recreate the issues you are seeing at all of my old intel mac pro laptop, but other newer users have reported similar issues in our Mobileread user forum.

**Comment by kevinhendricks** [comment]
I am going to leave this bug open for a bit longer so that others running into similar problems can find it and the workaround more easily.

Thank you for your bug report and testing.

**Comment by v-v-x** [comment]
Thank you for your help!

**Comment by kevinhendricks** [comment]
After some research, this behaviour is part of macOS's protection system that it invokes on non-notarized software.  The only solution is to notarize it via Apple and  that something I do not intend to do.

The only other workaround it to remove the Quarantine meta tags before unpacking Sigil and on first launch, resizing the MainWindow.

Closing this since no solution without notarization  is possible.

**Comment by kevinhendricks** [comment]
We now notarize Sigil on macOS, so this issue has now gone away.
