### ISSUE TITLE
[Bug]: Dragging text not working anymore

### ISSUE THREAD

**Issue by mcgratta144** [Sigil-Ebook/Sigil#759]
### Bug Description

After previous update, I cannot drag text from one tag to another or text outside of tag into a tag.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 10 Home

### What version of Sigil are you using?

current

**Comment by dougmassay** [comment]
"Previous Update" is not helpful. What version of Sigil were you using where dragging text worked the way you expect it to? There was certainly no changes from Sigil 2.2.0 to 2.2.1 that would affect this behavior. I'm not even certain the behavior you describe was ever an intended feature of Sigil.

**Comment by dougmassay** [comment]
My bad. Default support for drag and drop in Code View was removed quite a while ago because of crashes being reported. If you know the risks, you can re-enable this unsupported feature by setting an environment variable named SIGIL_ALLOW_CODEVIEW_DROP (starting with Sigil 2.0.1). It doesn't matter what value you set it to.

08dd45c

**Comment by dougmassay** [comment]
More discussion (including links to instructions for setting environment variables on Windows) at: https://www.mobileread.com/forums/showthread.php?t=355784
