### ISSUE TITLE
[Performance Flaw]: Increasengly slow files addition

### ISSUE THREAD

**Issue by Palloxin** [Sigil-Ebook/Sigil#774]
### How to reproduce
1. Create a new epub 2.0
2. Pick 3000 html files and add them to the epub

_See the progress speed become slower and slower_

### Description
The files addition speed becomes painfully slow the more files are present in the queue. The more files u chose to add in the epub the slower the progress will be.

You can test it yourself
RAR file with 3k files from an epub. 12k words per chapter. NO images whatsoever, just text.

https://cdn.discordapp.com/attachments/1265186851157835837/1283419316020187136/3000_xhtml_files.rar?ex=66e2ece1&is=66e19b61&hm=6b0eaa60756321dc9dbecdb77803dce429579687174796d868d9ac3e43b2d098&

I timed every 10% of progress, and the speed does indeed slow down a lot.
![image](https://github.com/user-attachments/assets/1f3dfb74-e862-46dd-bac8-4253afbe0cce)

### Other Details
- I noticed all modifications are way slower the more chapters an epub has.
- The CPU usage of the app never exceeds the 33%.
- My CPU is an Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz, 2501 Mhz, 2 cores, 4 logic processors
- Based on the first 10%, it should have taken 5min. The final result is 7 times that :/

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 10 19044

### What version of Sigil are you using?

2.3.1

**Comment by kevinhendricks** [comment]
Expected behaviour.  This is not a bug.


Each time Sigil adds an xhtml file (and any internal links to css , resources, etc) it must parse and update the epub's OPF, then serialize it and save it just in case a file io error happens at any point along the way (ie, to keep the epub as valid as possible after each file is added to prevent data loss.)

That is a non-linear in nature as the size of the OPF grows.

For file counts of that magnitude, use a python script to pre-create the epub and then edit in Sigil and do not try dynamically add huge numbers of files in series.

**Comment by kevinhendricks** [comment]
FWIW,  in addition to growing the opf (which is the most non-linear part as it grows both the opf manifest and spine - full parsing and serializing with each file added) and updating BookBrowser again after each file is added) it also parses and well formed checks each xhtml file it loads, auto fixing if needed and selected, extracts paths to css files and other resources, creates a cached resource QTextDoument, and loads it, etc.

Again all of this is done to prevent data lossage.  Few if any epub developers are importing even close to a 1000 files into an epub (99% of commercial epubs are less than 100 chapters in size - and most other files are images, css, etc).  Given that, epub file safety with no data lost is more important than speed.

If this is something you are doing in Sigil repeatedly (instead of once) you are probably misusing Sigil for something it was not designed to do. 

But either way ... pre-building a simple opf for a huge set of static files is easily doable in python where you have complete control.

**Comment by Palloxin** [comment]
Do you know how to make the app use more CPU? it never exceed 33%

**Comment by kevinhendricks** [comment]
The AddExisting method is single-threaded and io bound not cpu bound.  You can not have two threads editing and exact same OPF file at the exact same time. 

Most other operations are multi-threaded (using Qt Concurren)  but adding existing files can not be one of those.

Again, you best bet is to write your own Sigil Input plugin.
