### ISSUE TITLE
[Bug]: ICloud Drive folder not accessible through Sigil file browser 

### ISSUE THREAD

**Issue by Lululalu** [Sigil-Ebook/Sigil#775]
### Bug Description

Everytime I want to add images and other files that are stored in the icloud drive folder, I have to copy and paste the files to another folder (the downloads folder for example). It's really annoying sometimes. I wish Sigil would open Finder when I click "add existing files".

### Platform (OS)

macOS

### OS Version / Specifics

15.0

### What version of Sigil are you using?

1.3.1

**Comment by kevinhendricks** [comment]
You can add any device path to the left hand pane of the I/O Window and it will be remembered in all future sessions.  Simply manually navigate to the path and folder you want, then drag and drop that folder to the left hand pane.

 ~/Library/Mobile\ Documents/com~apple~CloudDocs/

Closing since this is already supported in Sigil.  You can also create a symlink to point there to make access even easier.
