### ISSUE TITLE
[Bug]: Allow installation on Windows 11 on ARM

### ISSUE THREAD

**Issue by PictureWilly** [Sigil-Ebook/Sigil#786]
### Bug Description

The Sigil Inno Setup installer supports **only true x64 Intel CPUs**. But Sigil runs fine in x64 emulation mode on Windows 11 on ARM even with plugins installed. 

The change in the InnoSetup script is simple:
- ArchitecturesAllowed=**x64compatible**

This way Sigil could also be installed on any Copilot+ PC which have ARM64 CPUs.

Note: **The latest InnoSetup version has full ARM support**. The values for the supported [architectures identifiers](https://jrsoftware.org/ishelp/index.php?topic=archidentifiers) have been adjusted accordingly.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 11 on ARM 24H2

### What version of Sigil are you using?

current

**Comment by dougmassay** [comment]
I will certainly consider it. But I will need to conduct my own research to verify. Making everyone who builds Sigil on Windows update to the very latest InnoSetup could have consequences. I'd hate for them to start having build failures because their versions of InnoSetup don't grok the x64compatible parameter.

I don't foresee much trouble, but I have to experiment a bit just the same.

**Comment by dougmassay** [comment]
I've got a Windows Beta installer ready to test if it works on Windows arm64. Sigil still needs the Microsoft Visual C++ 2015-2022 Redistributable (x64) to run. I have no idea if that is installed by default on Windows arm64 or not. It's been a part of x64 Windows since Windows 10, so it's no longer included with the Windows Sigil installer.

You can download the beta from my personal github repository: https://github.com/dougmassay/win-qtwebkit-5.212/releases/tag/v5.212-1

It's the asset named Sigil-2.4.0-Beta-2-Windows-x64-Setup.exe

It's a tad bit bigger than the official release versions because I don't take the extra time to ultra compress betas or Continuous Integration builds.

Please let me know if this is enough to let Sigil install and run on Windows arm64.

**Comment by dougmassay** [comment]
Great. Thanks for getting back to me about the new installer working.

**Comment by dougmassay** [comment]
I'm going to close this issue. Feel free to reopen it if you run into problems.
