### ISSUE TITLE
please add name to released versions source code archives

### ISSUE THREAD

**Issue by jirib** [Sigil-Ebook/Sigil#96]
Hi,

i see it is 0.8.7.tar.gz... this is little annoying for people porting to various OS/distros as the dir having all source code would have a file with that name and one cannot quickly know to which app is this filename related.

0.8.7.tar.gz -> Sigil-0.8.7.tar.gz etc...

Thx!

**Comment by kevinhendricks** [comment]
Hi,
Will do in the future.  Understand 0.8.7 is very broken so I would stick with 0.8.6 until the pre-release version of 0.9.0 (in master) is released.  I will be recalling 0.8.7 once pre-0.9.0 comes out.

Kevin

**Comment by jirib** [comment]
Thx. I hope I understood wrong you will release *another* 0.8.7 in the future. If so this is bad approach, it will confuse all ports/package maintainers who depends on chksums on source archives.

**Comment by kevinhendricks** [comment]
No,

I will remove 0.8.7 as it was broken upon release.  No more 0.8.X builds will be made.  The official Sigil 0.8.6 release will be the last of the stable series.  The Sigil 0.8.X branch is now dead.

All work and future releases are based off master (with its embedded python3 interpreter) and it will add partial support for epub3 and continue developing  from there.  Support for epub2 will be continued in the master branch as well.

The previous maintainer released Sigil 0.8.7 simply to update the links for the new github site after the maintainer shift but it included a late change that broke things.  It is simply not worth releasing a new 0.8.X version this close to a 0.9.0-pre release.

Hope this explains things more fully.  If you would like a patch to back out the broken late change let me know and I will send you one. 

Please note, the Sigil 0.8.X branch is broken when it comes to the most recent versions of clang/llvm since it uses NULL reference checks that are now optimized away.  The master tree has had massive changes to fix all of that.  It is simply too large to backport to the 0.8.X branch.

Let me know if you still have questions.

Kevin
